Gate_RuinsOfAlph_Route32_hns_MapScripts::
	.byte 0

Gate_RuinsOfAlph_Route32_EventScript_PokefanM::
	lock
	faceplayer
	msgbox Gate_RuinsOfAlph_Route32_Text_PokefanM, MSGBOX_DEFAULT
	closemessage
	release
	end

Gate_RuinsOfAlph_Route32_EventScript_Youngster::
	lock
	faceplayer
	msgbox Gate_RuinsOfAlph_Route32_Text_Youngster, MSGBOX_DEFAULT
	closemessage
	release
	end

Gate_RuinsOfAlph_Route32_Text_PokefanM:
	.string "¿Estás estudiando las RUINAS?\n"
	.string "Veo madera de científico en ti.$"

Gate_RuinsOfAlph_Route32_Text_Youngster:
	.string "Hay dibujos en unos paneles de\n"
	.string "piedra dentro de las cámaras.\p"
	.string "Intenté moverlos para colocarlos.\n"
	.string "¿Qué misterio ocultarán?$"
