LavenderTown_SoulHouse_hns_MapScripts::
	.byte 0

LavenderTownSoulHouse_EventScript_MrFuji::
	msgbox MrFuji_Text_Main, MSGBOX_NPC
	end
LavenderTownSoulHouse_EventScript_Lass::
	msgbox SoulHouse_Text_Lass, MSGBOX_NPC
	end
LavenderTownSoulHouse_EventScript_Teacher::
	msgbox SoulHouse_Text_Teacher, MSGBOX_NPC
	end
LavenderTownSoulHouse_EventScript_Granny::
	msgbox SoulHouse_Text_Granny, MSGBOX_NPC
	end

MrFuji_Text_Main:
	.string "SR. FUJI: ¡Hola!\p"
	.string "¡Mmm…! Parece que\n"
	.string "estás educando a\p"
	.string "tus POKéMON con\n"
	.string "mucho cariño.\p"
	.string "Los amantes de los\n"
	.string "POKéMON vienen a\p"
	.string "rendir homenaje a\n"
	.string "POKéMON muertos.\p"
	.string "Por favor, muestra\n"
	.string "tu condolencia por\p"
	.string "las almas POKéMON\n"
	.string "que han partido.\p"
	.string "Seguro que eso\n"
	.string "les hará felices.$"
SoulHouse_Text_Teacher:
	.string "Creo que aquí hay\n"
	.string "otras tumbas de\l"
	.string "POKéMON.\p"
	.string "Hay muchas cámaras\n"
	.string "en las que sólo\p"
	.string "puede entrar el\n"
	.string "SR. FUJI.$"
SoulHouse_Text_Lass:
	.string "He venido con mi\n"
	.string "madre a visitar\p"
	.string "las tumbas de los\n"
	.string "POKéMON…$"
SoulHouse_Text_Granny:
	.string "A los POKéMON que\n"
	.string "vivían conmigo…\p"
	.string "los quería como a\n"
	.string "mis nietos…$"
