SaffronCity_Mart_hns_MapScripts::
	.byte 0

SafronMart_EventScript_CooltrainerM::
	msgbox SaffronMart_Text_CooltrainerM, MSGBOX_NPC
	end
SafronMart_EventScript_CooltrainerF::
	msgbox SaffronMart_Text_CooltrainerF, MSGBOX_NPC
	end
SaffronMart_Text_CooltrainerM:
	.string "En PUEBLO LAVANDA hay una gran\n"
	.string "TORRE RADIO.$"

SaffronMart_Text_CooltrainerF:
	.string "Quiero hacerme más fuerte, pero\n"
	.string "todavía no se me da bien…\p"
	.string "¿Podrías enseñarme algún día?$"
