PewterCity_Mart_hns_MapScripts::
	.byte 0

PewterCity_Mart_EventScript_Youngster::
	msgbox PewterCity_Mart_Text_Youngster, MSGBOX_NPC
	end

PewterCity_Mart_EventScript_Nerd::
	msgbox PewterCity_Mart_Text_SuperNerd, MSGBOX_NPC
	end

PewterCity_Mart_Text_Youngster:
	.string "¡Hola! ¡Mira mi GYARADOS!\p"
	.string "Lo crié desde MAGIKARP. No puedo\n"
	.string "creer lo fuerte que se ha vuelto.$"

PewterCity_Mart_Text_SuperNerd:
	.string "Había un anciano raro que vendía\n"
	.string "MAGIKARP.\p"
	.string "Decía que los del LAGO DE LA FURIA\n"
	.string "eran excelentes.$"
