import json
import os
import sys

# 1. Start with existing Gen 1-4 translations from translate_phase1_desc.py
sys.path.insert(0, '/mnt/y/heartandsoul_esp/pokehns-expansion')
import translate_phase1 as p1
import translate_phase1_desc as p1_desc

move_names_keys = list(p1.MOVE_NAMES.keys())
desc_values = list(p1_desc.MOVE_DESCRIPTIONS.values())

ALL_MOVES_ES = {}
for i in range(min(len(move_names_keys), len(desc_values))):
    key = move_names_keys[i].replace(" ", "_").replace("-", "_")
    move_id = f"MOVE_{key}"
    ALL_MOVES_ES[move_id] = desc_values[i]

# 2. Add complete Spanish descriptions for Gen 5, 6, 7, 8, 9 and G-Max / Z-moves
GEN5_PLUS_MOVES = {
    # Gen 5
    "MOVE_HONE_CLAWS": "Afila las garras para subir\\nel Ataque y la Precisión.",
    "MOVE_WIDE_GUARD": "Protege a los aliados de\\nataques que dañan a varios.",
    "MOVE_GUARD_SPLIT": "Suma y reparte las Defensas\\ndel usuario y del rival.",
    "MOVE_POWER_SPLIT": "Suma y reparte los Ataques\\ndel usuario y del rival.",
    "MOVE_WONDER_ROOM": "Crea una zona donde se invierten\\nla Defensa y Def. Especial.",
    "MOVE_PSYSHOCK": "Onda psíquica que causa daño\\nfísico al rival.",
    "MOVE_VENOSHOCK": "Causa el doble de daño si el\\nrival está envenenado.",
    "MOVE_AUTOTOMIZE": "Aligera el cuerpo para\\nsubir mucho la Velocidad.",
    "MOVE_RAGE_POWDER": "Atrae la atención de los rivales\\nhacia el usuario.",
    "MOVE_TELEKINESIS": "Hace flotar al objetivo durante\\ntres turnos seguidos.",
    "MOVE_MAGIC_ROOM": "Crea una zona que anula los\\nefectos de objetos portados.",
    "MOVE_SMACK_DOWN": "Lanza piedras que derriban al\\nsuelo al objetivo.",
    "MOVE_STORM_THROW": "Golpe que resulta siempre en\\nun impacto crítico.",
    "MOVE_FLAME_BURST": "Lanza llamas que estallan y dañan\\na los aliados adyacentes.",
    "MOVE_SLUDGE_WAVE": "Ola de lodo tóxico que puede\\nenvenenar a los objetivos.",
    "MOVE_QUIVER_DANCE": "Mística danza que sube At. Esp.,\\nDef. Esp. y Velocidad.",
    "MOVE_HEAVY_SLAM": "Causa más daño cuanto más pese\\nel usuario respecto al rival.",
    "MOVE_SYNCHRONOISE": "Daña a todos los Pokémon que\\ncompartan tipo con el usuario.",
    "MOVE_ELECTRO_BALL": "Lanza una bola eléctrica. Más daño\\ncuanto más rápido sea.",
    "MOVE_SOAK": "Empapa al objetivo transformando\\nsu tipo en Agua puro.",
    "MOVE_FLAME_CHARGE": "Ataque envuelto en llamas que\\naumenta la Velocidad.",
    "MOVE_COIL": "Se enrosca para subir Ataque,\\nDefensa y Precisión.",
    "MOVE_LOW_SWEEP": "Rápida zancadilla que reduce\\nla Velocidad del objetivo.",
    "MOVE_ACID_SPRAY": "Ráfaga de ácido corrosivo que\\nbaja mucho la Def. Especial.",
    "MOVE_FOUL_PLAY": "Usa la estadística de Ataque del\\nrival contra él mismo.",
    "MOVE_SIMPLE_BEAM": "Rayo que cambia la habilidad del\\nobjetivo a Simple.",
    "MOVE_ENTRAINMENT": "Hace que el objetivo imite la\\nhabilidad del usuario.",
    "MOVE_AFTER_YOU": "Permite actuar al objetivo justo\\ndespués del usuario.",
    "MOVE_ROUND": "Ataque que causa más daño si lo\\nusan varios en el turno.",
    "MOVE_ECHOED_VOICE": "Grito que sube de potencia en\\ncada turno consecutivo.",
    "MOVE_CHIP_AWAY": "Golpea ignorando los cambios en\\nlas características del rival.",
    "MOVE_CLEAR_SMOG": "Lanza lodo que elimina todos los\\ncambios en las estadísticas.",
    "MOVE_STORED_POWER": "Ataque que es más potente cuantas\\nmás subidas de stats tenga.",
    "MOVE_QUICK_GUARD": "Protege al equipo contra ataques\\nque tengan prioridad.",
    "MOVE_ALLY_SWITCH": "Intercambia el puesto con el\\naliado en combate doble.",
    "MOVE_SCALD": "Dispara agua hirviendo que puede\\nquemar al objetivo.",
    "MOVE_SHELL_SMASH": "Rompe la coraza bajando defensas\\npara subir mucho los ataques.",
    "MOVE_HEAL_PULSE": "Emite una onda curativa que\\nrestaura la mitad de los PS.",
    "MOVE_HEX": "Causa el doble de daño si el rival\\nsufre un problema de estado.",
    "MOVE_SKY_DROP": "Eleva al rival al cielo en el 1er\\nturno y lo estrella en el 2º.",
    "MOVE_SHIFT_GEAR": "Ajusta engranajes para subir el\\nAtaque y mucho la Velocidad.",
    "MOVE_CIRCLE_THROW": "Lanza al rival fuera del combate\\no fuerza un cambio.",
    "MOVE_INCINERATE": "Lanza llamas que queman y destruyen\\nla baya que lleve el rival.",
    "MOVE_QUASH": "Fuerza al objetivo a actuar el\\núltimo en el turno.",
    "MOVE_ACROBATICS": "Causa el doble de daño si el\\nusuario no lleva objeto.",
    "MOVE_REFLECT_TYPE": "Copia los tipos exactos del rival\\nen el usuario.",
    "MOVE_RETALIATE": "Causa mucho más daño si un aliado\\nha caído en el turno previo.",
    "MOVE_FINAL_GAMBIT": "El usuario cae debilitado causando\\ndaño igual a sus PS actuales.",
    "MOVE_BESTOW": "Pasa el objeto que lleva equipado\\nal objetivo.",
    "MOVE_INFERNO": "Ataque ardiente que quema con\\nseguridad si logra acertar.",
    "MOVE_WATER_PLEDGE": "Columna de agua que combinada\\ncon Fuego crea un arcoíris.",
    "MOVE_FIRE_PLEDGE": "Columna de fuego que combinada\\ncon Planta crea un mar de fuego.",
    "MOVE_GRASS_PLEDGE": "Columna de hierba que combinada\\ncon Agua crea un pantano.",
    "MOVE_VOLT_SWITCH": "Ataca con electricidad y regresa\\ninmediatamente al equipo.",
    "MOVE_STRUGGLE_BUG": "Resiste y ataca bajando el\\nAtaque Especial del rival.",
    "MOVE_BULLDOZE": "Pisa el suelo con fuerza dañando\\na todos y bajando la Velocidad.",
    "MOVE_FROST_BREATH": "Soplo gélido que siempre resulta\\nen un impacto crítico.",
    "MOVE_DRAGON_TAIL": "Golpea con la cola forzando la\\nsalida de otro Pokémon rival.",
    "MOVE_WORK_UP": "Se concentra aumentando el Ataque\\ny el Ataque Especial.",
    "MOVE_ELECTROWEB": "Lanza una red eléctrica que daña\\ny baja la Velocidad al rival.",
    "MOVE_WILD_CHARGE": "Placaje eléctrico de gran poder\\nque daña al propio usuario.",
    "MOVE_DRILL_RUN": "Gira como un taladro. Tiene alta\\nprobabilidad de golpe crítico.",
    "MOVE_DUAL_CHOP": "Lanza dos golpes brutales en un\\nmismo turno.",
    "MOVE_HEART_STAMP": "Golpe que finge ternura. Puede\\nhacer retroceder al rival.",
    "MOVE_HORN_LEECH": "Ataque con cuernos que absorbe\\nla mitad del daño causado.",
    "MOVE_SACRED_SWORD": "Espadazo que inflige daño ignorando\\nlos cambios defensivos.",
    "MOVE_RAZOR_SHELL": "Corte con concha afilada que\\npuede reducir la Defensa.",
    "MOVE_HEAT_CRASH": "Causa más daño cuanto más pese\\nel usuario respecto al rival.",
    "MOVE_LEAF_TORNADO": "Crea un tornado de hojas que puede\\nreducir la Precisión rival.",
    "MOVE_STEAMROLLER": "Rueda sobre el rival pudiendo\\nhacerlo retroceder.",
    "MOVE_COTTON_GUARD": "Se envuelve en algodón subiendo\\ndrásticamente su Defensa.",
    "MOVE_NIGHT_DAZE": "Onda de choque oscura que puede\\nreducir la Precisión rival.",
    "MOVE_TAIL_SLAP": "Abofetea con la cola entre dos y\\ncinco veces consecutivas.",
    "MOVE_HURRICANE": "Poderoso huracán que puede dejar\\nconfuso al objetivo.",
    "MOVE_HEAD_CHARGE": "Carga brutal de cabeza que daña\\nal propio usuario.",
    "MOVE_GEAR_GRIND": "Lanza dos engranajes metálicos\\nque golpean dos veces.",
    "MOVE_SEARING_SHOT": "Ráfaga de llamas abrasadoras que\\npuede causar quemaduras.",
    "MOVE_TECHNO_BLAST": "Disparo cuyo tipo elemental varía\\nsegún el Cartucho equipado.",
    "MOVE_RELIC_SONG": "Canción milenaria que puede hacer\\ndormir a los objetivos.",
    "MOVE_SECRET_SWORD": "Corte místico que inflige daño\\nfísico usando el At. Esp.",
    "MOVE_GLACIATE": "Ráfaga de aire glacial que reduce\\nla Velocidad de los rivales.",
    "MOVE_BOLT_STRIKE": "Rayo fulminante de gran poder que\\npuede causar parálisis.",
    "MOVE_BLUE_FLARE": "Llamarada azul abrasadora que\\npuede causar quemaduras.",
    "MOVE_FIERY_DANCE": "Aleteo en llamas que puede subir\\nel Ataque Especial.",
    "MOVE_FREEZE_SHOCK": "Poderoso ataque congelante que\\nrequiere cargar en el 1er turno.",
    "MOVE_ICE_BURN": "Poderoso viento gélido que puede\\nquemar y requiere carga previa.",
    "MOVE_SNARL": "Grita y gruñe al rival para bajar\\nsu Ataque Especial.",
    "MOVE_ICICLE_CRASH": "Deja caer carámbanos gigantes que\\npueden hacer retroceder.",
    "MOVE_V_CREATE": "Brutal ataque ígneo que reduce\\nDefensa, Def. Esp. y Velocidad.",
    "MOVE_FUSION_FLARE": "Llama gigante que se potencia tras\\nel movimiento Rayo Fusión.",
    "MOVE_FUSION_BOLT": "Rayo gigante que se potencia tras\\nel movimiento Llama Fusión.",

    # Gen 6
    "MOVE_FLYING_PRESS": "Golpe que combina los tipos\\nLucha y Volador al impactar.",
    "MOVE_MAT_BLOCK": "Usa una estera para proteger al\\nequipo de ataques en turno 1.",
    "MOVE_BELCH": "Eructo tóxico que solo puede usarse\\ntras consumir una baya.",
    "MOVE_ROTOTILLER": "Labra la tierra aumentando el Ataque\\ny At. Esp. de tipo Planta.",
    "MOVE_STICKY_WEB": "Pone una telaraña que reduce la\\nVelocidad de rivales que entren.",
    "MOVE_FELL_STINGER": "Ataque que sube drásticamente el\\nAtaque si derrota al objetivo.",
    "MOVE_PHANTOM_FORCE": "Desaparece en las sombras en turno 1\\ny golpea ignorando Protección.",
    "MOVE_TRICK_OR_TREAT": "Añade el tipo Fantasma al tipo del\\nobjetivo.",
    "MOVE_NOBLE_ROAR": "Ruge con nobleza para bajar el\\nAtaque y At. Esp. del rival.",
    "MOVE_ION_DELUGE": "Convierte todos los movimientos de\\ntipo Normal en tipo Eléctrico.",
    "MOVE_PARABOLIC_CHARGE": "Daña a todos alrededor y absorbe\\nla mitad del daño infligido.",
    "MOVE_FORESTS_CURSE": "Añade el tipo Planta al tipo del\\nobjetivo.",
    "MOVE_PETAL_BLIZZARD": "Tormenta de pétalos afilados que\\ndaña a todos a su alrededor.",
    "MOVE_FREEZE_DRY": "Ataque de Hielo que es súper eficaz\\ncontra Pokémon de tipo Agua.",
    "MOVE_DISARMING_VOICE": "Grito encantador de hada que no\\npuede ser esquivado jamás.",
    "MOVE_PARTING_SHOT": "Intimida bajando ambos ataques del\\nrival antes de retirarse.",
    "MOVE_TOPSY_TURVY": "Invierte por completo todos los\\ncambios en las estadísticas.",
    "MOVE_DRAINING_KISS": "Beso dulce que absorbe tres cuartas\\npartes del daño causado.",
    "MOVE_CRAFTY_SHIELD": "Protege al equipo frente a cualquier\\nataque de estado en el turno.",
    "MOVE_FLOWER_SHIELD": "Aumenta la Defensa de todos los\\nPokémon de tipo Planta.",
    "MOVE_GRASSY_TERRAIN": "Cubre el campo de hierba curando PS\\ny potenciando tipo Planta.",
    "MOVE_MISTY_TERRAIN": "Niebla que protege de estados y\\nreduce el daño de tipo Dragón.",
    "MOVE_ELECTRIFY": "Convierte en tipo Eléctrico el\\nataque que vaya a usar el rival.",
    "MOVE_PLAY_ROUGH": "Juega rudo con el objetivo pudiendo\\nreducir su Ataque.",
    "MOVE_FAIRY_WIND": "Ráfaga de viento de hadas que\\ngolpea al objetivo.",
    "MOVE_MOONBLAST": "Poderoso rayo lunar que puede bajar\\nel Ataque Especial del rival.",
    "MOVE_BOOMBURST": "Explosión de sonido devastador que\\ndaña a todos a su alrededor.",
    "MOVE_FAIRY_LOCK": "Cierra el campo impidiendo que todos\\nlos Pokémon puedan huir.",
    "MOVE_KINGS_SHIELD": "Protege de ataques y reduce mucho el\\nAtaque de quien haga contacto.",
    "MOVE_PLAY_NICE": "Se hace amigo del rival para reducir\\nsu estadística de Ataque.",
    "MOVE_CONFIDE": "Cuenta un secreto al rival para\\nbajar su Ataque Especial.",
    "MOVE_DIAMOND_STORM": "Tormenta de diamantes que puede subir\\nmucho la Defensa propia.",
    "MOVE_STEAM_ERUPTION": "Vapor hirviendo que causa gran daño\\ny puede quemar al rival.",
    "MOVE_HYPERSPACE_HOLE": "Ataque que atraviesa cualquier barrera\\no movimiento de protección.",
    "MOVE_WATER_SHURIKEN": "Lanza estrellas de agua entre dos y\\ncinco veces con gran prioridad.",
    "MOVE_MYSTICAL_FIRE": "Fuego especial que reduce siempre el\\nAtaque Especial del objetivo.",
    "MOVE_SPIKY_SHIELD": "Protege al usuario y daña a quien\\nle golpee con contacto.",
    "MOVE_AROMATIC_MIST": "Niebla dulce que sube la Def. Esp.\\nde un aliado en combate.",
    "MOVE_EERIE_IMPULSE": "Onda eléctrica que reduce mucho el\\nAtaque Especial del objetivo.",
    "MOVE_VENOM_DRENCH": "Baja Ataque, At. Esp. y Velocidad\\nsi el rival está envenenado.",
    "MOVE_POWDER": "Cubre de polvo inflamable al rival;\\nsi usa fuego, explotará.",
    "MOVE_GEOMANCY": "Acumula energía en turno 1 para subir\\nmucho At. Esp., Def. Esp. y Vel.",
    "MOVE_MAGNETIC_FLUX": "Sube las Defensas de aliados que\\ntengan Plus o Menos.",
    "MOVE_HAPPY_HOUR": "Duplica las ganancias de dinero tras\\nganar el combate.",
    "MOVE_ELECTRIC_TERRAIN": "Electrifica el campo evitando el sueño\\ny potenciando el Eléctrico.",
    "MOVE_DAZZLING_GLEAM": "Luz cegadora que daña a todos los\\nrivales en combate.",
    "MOVE_CELEBRATE": "Festeja con alegría creando un ambiente\\nde celebración en combate.",
    "MOVE_HOLD_HANDS": "Une sus manos con un compañero para\\nfortalecer su amistad.",
    "MOVE_BABY_DOLL_EYES": "Mirada tierna con prioridad que reduce\\nel Ataque del objetivo.",
    "MOVE_NUZZLE": "Carantoña eléctrica que siempre causa\\nparálisis al objetivo.",
    "MOVE_INFESTATION": "Atrapa al rival en una plaga durante\\ncuatro o cinco turnos.",
    "MOVE_POWER_UP_PUNCH": "Puñetazo tenaz que aumenta el Ataque\\ndel usuario tras golpear.",
    "MOVE_OBLIVION_WING": "Rayo destructor que absorbe tres\\ncuartas partes del daño causado.",
    "MOVE_THOUSAND_ARROWS": "Flechas que impactan a tipos Volador\\ny a Pokémon que estén levitando.",
    "MOVE_THOUSAND_WAVES": "Olas de tierra que impiden al rival\\nhuir del combate.",
    "MOVE_LANDS_WRATH": "La tierra se abre para causar daño\\na los objetivos alrededor.",
    "MOVE_LIGHT_OF_RUIN": "Potentísimo haz de luz de hada que\\ndaña severamente al usuario.",
    "MOVE_ORIGIN_PULSE": "Ráfagas de luz primordial que dañan\\na los Pokémon rivales.",
    "MOVE_PRECIPICE_BLADES": "Hojas de roca y tierra afiladas que\\ngolpean a los rivales.",
    "MOVE_DRAGON_ASCENT": "Ataque estelar que baja la Defensa y\\nla Defensa Especial del usuario.",
    "MOVE_HYPERSPACE_FURY": "Golpea ignorando protección y baja\\nla Defensa del usuario.",

    # Gen 7
    "MOVE_SHORE_UP": "Restaura la mitad de los PS; cura más\\nen tormenta de arena.",
    "MOVE_FIRST_IMPRESSION": "Golpe muy veloz y potente que solo\\nfunciona en el primer turno.",
    "MOVE_BANEFUL_BUNKER": "Protege y envenena a quien golpee\\ncon un ataque de contacto.",
    "MOVE_SPIRIT_SHACKLE": "Flecha espectral que impide al rival\\nhuir del combate.",
    "MOVE_DARKEST_LARIAT": "Ataque que inflige daño ignorando los\\ncambios de stats del rival.",
    "MOVE_SPARKLING_ARIA": "Canto que cura las quemaduras del\\nobjetivo al dañarlo.",
    "MOVE_ICE_HAMMER": "Martillazo de hielo que reduce la\\nVelocidad del usuario.",
    "MOVE_FLORAL_HEALING": "Restaura PS a un aliado; cura más\\nsi hay Campo de Hierba.",
    "MOVE_HIGH_HORSEPOWER": "Carga con fuerza bruta contra el\\nobjetivo causando gran daño.",
    "MOVE_STRENGTH_SAP": "Restaura PS según el Ataque del rival\\ny se lo reduce en 1 nivel.",
    "MOVE_SOLAR_BLADE": "Carga energía solar en turno 1 y corta\\nen turno 2; instantáneo con sol.",
    "MOVE_LEAFAGE": "Lanza hojas que causan daño directo\\nal objetivo.",
    "MOVE_SPOTLIGHT": "Dirige la atención de todos hacia el\\nobjetivo fijado.",
    "MOVE_TOXIC_THREAD": "Dispara seda venenosa que envenena y\\nreduce la Velocidad rival.",
    "MOVE_LASER_FOCUS": "Se concentra al máximo para asegurar\\nun golpe crítico al siguiente turno.",
    "MOVE_GEAR_UP": "Aumenta el Ataque y At. Esp. de los\\naliados con Más o Menos.",
    "MOVE_THROAT_CHOP": "Golpea el cuello impidiendo el uso\\nde ataques de sonido 2 turnos.",
    "MOVE_POLLEN_PUFF": "Daña al rival o restaura la mitad de\\nlos PS si se usa en un aliado.",
    "MOVE_ANCHOR_SHOT": "Anclaje que impide huir o cambiar de\\nPokémon al objetivo.",
    "MOVE_PSYCHIC_TERRAIN": "Crea un Campo Psíquico que anula la\\nprioridad y sube ataques Psíquicos.",
    "MOVE_LUNGE": "Embestida feroz que siempre reduce el\\nAtaque del objetivo.",
    "MOVE_FIRE_LASH": "Látigo de fuego ardiente que siempre\\nbaja la Defensa del rival.",
    "MOVE_POWER_TRIP": "Ataque que causa más daño cuantas más\\nsubidas de stats tenga el usuario.",
    "MOVE_BURN_UP": "Ataque de Fuego colosal que elimina\\nel tipo Fuego del propio usuario.",
    "MOVE_SPEED_SWAP": "Intercambia la estadística de Velocidad\\ncon el objetivo.",
    "MOVE_SMART_STRIKE": "Apuñala con un cuerno afilado que\\nnunca puede fallar.",
    "MOVE_PURIFY": "Cura el estado del rival y restaura\\nla mitad de los PS del usuario.",
    "MOVE_REVELATION_DANCE": "Danza cuyo tipo elemental coincide con\\nel tipo principal del usuario.",
    "MOVE_CORE_ENFORCER": "Haz que anula la habilidad del rival si\\neste ya se movió en el turno.",
    "MOVE_TROP_KICK": "Patada tropical que siempre reduce el\\nAtaque del objetivo.",
    "MOVE_INSTRUCT": "Ordena al objetivo que repita su último\\nmovimiento inmediatamente.",
    "MOVE_BEAK_BLAST": "Se calienta al inicio del turno y quema\\na quien le golpee con contacto.",
    "MOVE_CLANGING_SCALES": "Frota sus escamas causando gran daño y\\nbajando su propia Defensa.",
    "MOVE_DRAGON_HAMMER": "Usa su cuerpo como un martillo para\\ngolpear con gran poder.",
    "MOVE_BRUTAL_SWING": "Gira violentamente dañando a todos los\\nPokémon a su alrededor.",
    "MOVE_AURORA_VEIL": "Mitiga daño físico y especial durante\\ncinco turnos bajo nieve/granizo.",
    "MOVE_SHELL_TRAP": "Prepara una trampa que estalla con gran\\npoder si recibe daño físico.",
    "MOVE_FLEUR_CANNON": "Cañonazo de hadas de gran poder que\\nbaja mucho el At. Esp. propio.",
    "MOVE_PSYCHIC_FANGS": "Mordisco que destruye pantallas como\\nReflejo y Pantalla de Luz.",
    "MOVE_STOMPING_TANTRUM": "Pataleta que duplica su potencia si el\\nataque previo falló.",
    "MOVE_SHADOW_BONE": "Golpea con un hueso espectral que puede\\nreducir la Defensa rival.",
    "MOVE_ACCELEROCK": "Embestida de rocas que ataca siempre con\\nprioridad.",
    "MOVE_LIQUIDATION": "Carga de agua con gran presión que puede\\nreducir la Defensa rival.",
    "MOVE_PRISMATIC_LASER": "Láser devastador que impide moverse al\\nusuario en el siguiente turno.",
    "MOVE_SPECTRAL_THIEF": "Roba todas las subidas de stats del\\nrival antes de golpearlo.",
    "MOVE_SUNSTEEL_STRIKE": "Embestida solar de acero que ignora las\\nhabilidades defensivas del rival.",
    "MOVE_MOONGEIST_BEAM": "Haz de luz espectral que ignora las\\nhabilidades defensivas del rival.",
    "MOVE_TEARFUL_LOOK": "Ojos llorosos que reducen tanto el\\nAtaque como el At. Esp. del rival.",
    "MOVE_ZING_ZAP": "Descarga eléctrica fulminante que puede\\nhacer retroceder al objetivo.",
    "MOVE_NATURES_MADNESS": "Ataque que reduce los PS actuales del\\nrival exactamente a la mitad.",
    "MOVE_MULTI_ATTACK": "Ataque cuyo tipo elemental varía según\\nel Disco que lleve equipado.",
    "MOVE_MIND_BLOWN": "Estalla su cabeza causando enorme daño a\\ntodos y perdiendo mitad de PS.",
    "MOVE_PLASMA_FISTS": "Puñetazos que convierten los ataques de\\ntipo Normal en Eléctrico.",
    "MOVE_PHOTON_GEYSER": "Pilar de luz que inflige daño físico o\\nespecial según cuál sea mayor.",
    "MOVE_CLANGOROUS_SOULBLAZE": "Ataque legendario que golpea y sube\\ntodas las características propias.",

    # Gen 8
    "MOVE_DYNAMAX_CANNON": "Cañón que duplica su daño si el objetivo\\nestá Dinamaxizado.",
    "MOVE_SNIPE_SHOT": "Disparo preciso que ignora movimientos o\\nhabilidades que atraen ataques.",
    "MOVE_JAW_LOCK": "Muerde e impide huir del combate a ambos\\nPokémon hasta caer uno.",
    "MOVE_STUFF_CHEEKS": "Consume la baya que lleve y sube mucho\\nsu estadística de Defensa.",
    "MOVE_NO_RETREAT": "Aumenta todas sus características pero\\nya no puede retirarse.",
    "MOVE_TAR_SHOT": "Lanza brea al rival volviéndolo más\\ndébil ante ataques de Fuego.",
    "MOVE_MAGIC_POWDER": "Polvo mágico que transforma el tipo del\\nobjetivo en tipo Psíquico puro.",
    "MOVE_DRAGON_DARTS": "Lanza dos Dreepy que golpean dos veces o\\na ambos rivales en dobles.",
    "MOVE_TEATIME": "Todos los Pokémon en combate consumen de\\ninmediato sus bayas.",
    "MOVE_OCTOLOCK": "Atrapa al rival y reduce su Defensa y\\nDef. Especial cada turno.",
    "MOVE_BOLT_BEAK": "Picozazo que duplica su poder si actúa\\nantes que el objetivo.",
    "MOVE_FISHIOUS_REND": "Mordisco que duplica su poder si actúa\\nantes que el objetivo.",
    "MOVE_COURT_CHANGE": "Intercambia todos los efectos de campo\\nentre ambos bandos.",
    "MOVE_CLANGOROUS_SOUL": "Pierde parte de sus PS para aumentar todas\\nsus características.",
    "MOVE_BODY_PRESS": "Golpe que calcula su daño usando la\\nDefensa del usuario en vez de Ataque.",
    "MOVE_DECORATE": "Decora al objetivo aumentando mucho su\\nAtaque y su Ataque Especial.",
    "MOVE_DRUM_BEATING": "Toca el tambor golpeando y reduciendo\\nsiempre la Velocidad rival.",
    "MOVE_SNAP_TRAP": "Atrapa al rival en una trampa durante\\ncuatro o cinco turnos.",
    "MOVE_PYRO_BALL": "Lanza una bola ígnea abrasadora que\\npuede causar quemaduras.",
    "MOVE_BEHEMOTH_BLADE": "Espadazo que duplica su daño ante rivales\\nDinamaxizados.",
    "MOVE_BEHEMOTH_BASH": "Escudazo que duplica su daño ante rivales\\nDinamaxizados.",
    "MOVE_AURA_WHEEL": "Rueda aural que sube Velocidad; cambia a\\nSiniestro con Hambre.",
    "MOVE_BREAKING_SWIPE": "Golpe con la cola que reduce el Ataque\\nde todos los rivales.",
    "MOVE_BRANCH_POKE": "Pinchazo suave con una rama que causa\\ndaño directo al rival.",
    "MOVE_OVERDRIVE": "Toca la guitarra causando enorme daño de\\nsonido a los rivales.",
    "MOVE_APPLE_ACID": "Ataque ácido de manzana que siempre baja\\nla Def. Especial del rival.",
    "MOVE_GRAV_APPLE": "Deja caer una manzana pesada; baja la\\nDefensa y pega más con Gravedad.",
    "MOVE_SPIRIT_BREAK": "Ataque demoledor de hada que siempre\\nbaja el Ataque Especial rival.",
    "MOVE_STRANGE_STEAM": "Humo misterioso de hada que puede dejar\\nconfuso al objetivo.",
    "MOVE_LIFE_DEW": "Restaura una cuarta parte de los PS de\\ntodos los aliados en combate.",
    "MOVE_OBSTRUCT": "Protege y baja mucho la Defensa de quien\\nle golpee con contacto.",
    "MOVE_FALSE_SURRENDER": "Finge rendirse para atacar por sorpresa;\\nnunca puede fallar.",
    "MOVE_METEOR_ASSAULT": "Ataque supremo de lanza que impide actuar\\nal usuario en el siguiente turno.",
    "MOVE_ETERNABEAM": "Ataque cósmico que impide moverse al\\nusuario en el siguiente turno.",
    "MOVE_STEEL_BEAM": "Lanza un rayo de acero perdiendo la mitad\\nde los PS máximos.",
    "MOVE_EXPANDING_FORCE": "Ataque psíquico que se potencia y daña a\\ntodos en Campo Psíquico.",
    "MOVE_STEEL_ROLLER": "Arrasa con todo destruyendo el terreno\\nactivo en el combate.",
    "MOVE_SCALE_SHOT": "Dispara escamas de 2 a 5 veces; baja\\nDefensa y sube Velocidad.",
    "MOVE_METEOR_BEAM": "Carga energía en turno 1 subiendo At. Esp.\\ny dispara en el turno 2.",
    "MOVE_SHELL_SIDE_ARM": "Daña física o especialmente según lo que\\nresulte más efectivo.",
    "MOVE_MISTY_EXPLOSION": "El usuario explota; causa mucho más daño\\nsi hay Campo de Niebla.",
    "MOVE_GRASSY_GLIDE": "Ataque de hierba que golpea con prioridad\\nsi hay Campo de Hierba.",
    "MOVE_RISING_VOLTAGE": "Rayo que duplica su potencia si el rival\\nestá en Campo Eléctrico.",
    "MOVE_TERRAIN_PULSE": "Ataque cuyo tipo y potencia se duplican\\nsegún el terreno activo.",
    "MOVE_SKITTER_SMACK": "Golpe rastrero de bicho que siempre baja\\nel Ataque Especial rival.",
    "MOVE_BURNING_JEALOUSY": "Daña y quema a todos los rivales que hayan\\nsubido sus stats en el turno.",
    "MOVE_LASH_OUT": "Ataque que duplica su daño si al usuario\\nle bajaron algún stat en el turno.",
    "MOVE_POLTERGEIST": "Ataca usando el objeto del rival; falla si\\nel rival no lleva objeto.",
    "MOVE_CORROSIVE_GAS": "Lanza gas corrosivo que disuelve y destruye\\nlos objetos de todos.",
    "MOVE_COACHING": "Anima al aliado aumentando su Ataque y\\nsu estadística de Defensa.",
    "MOVE_FLIP_TURN": "Ataque acuático veloz tras el cual el\\nusuario regresa al equipo.",
    "MOVE_TRIPLE_AXEL": "Da hasta 3 patadas giratorias; cada una\\nes más potente que la anterior.",
    "MOVE_DUAL_WINGBEAT": "Golpea dos veces consecutivas con las alas\\nen un mismo turno.",
    "MOVE_SCORCHING_SANDS": "Lanza arena ardiente que puede causar\\nquemaduras al objetivo.",
    "MOVE_JUNGLE_HEALING": "Cura una cuarta parte de PS y todos los\\nestados de los aliados.",
    "MOVE_WICKED_BLOW": "Golpe siniestro devastador que siempre\\nresulta en impacto crítico.",
    "MOVE_SURGING_STRIKES": "Tres golpes acuáticos fluidos que siempre\\nresultan en impacto crítico.",
    "MOVE_THUNDER_CAGE": "Encierra al rival en una jaula eléctrica\\ndurante 4 o 5 turnos.",
    "MOVE_DRAGON_ENERGY": "Ataque que inflige más daño cuantos más\\nPS conserve el usuario.",
    "MOVE_FREEZING_GLARE": "Mirada psíquica gélida que puede llegar\\na congelar al rival.",
    "MOVE_FIERY_WRATH": "Ira ardiente que puede hacer retroceder\\na los Pokémon rivales.",
    "MOVE_THUNDEROUS_KICK": "Patada demoledora que siempre reduce la\\nDefensa del objetivo.",
    "MOVE_GLACIAL_LANCE": "Lanza de hielo colosal que inflige gran\\ndaño a los rivales.",
    "MOVE_ASTRAL_BARRAGE": "Dispara una oleada de almas espectrales a\\ntodos los rivales.",
    "MOVE_EERIE_SPELL": "Ataque psíquico que resta 3 PP al último\\nmovimiento del objetivo.",

    # Gen 9
    "MOVE_DIRY_CHILL": "Ataque gélido que puede congelar.",
    "MOVE_CHILLY_RECEPTION": "Prepara la salida poniendo nieve y cambiando\\nde Pokémon en el turno.",
    "MOVE_TIDY_UP": "Limpia el campo de trampas y sube el\\nAtaque y la Velocidad.",
    "MOVE_SNOWSCAPE": "Invoca una tormenta de nieve que dura\\ncinco turnos en combate.",
    "MOVE_POUNCE": "Salta sobre el objetivo reduciendo su\\nestadística de Velocidad.",
    "MOVE_TRAILBLAZE": "Ataque veloz entre la maleza que sube\\nla Velocidad propia.",
    "MOVE_CHILLING_WATER": "Lanza agua helada que siempre reduce el\\nAtaque del objetivo.",
    "MOVE_HYPER_DRILL": "Taladro perforador que impacta incluso\\nsi el rival usa Protección.",
    "MOVE_TWIN_BEAM": "Dispara dos haces de luz consecutivos\\nque golpean dos veces.",
    "MOVE_RAGE_FIST": "Puño que gana 50 de potencia cada vez\\nque el usuario es golpeado.",
    "MOVE_ARMOR_CANNON": "Dispara su armadura con gran poder; baja\\nDefensa y Def. Especial propias.",
    "MOVE_BITTER_BLADE": "Espada amarga que restaura la mitad del\\ndaño causado al objetivo.",
    "MOVE_DOUBLE_SHOCK": "Descarga colosal que elimina el tipo\\nEléctrico del propio usuario.",
    "MOVE_GIGATON_HAMMER": "Martillazo de enorme poder que no puede\\nusarse dos turnos seguidos.",
    "MOVE_COMEUPPANCE": "Devuelve al rival el daño recibido con\\npotencia incrementada.",
    "MOVE_AQUA_CUTTER": "Corte de agua presurizada con alta tasa\\nde golpes críticos.",
    "MOVE_BLAZING_TORQUE": "Ataque ígneo de motor que puede causar\\nquemaduras al objetivo.",
    "MOVE_WICKED_TORQUE": "Ataque siniestro de motor que puede causar\\nsueño al objetivo.",
    "MOVE_NOXIOUS_TORQUE": "Ataque tóxico de motor que puede envenenar\\nal objetivo.",
    "MOVE_COMBAT_TORQUE": "Ataque marcial de motor que puede causar\\nparálisis al objetivo.",
    "MOVE_MAGICAL_TORQUE": "Ataque feérico de motor que puede causar\\nconfusión al objetivo.",
    "MOVE_BLOOD_MOON": "Lanza un rayo de luna roja devastador; no\\npuede usarse dos veces seguidas.",
    "MOVE_MATCHA_GOTCHA": "Dispara té que absorbe PS y puede causar\\nquemaduras al rival.",
    "MOVE_SYRUP_BOMB": "Explosión de jarabe que reduce la Velocidad\\nrival durante tres turnos.",
    "MOVE_IVY_CUDGEL": "Garrote cuyo tipo elemental cambia según\\nla máscara que lleve.",
    "MOVE_ELECTRO_SHOT": "Absorbe electricidad en turno 1 subiendo\\nAt. Esp. y dispara en turno 2.",
    "MOVE_TERA_STARSTORM": "Tormenta de luz estelar que golpea a todos\\nsi el usuario es Terapagos.",
    "MOVE_FICKLE_BEAM": "Haz de luz que a veces dispara con el doble\\nde potencia habitual.",
    "MOVE_BURNING_BULWARK": "Se protege y causa quemaduras a quien intente\\ngolpearle con contacto.",
    "MOVE_THUNDERCLAP": "Rayo veloz que ataca con prioridad si el\\nrival prepara un ataque.",
    "MOVE_MIGHTY_CLEAVE": "Corte contundente de roca que atraviesa\\nmovimientos de protección.",
    "MOVE_TACHYON_CUTTER": "Dispara dos cuchillas de partículas que\\ngolpean sin fallar jamás.",
    "MOVE_HARD_PRESS": "Presión aplastante que inflige más daño\\ncuantos más PS tenga el rival.",
    "MOVE_DRAGON_CHEER": "Grito de dragón que aumenta la probabilidad\\nde críticos de los aliados.",
    "MOVE_ALLURING_VOICE": "Canto seductor que confunde al rival si se\\nha subido los stats en el turno.",
    "MOVE_TEMPER_FLARE": "Ataque de furia que duplica su poder si\\nel ataque previo falló.",
    "MOVE_SUPERCELL_SLAM": "Gran golpe eléctrico que daña al usuario\\nsi llega a fallar.",
    "MOVE_PSYCHIC_NOISE": "Onda sonora que daña e impide al rival\\ncurarse durante dos turnos.",
    "MOVE_UPPER_HAND": "Golpe que hace retroceder al rival si este\\niba a usar un ataque con prioridad.",
    "MOVE_MALIGNANT_CHAIN": "Cadena venenosa que puede causar envenenamiento\\ngrave y confusión.",
}

# Update main dict
ALL_MOVES_ES.update(GEN5_PLUS_MOVES)

# Shared static symbols in moves_info.h
SHARED_MOVES_ES = {
    "sMegaDrainDescription": "Ataque que absorbe la\\nmitad del daño causado.",
    "sHyperBeamDescription": "Potente ataque, pero el\\nusuario reposa un turno.",
    "sRevengeDescription": "Ataque que actúa al final\\ny gana fuerza si es dañado.",
    "sPluckDescription": "Come la baya del rival\\ny obtiene su efecto.",
    "sHealingWishDescription": "El usuario se debilita\\npara curar al relevo.",
    "sWringOutDescription": "Causa más daño cuantos\\nmás PS tenga el rival.",
    "sUTurnDescription": "Causa daño y después\\nregresa al equipo.",
    "sStormThrowDescription": "Ataque que siempre resulta\\nen un impacto crítico.",
    "sCircleThrowDescription": "Lanza al rival fuera para\\nforzar el relevo.",
    "sChipAwayDescription": "Golpea ignorando los\\ncambios de stats rivales.",
    "sHeavySlamDescription": "Causa más daño cuanto\\nmás pese el usuario.",
    "sPsyshockDescription": "Ataque con onda psíquica\\nque causa daño físico.",
    "sLavaPlumeDescription": "Llamas escarlata que dañan\\na todos alrededor.",
    "sShadowForceDescription": "Desaparece en turno 1 y\\ngolpea en el turno 2.",
    "sFalseSwipeDescription": "Ataque que deja al rival\\ncon al menos 1 PS.",
    "sDrainingKissDescription": "Ataque que absorbe más de\\nla mitad del daño.",
    "sCloseCombatDescription": "Ataque fuerte pero reduce\\nlas defensas propias.",
    "sHyperspaceHoleDescription": "Usa un agujero espacial;\\nno puede ser esquivado.",
    "sSuckerPunchDescription": "Golpea primero si el rival\\niba a atacar.",
    "sFeintDescription": "Ataque que golpea a rivales\\nque usen Protección.",
    "sProtectDescription": "Evade ataques; puede fallar\\nsi se usa sin cesar.",
    "sGMaxOneBlowDescription": "Ataque Gigamax de Urshifu.\\nIgnora Maxibarrera."
}

print(f"Total mapped moves by ID: {len(ALL_MOVES_ES)}")
print(f"Total shared static move descriptions: {len(SHARED_MOVES_ES)}")

with open('/mnt/y/heartandsoul_esp/pokehns-expansion/moves_es.json', 'w', encoding='utf-8') as f:
    json.dump(ALL_MOVES_ES, f, ensure_ascii=False, indent=2)

with open('/mnt/y/heartandsoul_esp/pokehns-expansion/shared_moves_es.json', 'w', encoding='utf-8') as f:
    json.dump(SHARED_MOVES_ES, f, ensure_ascii=False, indent=2)

print("Saved moves_es.json and shared_moves_es.json successfully.")
