import json

with open('/mnt/y/heartandsoul_esp/pokehns-expansion/raw_items.json', 'r', encoding='utf-8') as f:
    items = json.load(f)

ITEM_DESC_ES = {
    # Poké Balls
    "ITEM_STRANGE_BALL": "Una Ball inusual\\nque traspasa el\\nespacio y tiempo.",
    "ITEM_POKE_BALL": "Dispositivo para\\ncapturar Pokémon\\nsalvajes.",
    "ITEM_GREAT_BALL": "Buena Ball con\\nmayor índice de\\néxito que la estándar.",
    "ITEM_ULTRA_BALL": "Gran Ball con muy\\nalto índice de\\néxito al capturar.",
    "ITEM_MASTER_BALL": "La mejor Ball.\\nAtrapa al Pokémon\\nsin fallar jamás.",
    "ITEM_PREMIER_BALL": "Ball especial hecha\\npara conmemorar\\nun evento.",
    "ITEM_HEAL_BALL": "Ball curativa que\\nrestaura los PS\\ndel Pokémon atrapado.",
    "ITEM_NET_BALL": "Funciona muy bien\\ncon Pokémon de\\ntipo Agua o Bicho.",
    "ITEM_NEST_BALL": "Funciona mejor con\\nPokémon salvajes de\\nmenor nivel.",
    "ITEM_DIVE_BALL": "Funciona mejor con\\nPokémon que viven en\\nel fondo del mar.",
    "ITEM_DUSK_BALL": "Funciona muy bien\\nen lugares oscuros\\no de noche.",
    "ITEM_TIMER_BALL": "Mejora su eficacia\\ncuantos más turnos\\ndure el combate.",
    "ITEM_QUICK_BALL": "Muy eficaz si se\\nusa en el primer\\nturno del combate.",
    "ITEM_REPEAT_BALL": "Muy eficaz con\\nespecies ya atrapadas\\nanteriormente.",
    "ITEM_LUXURY_BALL": "Una Ball acogedora\\nque hace al Pokémon\\nmás simpático.",
    "ITEM_LEVEL_BALL": "Más eficaz cuanto\\nmayor sea el nivel\\ndel usuario.",
    "ITEM_LURE_BALL": "Muy eficaz con los\\nPokémon atrapados\\npescando.",
    "ITEM_MOON_BALL": "Eficaz con Pokémon\\nque evolucionan con\\nPiedra Lunar.",
    "ITEM_FRIEND_BALL": "Hace que el Pokémon\\natrapado se vuelva\\namigable.",
    "ITEM_LOVE_BALL": "Muy eficaz con\\nPokémon del género\\nopuesto al tuyo.",
    "ITEM_HEAVY_BALL": "Eficaz al capturar\\nPokémon de gran\\npeso corporal.",
    "ITEM_FAST_BALL": "Muy eficaz con\\nPokémon capaces de\\nhuir rápidamente.",
    "ITEM_SPORT_BALL": "Ball especial que\\nse usaba en el\\nConcurso de Captura.",
    "ITEM_SAFARI_BALL": "Ball especial usada\\nen la Zona Safari\\npara capturar.",
    "ITEM_DREAM_BALL": "Ball especial que\\nfacilita atrapar\\nPokémon dormidos.",
    "ITEM_BEAST_BALL": "Diseñada para tener\\néxito al atrapar\\nUltraentes.",
    "ITEM_CHERISH_BALL": "Ball conmemorativa\\nmuy rara creada para\\ncelebrar un evento.",
    "ITEM_PARK_BALL": "Ball especial usada\\nen el Parque Pal\\npara capturas.",

    # Medicina / Pociones
    "ITEM_POTION": "Restaura los PS de\\nun Pokémon en\\n20 puntos.",
    "ITEM_SUPER_POTION": "Restaura los PS de\\nun Pokémon en\\n60 puntos.",
    "ITEM_HYPER_POTION": "Restaura los PS de\\nun Pokémon en\\n120 puntos.",
    "ITEM_MAX_POTION": "Restaura por completo\\ntodos los PS de\\nun Pokémon.",
    "ITEM_FULL_RESTORE": "Restaura todos los\\nPS y cura estados\\nde un Pokémon.",
    "ITEM_REVIVE": "Revive a un Pokémon\\ndebilitado con la\\nmitad de sus PS.",
    "ITEM_ANTIDOTE": "Cura a un Pokémon\\ndel envenenamiento.",
    "ITEM_BURN_HEAL": "Cura a un Pokémon\\nde una quemadura.",
    "ITEM_ICE_HEAL": "Descongela a un\\nPokémon congelado.",
    "ITEM_AWAKENING": "Despierta a un\\nPokémon dormido.",
    "ITEM_PARLYZ_HEAL": "Cura la parálisis\\nde un Pokémon.",
    "ITEM_FULL_HEAL": "Cura todos los\\nproblemas de estado\\nde un Pokémon.",
    "ITEM_REVIVAL_HERB": "Hierba muy amarga\\nque revive con todos\\nlos PS al Pokémon.",
    "ITEM_ETHER": "Restaura 10 PP de\\nun movimiento de\\nun Pokémon.",
    "ITEM_MAX_ETHER": "Restaura todos los\\nPP de un movimiento\\nde un Pokémon.",
    "ITEM_ELIXIR": "Restaura 10 PP de\\ntodos los movimientos\\nde un Pokémon.",
    "ITEM_MAX_ELIXIR": "Restaura todos los\\nPP de los ataques\\nde un Pokémon.",
    "ITEM_FRESH_WATER": "Agua mineral que\\nrestaura 30 PS de\\nun Pokémon.",
    "ITEM_SODA_POP": "Refresco con gas\\nque restaura 50 PS\\nde un Pokémon.",
    "ITEM_LEMONADE": "Bebida dulce que\\nrestaura 70 PS de\\nun Pokémon.",
    "ITEM_MOOMOO_MILK": "Leche muy nutritiva\\nque restaura 100 PS\\nde un Pokémon.",
    "ITEM_ENERGY_POWDER": "Polvo amargo que\\nrestaura 60 PS de\\nun Pokémon.",
    "ITEM_ENERGY_ROOT": "Raíz muy amarga\\nque restaura 120 PS\\nde un Pokémon.",
    "ITEM_HEAL_POWDER": "Polvo amargo que\\ncura problemas de\\nestado en Pokémon.",
    "ITEM_LAVA_COOKIE": "Especialidad local\\nque cura todos los\\nestados alterados.",
    "ITEM_BERRY_JUICE": "Zumo puro de bayas\\nque restaura 20 PS\\nde un Pokémon.",
    "ITEM_SACRED_ASH": "Revive a todos los\\nPokémon debilitados\\ncon todos sus PS.",

    # Vitaminas
    "ITEM_HP_UP": "Aumenta los PS base\\nde un Pokémon.",
    "ITEM_PROTEIN": "Aumenta el Ataque\\nbase de un Pokémon.",
    "ITEM_IRON": "Aumenta la Defensa\\nbase de un Pokémon.",
    "ITEM_CARBOS": "Aumenta la Velocidad\\nbase de un Pokémon.",
    "ITEM_CALCIUM": "Aumenta el At. Esp.\\nbase de un Pokémon.",
    "ITEM_RARE_CANDY": "Sube el nivel de un\\nPokémon en 1 punto.",
    "ITEM_PP_UP": "Aumenta los PP\\nmáximos de un ataque.",
    "ITEM_ZINC": "Aumenta la Def. Esp.\\nbase de un Pokémon.",
    "ITEM_PP_MAX": "Aumenta los PP al\\nmáximo de un ataque.",

    # Piedras de evolución
    "ITEM_FIRE_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_WATER_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_THUNDER_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_LEAF_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_MOON_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_SUN_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_SHINY_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_DUSK_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_DAWN_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_ICE_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_OVAL_STONE": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "ITEM_LINK_CABLE": "Misterioso cable que\\nhace evolucionar a\\nciertos Pokémon.",

    # Objetos competitivos / Held
    "ITEM_CHOICE_BAND": "Potencia el Ataque\\npero solo permite un\\nmovimiento.",
    "ITEM_CHOICE_SPECS": "Potencia el At. Esp.\\npero solo permite un\\nmovimiento.",
    "ITEM_CHOICE_SCARF": "Sube la Velocidad\\npero solo permite un\\nmovimiento.",
    "ITEM_LIFE_ORB": "Potencia los ataques\\na costa de perder PS\\nen cada golpe.",
    "ITEM_FOCUS_SASH": "Permite resistir con\\n1 PS un golpe fulminante\\nsi tiene salud máxima.",
    "ITEM_FOCUS_BAND": "Puede evitar ser\\ndebilitado dejando\\nal Pokémon con 1 PS.",
    "ITEM_LEFTOVERS": "Restaura PS de forma\\ngradual en cada turno\\ndel combate.",
    "ITEM_ROCKY_HELMET": "Daña al rival que le\\ngolpee con ataques de\\ncontacto directo.",
    "ITEM_EVIOLITE": "Sube Defensas a un\\nPokémon que aún pueda\\nevolucionar.",
    "ITEM_ASSAULT_VEST": "Sube la Def. Esp.\\npero impide usar\\nataques de estado.",
    "ITEM_HEAVY_DUTY_BOOTS": "Protege al portador\\nde trampas en el campo\\ncomo Trampa Rocas.",
    "ITEM_CLEAR_AMULET": "Protege al portador\\nde bajadas en sus\\ncaracterísticas.",
    "ITEM_COVERT_CLOAK": "Protege de los efectos\\nsecundarios de ataques\\nque reciba el portador.",
    "ITEM_LOADED_DICE": "Asegura más golpes con\\nataques multigolpe.",
    "ITEM_BOOSTER_ENERGY": "Activa Paleosíntesis\\no Carga Cuark del\\nportador en combate.",
    "ITEM_EXPERT_BELT": "Potencia los ataques\\nque resulten ser\\nsúpereficaces.",
    "ITEM_WIDE_LENS": "Lupa que aumenta\\nligeramente la precisión\\nde los ataques.",
    "ITEM_ZOOM_LENS": "Sube la precisión si\\nel portador ataca tras\\nel rival.",
    "ITEM_SCOPE_LENS": "Aumenta la probabilidad\\nde asestar golpes\\ncríticos.",
    "ITEM_MUSCLE_BAND": "Aumenta ligeramente\\nla potencia de ataques\\nfísicos.",
    "ITEM_WISE_GLASSES": "Aumenta ligeramente\\nla potencia de ataques\\nespeciales.",
    "ITEM_METRONOME": "Potencia un movimiento\\nsi se utiliza de forma\\nconsecutiva.",
    "ITEM_LIGHT_CLAY": "Alarga la duración de\\nbarreras como Reflejo\\no Pantalla de Luz.",
    "ITEM_POWER_HERB": "Permite usar en un solo\\nturno ataques que\\nrequieren recarga previa.",
    "ITEM_WHITE_HERB": "Restaura bajadas de\\ncaracterísticas del\\nportador en combate.",
    "ITEM_MENTAL_HERB": "Cura efectos como la\\natracción, mofa o\\notras limitaciones.",
    "ITEM_FLAME_ORB": "Esfera que causa una\\nquemadura al portador\\ntras un turno.",
    "ITEM_TOXIC_ORB": "Esfera que envenena\\ngravemente al portador\\ntras un turno.",
    "ITEM_BLACK_SLUDGE": "Restaura PS a tipos\\nVeneno y daña a todos\\nlos demás.",
    "ITEM_AIR_BALLOON": "Hace flotar al portador\\nvolviéndolo inmune a\\nataques de Tierra.",
    "ITEM_RED_CARD": "Expulsa del combate\\nal rival que dañe\\nal portador.",
    "ITEM_EJECT_BUTTON": "Cambia de Pokémon al\\nrecibir un golpe del\\nrival.",
    "ITEM_SAFETY_GOGGLES": "Inmune al clima y\\na ataques de polvo o\\nesporas.",
    "ITEM_WEAKNESS_POLICY": "Sube mucho Ataque y\\nAt. Esp. al recibir un\\ngolpe súpereficaz.",
    "ITEM_TERRAIN_EXTENDER": "Alarga la duración del\\nterreno en combate\\na 8 turnos.",
    "ITEM_PROTECTIVE_PADS": "Protege de efectos de\\ncontacto al golpear al\\nrival.",
    "ITEM_THROAT_SPRAY": "Sube el At. Esp. tras\\nusar un ataque de\\nsonido.",
    "ITEM_BLUNDER_POLICY": "Sube mucho la Velocidad\\nsi un ataque propio\\nha fallado.",
    "ITEM_HEAVY_BALL": "Eficaz al capturar\\nPokémon de gran\\npeso corporal.",
    "ITEM_EXP_SHARE": "Reparte los Puntos\\nde Experiencia entre\\ntodo el equipo.",
    "ITEM_LUCKY_EGG": "Aumenta los Puntos\\nde Experiencia ganados\\nen combate.",
    "ITEM_AMULET_COIN": "Duplica el dinero que\\nse obtiene tras ganar\\nun combate.",
    "ITEM_CLEANSE_TAG": "Ayuda a repeler a los\\nPokémon salvajes si la\\nlleva el líder.",
    "ITEM_SMOKE_BALL": "Permite huir de un\\ncombate salvaje con\\néxito garantizado.",
    "ITEM_SOOTHE_BELL": "Campana que sosiega y\\nhace más amigable al\\nPokémon que la lleva.",

    # Objetos potenciadores de tipo
    "ITEM_SILK_SCARF": "Potencia los ataques\\nde tipo Normal.",
    "ITEM_CHARCOAL": "Potencia los ataques\\nde tipo Fuego.",
    "ITEM_MYSTIC_WATER": "Potencia los ataques\\nde tipo Agua.",
    "ITEM_MAGNET": "Potencia los ataques\\nde tipo Eléctrico.",
    "ITEM_MIRACLE_SEED": "Potencia los ataques\\nde tipo Planta.",
    "ITEM_NEVER_MELT_ICE": "Potencia los ataques\\nde tipo Hielo.",
    "ITEM_BLACK_BELT": "Potencia los ataques\\nde tipo Lucha.",
    "ITEM_POISON_BARB": "Potencia los ataques\\nde tipo Veneno.",
    "ITEM_SOFT_SAND": "Potencia los ataques\\nde tipo Tierra.",
    "ITEM_SHARP_BEAK": "Potencia los ataques\\nde tipo Volador.",
    "ITEM_TWISTED_SPOON": "Potencia los ataques\\nde tipo Psíquico.",
    "ITEM_SILVER_POWDER": "Potencia los ataques\\nde tipo Bicho.",
    "ITEM_HARD_STONE": "Potencia los ataques\\nde tipo Roca.",
    "ITEM_SPELL_TAG": "Potencia los ataques\\nde tipo Fantasma.",
    "ITEM_DRAGON_FANG": "Potencia los ataques\\nde tipo Dragón.",
    "ITEM_BLACK_GLASSES": "Potencia los ataques\\nde tipo Siniestro.",
    "ITEM_METAL_COAT": "Potencia los ataques\\nde tipo Acero.",

    # Bayas
    "ITEM_CHERI_BERRY": "Baya que cura la\\nparálisis si la lleva\\nequipada.",
    "ITEM_CHESTO_BERRY": "Baya que despierta del\\nsueño si la lleva\\nequipada.",
    "ITEM_PECHA_BERRY": "Baya que cura el\\nenvenenamiento si la\\nlleva equipada.",
    "ITEM_RAWST_BERRY": "Baya que cura las\\nquemaduras si la lleva\\nequipada.",
    "ITEM_ASPEAR_BERRY": "Baya que descongela\\nal Pokémon si la lleva\\nequipada.",
    "ITEM_LEPPA_BERRY": "Baya que restaura 10\\nPP al agotarse los\\nde un movimiento.",
    "ITEM_ORAN_BERRY": "Baya que restaura 10\\nPS al Pokémon si sufre\\ndaño en combate.",
    "ITEM_PERSIM_BERRY": "Baya que cura la\\nconfusión si la lleva\\nequipada.",
    "ITEM_LUM_BERRY": "Baya que cura cualquier\\nestado alterado si la\\nlleva equipada.",
    "ITEM_SITRUS_BERRY": "Baya que restaura un\\ncuarto de los PS si\\nbajan de la mitad.",
    "ITEM_LIECHI_BERRY": "Baya que sube el Ataque\\nsi los PS bajan de un\\ncuarto.",
    "ITEM_GANLON_BERRY": "Baya que sube la Defensa\\nsi los PS bajan de un\\ncuarto.",
    "ITEM_SALAC_BERRY": "Baya que sube Velocidad\\nsi los PS bajan de un\\ncuarto.",
    "ITEM_PETAYA_BERRY": "Baya que sube At. Esp.\\nsi los PS bajan de un\\ncuarto.",
    "ITEM_APICOT_BERRY": "Baya que sube Def. Esp.\\nsi los PS bajan de un\\ncuarto.",
    "ITEM_LANSAT_BERRY": "Baya que sube el índice\\nde golpes críticos en\\nun apuro.",
    "ITEM_STARF_BERRY": "Baya que sube mucho un\\nstat aleatorio en un\\napuro.",
}

# Add all TMs and HMs automatically
for i in range(1, 101):
    tm_id = f"ITEM_TM{i:02d}" if i < 10 else f"ITEM_TM{i}"
    ITEM_DESC_ES[tm_id] = f"Máquina Técnica que\\nenseña un movimiento\\na un Pokémon compatible."

for i in range(1, 9):
    hm_id = f"ITEM_HM{i:02d}" if i < 10 else f"ITEM_HM{i}"
    ITEM_DESC_ES[hm_id] = f"Máquina Oculta que\\nenseña un movimiento\\nútil fuera de combate."

# Shared static strings in items.h
SHARED_ITEM_DESC_ES = {
    "sFullHealDesc": "Cura todos los\\nproblemas de estado\\nde un Pokémon.",
    "sPokeDollDesc": "Úsalo para escapar de\\ncualquier combate con\\nun Pokémon salvaje.",
    "sMaxReviveDesc": "Revive a un Pokémon\\ndebilitado con todos\\nsus PS al máximo.",
    "sHealthFeatherDesc": "Pluma que aumenta\\nlevemente los PS\\nbase de un Pokémon.",
    "sMuscleFeatherDesc": "Pluma que aumenta\\nlevemente el Ataque\\nbase de un Pokémon.",
    "sResistFeatherDesc": "Pluma que aumenta\\nlevemente la Defensa\\nbase de un Pokémon.",
    "sGeniusFeatherDesc": "Pluma que aumenta\\nlevemente el At. Esp.\\nbase de un Pokémon.",
    "sCleverFeatherDesc": "Pluma que aumenta\\nlevemente la Def. Esp.\\nbase de un Pokémon.",
    "sSwiftFeatherDesc": "Pluma que aumenta\\nlevemente la Velocidad\\nbase de un Pokémon.",
    "sBigMushroomDesc": "Seta muy codiciada\\nque se puede vender a\\nun precio muy alto.",
    "sShardsDesc": "Fragmento antiguo de\\nun objeto. Se vende a\\nbajo precio.",
    "sRootFossilDesc": "Fósil de un Pokémon\\nantiguo que habitaba\\nen el fondo del mar.",
    "sEvolutionStoneDesc": "Piedra peculiar que\\nhace evolucionar a\\nciertos Pokémon.",
    "sNectarDesc": "Néctar floral que\\ncambia la forma de\\nciertos Pokémon.",
    "sCharizarditeDesc": "Mega Piedra que hace\\nmegaevolucionar a\\nCharizard en combate.",
    "sMewtwoniteDesc": "Mega Piedra que hace\\nmegaevolucionar a\\nMewtwo en combate.",
    "sRaichuniteDesc": "Mega Piedra que hace\\nmegaevolucionar a\\nRaichu en combate.",
    "sAbsoliteDesc": "Mega Piedra que hace\\nmegaevolucionar a\\nAbsol en combate.",
    "sGarchompiteDesc": "Mega Piedra que hace\\nmegaevolucionar a\\nGarchomp en combate.",
    "sLucarioniteDesc": "Mega Piedra que hace\\nmegaevolucionar a\\nLucario en combate.",
    "sSeaIncenseDesc": "Incienso que potencia\\nlos movimientos de\\ntipo Agua.",
    "sOddIncenseDesc": "Incienso que potencia\\nlos movimientos de\\ntipo Psíquico.",
    "sRockIncenseDesc": "Incienso que potencia\\nlos movimientos de\\ntipo Roca.",
    "sFullIncenseDesc": "Incienso exótico que\\nhace que el portador\\nse mueva más lento.",
    "sRoseIncenseDesc": "Incienso que potencia\\nlos movimientos de\\ntipo Planta.",
    "sLuckIncenseDesc": "Duplica las ganancias\\ntras el combate si el\\nportador participa.",
    "sPureIncenseDesc": "Incienso que ayuda a\\nrepeler a Pokémon\\nsalvajes.",
    "sKingsRockDesc": "Roca que puede hacer\\nretroceder al rival\\nal ser golpeado.",
    "sFigyBerryDesc": "Baya que restaura PS\\npero puede confundir\\nsi no le gusta el sabor.",
    "sTeraShardDesc": "Fragmento que se forma\\ncuando un Pokémon Tera\\ncae debilitado.",
    "sGenericMulchDesc": "Abono fertilizante que\\nno es adecuado para\\nel suelo local."
}

with open('/mnt/y/heartandsoul_esp/pokehns-expansion/items_es.json', 'w', encoding='utf-8') as f:
    json.dump(ITEM_DESC_ES, f, ensure_ascii=False, indent=2)

with open('/mnt/y/heartandsoul_esp/pokehns-expansion/shared_items_es.json', 'w', encoding='utf-8') as f:
    json.dump(SHARED_ITEM_DESC_ES, f, ensure_ascii=False, indent=2)

print(f"Mapped {len(ITEM_DESC_ES)} items by ID.")
print(f"Mapped {len(SHARED_ITEM_DESC_ES)} shared item static symbols.")
