# Translations for remaining 232 moves
REMAINING_MOVES_ES = {
    # Gen 1/4 moves misaligned
    "MOVE_SONIC_BOOM": "Ondas de choque que causan\\nsiempre 20 PS de daño.",
    "MOVE_HEAL_BLOCK": "Impide al rival recuperar\\nPS durante 5 turnos.",
    "MOVE_POWER_TRICK": "El usuario intercambia su\\nAtaque y su Defensa.",
    "MOVE_GASTRO_ACID": "Ácido que anula la\\nhabilidad del rival.",
    "MOVE_LUCKY_CHANT": "Canto que previene que el\\nrival aseste críticos.",
    "MOVE_ME_FIRST": "Ejecuta el ataque del rival\\ncon mayor potencia.",
    "MOVE_COPYCAT": "Imita el último movimiento\\nusado por cualquiera.",
    "MOVE_POWER_SWAP": "Intercambia mejoras de\\nAtaque y At. Esp. rival.",
    "MOVE_GUARD_SWAP": "Intercambia mejoras de\\nDefensa y Def. Esp. rival.",
    "MOVE_PUNISHMENT": "Más daño cuantas más mejoras\\nde estadísticas tenga el rival.",
    "MOVE_LAST_RESORT": "Solo puede usarse tras haber\\nusado los demás ataques.",
    "MOVE_WORRY_SEED": "Siembra una semilla que cambia\\nla habilidad a Insomnio.",
    "MOVE_TOXIC_SPIKES": "Lanza púas que envenenan al\\nrival al entrar al campo.",
    "MOVE_HEART_SWAP": "Intercambia todos los cambios\\nde stats con el rival.",
    "MOVE_AQUA_RING": "Crea un velo de agua que cura\\nPS al final de cada turno.",
    "MOVE_MAGNET_RISE": "El usuario levita gracias al\\nelectromagnetismo.",
    "MOVE_FLARE_BLITZ": "Carga ígnea que puede quemar\\npero daña al usuario.",
    "MOVE_FORCE_PALM": "Onda de choque que puede\\nparalizar al rival.",
    "MOVE_AURA_SPHERE": "Lanza una ráfaga de aura que\\nnunca puede fallar.",
    "MOVE_ROCK_POLISH": "Pule el cuerpo para subir\\nmucho la Velocidad.",
    "MOVE_POISON_JAB": "Pinchazo venenoso que puede\\nenvenenar al objetivo.",
    "MOVE_DARK_PULSE": "Aura oscura que puede hacer\\nretroceder al rival.",
    "MOVE_NIGHT_SLASH": "Cuchillada veloz con alta\\ntasa de golpes críticos.",
    "MOVE_AQUA_TAIL": "Golpea con la cola como si\\nfuera una gran ola.",
    "MOVE_SEED_BOMB": "Dispara una ráfaga de duras\\nsemillas al objetivo.",
    "MOVE_AIR_SLASH": "Cuchilla de viento que puede\\nhacer retroceder al rival.",
    "MOVE_X_SCISSOR": "Tijera cruzada con garras\\no guadañas al rival.",
    "MOVE_BUG_BUZZ": "Onda sonora vibrante que puede\\nbajar la Def. Especial.",
    "MOVE_DRAGON_PULSE": "Genera una onda de choque de\\ndragón que daña al rival.",
    "MOVE_DRAGON_RUSH": "Embestida brutal de dragón\\nque puede amedrentar.",
    "MOVE_POWER_GEM": "Rayo de gemas brillantes que\\nresplandecen como joyas.",
    "MOVE_VACUUM_WAVE": "Gira los puños creando una\\nonda que ataca primero.",
    "MOVE_FOCUS_BLAST": "Ataque a tope de poder que\\npuede bajar Def. Esp.",
    "MOVE_ENERGY_BALL": "Concentra energía natural;\\npuede bajar Def. Especial.",
    "MOVE_BRAVE_BIRD": "Carga a baja altura que causa\\ndaño de retroceso.",
    "MOVE_EARTH_POWER": "Erupción de tierra que puede\\nreducir la Def. Especial.",
    "MOVE_SWITCHEROO": "Intercambia objetos con el\\nrival rápidamente.",
    "MOVE_NASTY_PLOT": "Maquila planes malvados para\\nsubir mucho el At. Esp.",
    "MOVE_BULLET_PUNCH": "Puñetazo veloz como una bala\\nque ataca con prioridad.",
    "MOVE_ICE_SHARD": "Lanza fragmentos de hielo que\\nsiempre golpean primero.",
    "MOVE_SHADOW_CLAW": "Zarpazo de sombras con alta\\nprobabilidad de crítico.",
    "MOVE_THUNDER_FANG": "Mordisco eléctrico que puede\\nparalizar o amedrentar.",
    "MOVE_ICE_FANG": "Mordisco gélido que puede\\nhelar o amedrentar.",
    "MOVE_FIRE_FANG": "Mordisco ígneo que puede\\nquemar o amedrentar.",
    "MOVE_SHADOW_SNEAK": "Extiende su sombra para\\ngolpear siempre primero.",
    "MOVE_MUD_BOMB": "Dispara una bola de lodo que\\npuede reducir la Precisión.",
    "MOVE_PSYCHO_CUT": "Cuchillas psíquicas con alta\\nprobabilidad de crítico.",
    "MOVE_ZEN_HEADBUTT": "Fuerte cabezazo psíquico que\\npuede amedrentar al rival.",
    "MOVE_MIRROR_SHOT": "Destello de luz espejo que\\npuede bajar la Precisión.",
    "MOVE_FLASH_CANNON": "Haz de luz concentrada que\\npuede bajar Def. Especial.",
    "MOVE_ROCK_CLIMB": "Carga de escalada que puede\\ndejar confuso al rival.",
    "MOVE_DEFOG": "Disipa neblina y pantallas;\\nreduce la Evasión rival.",
    "MOVE_TRICK_ROOM": "Los Pokémon más lentos se\\nmueven antes durante 5 turnos.",
    "MOVE_DRACO_METEOR": "Invoca cometas; reduce mucho\\nel Ataque Especial propio.",
    "MOVE_DISCHARGE": "Descarga eléctrica que puede\\nparalizar a los demás.",
    "MOVE_LEAF_STORM": "Tormenta de hojas; reduce mucho\\nel Ataque Especial propio.",
    "MOVE_POWER_WHIP": "Violento latigazo de zarcillos\\nque castiga al rival.",
    "MOVE_CROSS_POISON": "Corte en cruz que puede envenenar\\ny tiene alto ratio crítico.",
    "MOVE_GUNK_SHOT": "Lanza basura pestilente que\\npuede envenenar al rival.",
    "MOVE_IRON_HEAD": "Cabezazo de acero duro que\\npuede amedrentar al rival.",
    "MOVE_MAGNET_BOMB": "Lanza un proyectil magnético\\nque nunca puede fallar.",
    "MOVE_STONE_EDGE": "Apuñala con piedras afiladas;\\nalta probabilidad de crítico.",
    "MOVE_CAPTIVATE": "Seduce al género opuesto para\\nbajar mucho su At. Esp.",
    "MOVE_STEALTH_ROCK": "Lanza rocas flotantes que dañan\\nal rival al entrar.",
    "MOVE_GRASS_KNOT": "Lazo de hierba; hace más daño\\ncuanto más pesado sea el rival.",
    "MOVE_CHATTER": "Onda sonora estridente que\\nprovoca confusión segura.",
    "MOVE_JUDGMENT": "Ataque cuyo tipo elemental varía\\nsegún la tabla equipada.",
    "MOVE_CHARGE_BEAM": "Rayo eléctrico que a menudo\\naumenta el Ataque Especial.",
    "MOVE_WOOD_HAMMER": "Golpe demoledor de madera; causa\\ndaño de retroceso.",
    "MOVE_AQUA_JET": "Embestida acuática que ataca\\nsiempre en primer lugar.",
    "MOVE_ATTACK_ORDER": "Ordena a los súbditos golpear;\\nalto ratio de críticos.",
    "MOVE_DEFEND_ORDER": "Crea un escudo de súbditos que\\nsube Defensa y Def. Esp.",
    "MOVE_HEAL_ORDER": "Los súbditos acuden a sanar\\nla mitad de los PS máximos.",
    "MOVE_HEAD_SMASH": "Cabezazo a vida o muerte con\\ngran daño de retroceso.",
    "MOVE_DOUBLE_HIT": "Golpea dos veces consecutivas\\ncon la cola o extremidades.",
    "MOVE_ROAR_OF_TIME": "Ataque colosal; el usuario debe\\nrecargar el siguiente turno.",
    "MOVE_SPACIAL_REND": "Desgarra al rival y el espacio;\\nalto ratio de críticos.",
    "MOVE_MAGMA_STORM": "Vórtice de magma ardiente que\\natrapa al rival varios turnos.",
    "MOVE_DARK_VOID": "Suma a los rivales en profunda\\noscuridad para dormirlos.",
    "MOVE_SEED_FLARE": "Onda de choque celestial que\\nbaja mucho la Def. Esp.",
    "MOVE_OMINOUS_WIND": "Viento siniestro que puede\\nsubir todas las estadísticas.",

    # Let's Go Pikachu / Eevee Partner Moves
    "MOVE_ZIPPY_ZAP": "Ráfaga eléctrica con prioridad\\nque siempre asesta crítico.",
    "MOVE_SPLISHY_SPLASH": "Gran ola electrificada que\\npuede causar parálisis.",
    "MOVE_FLOATY_FALL": "Se eleva y cae en picado;\\npuede amedrentar al rival.",
    "MOVE_PIKA_PAPOW": "Poder del cariño de Pikachu;\\nnunca falla.",
    "MOVE_BOUNCY_BUBBLE": "Burbuja elástica que absorbe\\ntodo el daño infligido.",
    "MOVE_BUZZY_BUZZ": "Chispa eléctrica certera que\\nsiempre causa parálisis.",
    "MOVE_SIZZLY_SLIDE": "Carga envuelta en llamas que\\nsiempre causa quemaduras.",
    "MOVE_GLITZY_GLOW": "Onda que crea una pantalla que\\nmitiga el daño especial.",
    "MOVE_BADDY_BAD": "Ataque que crea una pantalla que\\nmitiga el daño físico.",
    "MOVE_SAPPY_SEED": "Esparce semillas gigantes que\\ndrenan PS cada turno.",
    "MOVE_FREEZY_FROST": "Ráfaga helada que elimina los\\ncambios en estadísticas.",
    "MOVE_SPARKLY_SWIRL": "Vórtice perfumado que cura los\\nestados de todo el equipo.",
    "MOVE_VEEVEE_VOLLEY": "Poder del cariño de Eevee;\\nnunca puede fallar.",
    "MOVE_DOUBLE_IRON_BASH": "Gira y golpea dos veces con los\\nbrazos; puede amedrentar.",

    # Legends Arceus / SV Hisuian Moves
    "MOVE_DIRE_CLAW": "Garra letal que puede causar\\nparálisis, veneno o somnolencia.",
    "MOVE_PSYSHIELD_BASH": "Carga de energía psíquica que\\naumenta la propia Defensa.",
    "MOVE_POWER_SHIFT": "El usuario intercambia sus\\nvalores de Ataque y Defensa.",
    "MOVE_STONE_AXE": "Hachazo de piedra que coloca\\nTrampa Rocas en el campo.",
    "MOVE_SPRINGTIDE_STORM": "Viento feroz primaveral; efecto\\nsegún la forma del usuario.",
    "MOVE_MYSTICAL_POWER": "Poder misterioso que aumenta el\\nAtaque Especial del usuario.",
    "MOVE_RAGING_FURY": "Furia de dos o tres turnos que\\ndeja confuso al usuario.",
    "MOVE_WAVE_CRASH": "Embestida acuática que causa\\ndaño de retroceso al usuario.",
    "MOVE_CHLOROBLAST": "Explosión de clorofila potente\\nque hiere mucho al usuario.",
    "MOVE_MOUNTAIN_GALE": "Bloques gigantes de hielo que\\npueden amedrentar al rival.",
    "MOVE_VICTORY_DANCE": "Danza triunfal que aumenta el\\nAtaque, Defensa y Velocidad.",
    "MOVE_HEADLONG_RUSH": "Placaje a fondo que reduce las\\ndefensas del propio usuario.",
    "MOVE_BARB_BARRAGE": "Dispara púas; duplica su poder\\nsi el rival está envenenado.",
    "MOVE_ESPER_WING": "Ala psíquica con alto crítico\\nque sube la Velocidad.",
    "MOVE_BITTER_MALICE": "Rencor gélido que reduce el\\nAtaque del objetivo.",
    "MOVE_SHELTER": "Se encierra en su caparazón para\\nsubir mucho su Defensa.",
    "MOVE_TRIPLE_ARROWS": "Tres flechas con alto crítico\\nque pueden bajar la Defensa.",
    "MOVE_INFERNAL_PARADE": "Doble poder si el rival tiene\\nestado; puede causar quemadura.",
    "MOVE_CEASELESS_EDGE": "Tajo siniestro que coloca púas\\ntóxicas en el campo rival.",
    "MOVE_BLEAKWIND_STORM": "Viento helado polar que puede\\nreducir la Velocidad rival.",
    "MOVE_WILDBOLT_STORM": "Tempestad eléctrica que puede\\nparalizar al objetivo.",
    "MOVE_SANDSEAR_STORM": "Arena abrasadora que puede\\nquemar al objetivo.",
    "MOVE_LUNAR_BLESSING": "Bendición lunar que cura PS y\\nestados del usuario y aliado.",
    "MOVE_TAKE_HEART": "Se llena de valor para curarse\\ny subir sus características.",

    # Scarlet & Violet New Moves
    "MOVE_TERA_BLAST": "Ataque que adopta el teratipo\\ndel usuario si teracristaliza.",
    "MOVE_SILK_TRAP": "Se protege y baja la Velocidad\\nde quien haga contacto.",
    "MOVE_AXE_KICK": "Patada hacha que puede fallar\\ny confundir al objetivo.",
    "MOVE_LAST_RESPECTS": "Gana potencia por cada aliado\\nderrotado en el equipo.",
    "MOVE_LUMINA_CRASH": "Luz cegadora que siempre baja\\nmucho la Def. Especial rival.",
    "MOVE_ORDER_UP": "Golpea y sube un stat según el\\nTatsugiri en la boca de Dondozo.",
    "MOVE_JET_PUNCH": "Puñetazo a velocidad vertiginosa\\nque ataca con prioridad.",
    "MOVE_SPICY_EXTRACT": "Aumenta mucho el Ataque pero\\nbaja mucho la Defensa rival.",
    "MOVE_SPIN_OUT": "Esfuerzo extremo en las ruedas\\nque baja mucho la Velocidad.",
    "MOVE_POPULATION_BOMB": "Familia que ataca de 1 a 10\\nveces seguidas en un turno.",
    "MOVE_ICE_SPINNER": "Giro con patas de hielo que daña\\ny elimina el terreno activo.",
    "MOVE_GLAIVE_RUSH": "Ataque temerario; el rival no\\nfallará y duplicará daño luego.",
    "MOVE_REVIVAL_BLESSING": "Revive a un compañero debilitado\\ncon la mitad de sus PS.",
    "MOVE_SALT_CURE": "Daña cada turno; duplica el daño\\ncontra Acero y Agua.",
    "MOVE_TRIPLE_DIVE": "Tres golpes de agua sucesivos\\nen un mismo turno.",
    "MOVE_MORTAL_SPIN": "Elimina trampas y Drenadoras;\\nenvenena a los rivales.",
    "MOVE_DOODLE": "Cambia la habilidad propia y de\\naliado por la del rival.",
    "MOVE_FILLET_AWAY": "Pierde PS para aumentar mucho\\nsus ataques y la Velocidad.",
    "MOVE_KOWTOW_CLEAVE": "Corte ceremonial certero que\\nnunca puede fallar.",
    "MOVE_FLOWER_TRICK": "Ramillete trucado que nunca falla\\ny siempre es golpe crítico.",
    "MOVE_TORCH_SONG": "Canto ardiente que siempre sube\\nel Ataque Especial propio.",
    "MOVE_AQUA_STEP": "Paso de baile acuático que sube\\nla Velocidad propia.",
    "MOVE_RAGING_BULL": "Placaje de toro que rompe barreras;\\ntipo según la forma de Tauros.",
    "MOVE_MAKE_IT_RAIN": "Lluvia de monedas; baja At. Esp.\\ny deja dinero tras la batalla.",
    "MOVE_RUINATION": "Poder de ruina que reduce a la\\nmitad los PS del rival.",
    "MOVE_COLLISION_COURSE": "Explosión prehistórica; más fuerte\\nsi es supereficaz.",
    "MOVE_ELECTRO_DRIFT": "Relámpago futurista; más fuerte\\nsi es supereficaz.",
    "MOVE_SHED_TAIL": "Crea un Sustituto antes de cambiar\\nde Pokémon en combate.",
    "MOVE_PSYBLADE": "Espada psíquica más potente en\\nCampo Eléctrico.",
    "MOVE_HYDRO_STEAM": "Vapor hirviente que duplica su\\npoder bajo sol abrasador.",

    # Z-Moves
    "MOVE_BREAKNECK_BLITZ": "Ataque Z de tipo Normal.\\nLa potencia varía.",
    "MOVE_ALL_OUT_PUMMELING": "Ataque Z de tipo Lucha.\\nLa potencia varía.",
    "MOVE_SUPERSONIC_SKYSTRIKE": "Ataque Z de tipo Volador.\\nLa potencia varía.",
    "MOVE_ACID_DOWNPOUR": "Ataque Z de tipo Veneno.\\nLa potencia varía.",
    "MOVE_TECTONIC_RAGE": "Ataque Z de tipo Tierra.\\nLa potencia varía.",
    "MOVE_CONTINENTAL_CRUSH": "Ataque Z de tipo Roca.\\nLa potencia varía.",
    "MOVE_SAVAGE_SPIN_OUT": "Ataque Z de tipo Bicho.\\nLa potencia varía.",
    "MOVE_NEVER_ENDING_NIGHTMARE": "Ataque Z de tipo Fantasma.\\nLa potencia varía.",
    "MOVE_CORKSCREW_CRASH": "Ataque Z de tipo Acero.\\nLa potencia varía.",
    "MOVE_INFERNO_OVERDRIVE": "Ataque Z de tipo Fuego.\\nLa potencia varía.",
    "MOVE_HYDRO_VORTEX": "Ataque Z de tipo Agua.\\nLa potencia varía.",
    "MOVE_BLOOM_DOOM": "Ataque Z de tipo Planta.\\nLa potencia varía.",
    "MOVE_GIGAVOLT_HAVOC": "Ataque Z de tipo Eléctrico.\\nLa potencia varía.",
    "MOVE_SHATTERED_PSYCHE": "Ataque Z de tipo Psíquico.\\nLa potencia varía.",
    "MOVE_SUBZERO_SLAMMER": "Ataque Z de tipo Hielo.\\nLa potencia varía.",
    "MOVE_DEVASTATING_DRAKE": "Ataque Z de tipo Dragón.\\nLa potencia varía.",
    "MOVE_BLACK_HOLE_ECLIPSE": "Ataque Z de tipo Siniestro.\\nLa potencia varía.",
    "MOVE_TWINKLE_TACKLE": "Ataque Z de tipo Hada.\\nLa potencia varía.",
    "MOVE_CATASTROPIKA": "Ataque Z exclusivo de Pikachu\\ncon electricidad máxima.",
    "MOVE_10000000_VOLT_THUNDERBOLT": "Ataque Z de Pikachu con gorra;\\nalto ratio de críticos.",
    "MOVE_STOKED_SPARKSURFER": "Ataque Z de Raichu de Alola;\\nparaliza al rival.",
    "MOVE_EXTREME_EVOBOOST": "Ataque Z de Eevee; sube todas\\nlas características.",
    "MOVE_PULVERIZING_PANCAKE": "Ataque Z de Snorlax lanzado a\\nplena potencia.",
    "MOVE_GENESIS_SUPERNOVA": "Ataque Z de Mew que activa el\\nCampo Psíquico.",
    "MOVE_SINISTER_ARROW_RAID": "Ataque Z de Decidueye; dispara\\ninfinidad de flechas.",
    "MOVE_MALICIOUS_MOONSAULT": "Ataque Z de Incineroar con un\\nsalto devastador.",
    "MOVE_OCEANIC_OPERETTA": "Ataque Z de Primarina con una\\ngigantesca masa de agua.",
    "MOVE_SPLINTERED_STORMSHARDS": "Ataque Z de Lycanroc que elimina\\ntodos los terrenos.",
    "MOVE_LETS_SNUGGLE_FOREVER": "Ataque Z de Mimikyu que propina\\nuna paliza con cariño.",
    "MOVE_GUARDIAN_OF_ALOLA": "Ataque Z del Guardián que reduce\\n3/4 de los PS del rival.",
    "MOVE_SEARING_SUNRAZE_SMASH": "Ataque Z de Solgaleo que ignora\\nhabilidades defensivas.",
    "MOVE_MENACING_MOONRAZE_MAELSTROM": "Ataque Z de Lunala que ignora\\nhabilidades defensivas.",
    "MOVE_LIGHT_THAT_BURNS_THE_SKY": "Ataque Z de Necrozma que usa su\\nmejor estadística.",
    "MOVE_SOUL_STEALING_7_STAR_STRIKE": "Ataque Z de Marshadow con golpes\\nfulminantes.",

    # Max Moves
    "MOVE_MAX_FLARE": "Ataque Dinamax de Fuego.\\nPone el clima soleado.",
    "MOVE_MAX_FLUTTERBY": "Ataque Dinamax de Bicho.\\nBaja el At. Esp. del rival.",
    "MOVE_MAX_LIGHTNING": "Ataque Dinamax Eléctrico.\\nActiva el Campo Eléctrico.",
    "MOVE_MAX_STRIKE": "Ataque Dinamax Normal.\\nBaja la Velocidad rival.",
    "MOVE_MAX_KNUCKLE": "Ataque Dinamax de Lucha.\\nSube el Ataque del equipo.",
    "MOVE_MAX_PHANTASM": "Ataque Dinamax Fantasma.\\nBaja la Defensa del rival.",
    "MOVE_MAX_HAILSTORM": "Ataque Dinamax de Hielo.\\nInvoca granizo o nieve.",
    "MOVE_MAX_OOZE": "Ataque Dinamax de Veneno.\\nSube el At. Esp. del equipo.",
    "MOVE_MAX_GEYSER": "Ataque Dinamax de Agua.\\nInvoca lluvia en combate.",
    "MOVE_MAX_AIRSTREAM": "Ataque Dinamax Volador.\\nSube la Velocidad del equipo.",
    "MOVE_MAX_STARFALL": "Ataque Dinamax de Hada.\\nActiva el Campo de Niebla.",
    "MOVE_MAX_WYRMWIND": "Ataque Dinamax de Dragón.\\nBaja el Ataque del rival.",
    "MOVE_MAX_MINDSTORM": "Ataque Dinamax Psíquico.\\nActiva el Campo Psíquico.",
    "MOVE_MAX_ROCKFALL": "Ataque Dinamax de Roca.\\nInvoca tormenta de arena.",
    "MOVE_MAX_QUAKE": "Ataque Dinamax de Tierra.\\nSube Def. Esp. del equipo.",
    "MOVE_MAX_DARKNESS": "Ataque Dinamax Siniestro.\\nBaja la Def. Esp. rival.",
    "MOVE_MAX_OVERGROWTH": "Ataque Dinamax de Planta.\\nActiva el Campo de Hierba.",
    "MOVE_MAX_STEELSPIKE": "Ataque Dinamax de Acero.\\nSube la Defensa del equipo.",

    # G-Max Moves
    "MOVE_G_MAX_VINE_LASH": "Ataque Gigamax de Venusaur.\\nDaña durante 4 turnos.",
    "MOVE_G_MAX_WILDFIRE": "Ataque Gigamax de Charizard.\\nDaña durante 4 turnos.",
    "MOVE_G_MAX_CANNONADE": "Ataque Gigamax de Blastoise.\\nDaña durante 4 turnos.",
    "MOVE_G_MAX_BEFUDDLE": "Ataque Gigamax de Butterfree.\\nEnvenena, paraliza o duerme.",
    "MOVE_G_MAX_VOLT_CRASH": "Ataque Gigamax de Pikachu.\\nParaliza a los rivales.",
    "MOVE_G_MAX_GOLD_RUSH": "Ataque Gigamax de Meowth.\\nConfunde y da dinero.",
    "MOVE_G_MAX_CHI_STRIKE": "Ataque Gigamax de Machamp.\\nAumenta la probabilidad crítica.",
    "MOVE_G_MAX_TERROR": "Ataque Gigamax de Gengar.\\nImpide escapar a los rivales.",
    "MOVE_G_MAX_FOAM_BURST": "Ataque Gigamax de Kingler.\\nBaja mucho la Velocidad rival.",
    "MOVE_G_MAX_RESONANCE": "Ataque Gigamax de Lapras.\\nReduce daño durante 5 turnos.",
    "MOVE_G_MAX_CUDDLE": "Ataque Gigamax de Eevee.\\nEnamora a los oponentes.",
    "MOVE_G_MAX_REPLENISH": "Ataque Gigamax de Snorlax.\\nRestaura las bayas comidas.",
    "MOVE_G_MAX_MALODOR": "Ataque Gigamax de Garbodor.\\nEnvenena a los rivales.",
    "MOVE_G_MAX_MELTDOWN": "Ataque Gigamax de Melmetal.\\nImpide repetir movimientos.",
    "MOVE_G_MAX_DRUM_SOLO": "Ataque Gigamax de Rillaboom.\\nIgnora habilidades rivales.",
    "MOVE_G_MAX_FIREBALL": "Ataque Gigamax de Cinderace.\\nIgnora habilidades rivales.",
    "MOVE_G_MAX_HYDROSNIPE": "Ataque Gigamax de Inteleon.\\nIgnora habilidades rivales.",
    "MOVE_G_MAX_WIND_RAGE": "Ataque Gigamax de Corviknight.\\nElimina pantallas del rival.",
    "MOVE_G_MAX_GRAVITAS": "Ataque Gigamax de Orbeetle.\\nCambia la gravedad 5 turnos.",
    "MOVE_G_MAX_STONESURGE": "Ataque Gigamax de Drednaw.\\nLanza rocas puntiagudas.",
    "MOVE_G_MAX_VOLCALITH": "Ataque Gigamax de Coalossal.\\nDaña durante 4 turnos.",
    "MOVE_G_MAX_TARTNESS": "Ataque Gigamax de Flapple.\\nReduce la Evasión rival.",
    "MOVE_G_MAX_SWEETNESS": "Ataque Gigamax de Appletun.\\nCura problemas de estado.",
    "MOVE_G_MAX_SANDBLAST": "Ataque Gigamax de Sandaconda.\\nAtrapa en tormenta de arena.",
    "MOVE_G_MAX_STUN_SHOCK": "Ataque Gigamax de Toxtricity.\\nEnvenena o paraliza rivales.",
    "MOVE_G_MAX_CENTIFERNO": "Ataque Gigamax de Centiskorch.\\nAtrapa en llamas al rival.",
    "MOVE_G_MAX_SMITE": "Ataque Gigamax de Hatterene.\\nConfunde a los rivales.",
    "MOVE_G_MAX_SNOOZE": "Ataque Gigamax de Grimmsnarl.\\nDuerme a los oponentes.",
    "MOVE_G_MAX_FINALE": "Ataque Gigamax de Alcremie.\\nRestaura PS a los aliados.",
    "MOVE_G_MAX_STEELSURGE": "Ataque Gigamax de Copperajah.\\nEsparce púas de acero.",
    "MOVE_G_MAX_DEPLETION": "Ataque Gigamax de Duraludon.\\nReduce PP del objetivo.",
}
