param(
    [string]$Version = ""
)

# Archivos base de sistema y anteriores
$files = @(
    'data/maps/LittlerootTown_BrendansHouse_1F/scripts.inc',
    'data/scripts/players_house.inc',
    'data/text/save.inc',
    'src/battle_message.c',
    'src/battle_controller_player.c',
    'src/strings.c',
    'src/data/items.h',
    'data/event_scripts.s',
    'data/scripts/pkmn_center_nurse.inc',
    'data/specials.inc',
    'src/item_menu.c',
    'data/maps/AzaleaTown_Gym_hns/scripts.inc',
    'data/maps/AzaleaTown_KurtsHouse_hns/scripts.inc',
    'data/maps/AzaleaTown_hns/scripts.inc',
    'data/maps/CherrygroveCity_House1_hns/scripts.inc',
    'data/maps/CherrygroveCity_House2_hns/scripts.inc',
    'data/maps/CherrygroveCity_House3_hns/scripts.inc',
    'data/maps/CherrygroveCity_Mart_hns/scripts.inc',
    'data/maps/CherrygroveCity_PokemonCenter_hns/scripts.inc',
    'data/maps/CherrygroveCity_PokemonCenter_hns/map.json',
    'data/maps/CherrygroveCity_PokemonCenter_hns/events.inc',
    'include/config/battle.h',
    'include/constants/form_change_types.h',
    'include/config/species_enabled.h',
    'include/config/pokemon.h',
    'src/data/pokemon/species_info/gen_1_families.h',
    'src/data/pokemon/species_info/gen_2_families.h',
    'src/data/pokemon/species_info/gen_3_families.h',
    'src/data/pokemon/species_info/gen_4_families.h',
    'src/data/pokemon/species_info/gen_5_families.h',
    'src/data/pokemon/species_info/gen_6_families.h',
    'src/data/pokemon/species_info/gen_7_families.h',
    'src/data/pokemon/species_info/gen_8_families.h',
    'src/data/pokemon/species_info/gen_9_families.h',
    'include/constants/flags_hns.h',
    'data/maps/CherrygroveCity_hns/scripts.inc',
    'data/maps/DarkCave_NorthSide_hns/scripts.inc',
    'data/maps/Gate_Route29_Route46_hns/scripts.inc',
    'data/maps/Gate_Route31_VioletCity_hns/scripts.inc',
    'data/maps/Gate_RuinsOfAlph_Route32_hns/scripts.inc',
    'data/maps/Gate_RuinsOfAlph_Route36_hns/scripts.inc',
    'data/maps/Gate_AzaleaTown_IlexForest_hns/scripts.inc',
    'data/maps/Gate_IlexForest_Route34_hns/scripts.inc',
    'data/maps/NewBarkTown_House1_hns/scripts.inc',
    'data/maps/NewBarkTown_Lab_hns/scripts.inc',
    'data/maps/NewBarkTown_PlayersHouse_1F_hns/scripts.inc',
    'data/maps/NewBarkTown_hns/scripts.inc',
    'data/maps/Route29_hns/scripts.inc',
    'data/maps/Route30_House_hns/scripts.inc',
    'data/maps/Route30_MrPokemonsHouse_hns/scripts.inc',
    'data/maps/Route30_hns/scripts.inc',
    'data/maps/Route31_hns/scripts.inc',
    'data/maps/Route32_hns/scripts.inc',
    'data/maps/Route46_hns/scripts.inc',
    'data/maps/RuinsOfAlph_Lab_hns/scripts.inc',
    'data/maps/RuinsOfAlph_Outside_hns/scripts.inc',
    'data/maps/SlowpokeWell_B1F_hns/scripts.inc',
    'data/maps/SproutTower_3F_hns/scripts.inc',
    'data/maps/VioletCity_Gym_hns/scripts.inc',
    'data/maps/VioletCity_House1_hns/scripts.inc',
    'data/maps/VioletCity_PokemonCenter_hns/scripts.inc',
    'data/maps/VioletCity_TrainerSchool_hns/scripts.inc',
    'data/maps/VioletCity_hns/scripts.inc',
    # Bloque 3
    'data/maps/IlexForest_hns/scripts.inc',
    'data/maps/Route34_hns/scripts.inc',
    'data/maps/Route34_DayCare_hns/scripts.inc',
    'data/maps/GoldenrodCity_hns/scripts.inc',
    'data/maps/GoldenrodCity_Gym_hns/scripts.inc',
    'data/maps/GoldenrodCity_BikeShop_hns/scripts.inc',
    'data/maps/GoldenrodCity_FlowerShop_hns/scripts.inc',
    'data/maps/GoldenrodCity_BillsHouse_hns/scripts.inc',
    'data/maps/GoldenrodCity_House1_hns/scripts.inc',
    'data/maps/GoldenrodCity_House2_hns/scripts.inc',
    'data/maps/GoldenrodCity_House3_hns/scripts.inc',
    'data/maps/GoldenrodCity_PokemonCenter_hns/scripts.inc',
    'data/maps/GoldenrodCity_TrainStation_hns/scripts.inc',
    'data/maps/Gate_GoldenrodCity_Route35_hns/scripts.inc',
    'data/maps/GoldenrodCity_RadioTower_1F_hns/scripts.inc',
    'data/maps/GoldenrodCity_UndergroundSwitches_hns/scripts.inc',
    'data/maps/GoldenrodCity_UndergroundTunnel_hns/scripts.inc',
    'data/maps/GoldenrodCity_DepartmentStore_1F_hns/scripts.inc',
    'data/maps/Route35_hns/scripts.inc',
    'data/maps/Route36_hns/scripts.inc',
    'data/maps/Route37_hns/scripts.inc',
    'data/maps/NationalPark_Normal_hns/scripts.inc',
    'data/maps/NationalPark_BugContest_hns/scripts.inc',
    'data/maps/Gate_NationalPark_hns/scripts.inc',
    'data/maps/EcruteakCity_Gym_hns/scripts.inc',
    'data/maps/BurnedTower_1F_hns/scripts.inc',
    'data/maps/BurnedTower_B1F_hns/scripts.inc',
    'data/maps/EcruteakCity_Theater_hns/scripts.inc',
    'data/maps/EcruteakCity_PokemonCenter_hns/scripts.inc',
    'data/maps/EcruteakCity_hns/scripts.inc',
    'data/maps/EcruteakCity_House1_hns/scripts.inc',
    'data/maps/EcruteakCity_House2_hns/scripts.inc',
    'data/maps/EcruteakCity_Mart_hns/scripts.inc',
    'data/maps/EcruteakCity_SageOffice1_hns/scripts.inc',
    'data/maps/Gate_EcruteakCity_Route38_hns/scripts.inc',
    'data/maps/Gate_EcruteakCity_Route42_hns/scripts.inc',
    'data/maps/Route38_hns/scripts.inc',
    'data/maps/Route39_hns/scripts.inc',
    'data/maps/Route39_Barn_hns/scripts.inc',
    'data/maps/Route39_FarmHouse_hns/scripts.inc',
    'data/maps/OlivineCity_hns/scripts.inc',
    'data/maps/OlivineCity_PokemonCenter_hns/scripts.inc',
    'data/maps/OlivineCity_Mart_hns/scripts.inc',
    'data/maps/OlivineCity_Gym_hns/scripts.inc',
    'data/maps/OlivineCity_Cafe_hns/scripts.inc',
    'data/maps/OlivineCity_Lighthouse_hns/scripts.inc',
    'data/maps/OlivineCity_House1_hns/scripts.inc',
    'data/maps/OlivineCity_House2_hns/scripts.inc',
    'data/maps/OlivineCity_House3_hns/scripts.inc',
    'data/maps/OlivineCity_PortInside_hns/scripts.inc',
    'data/maps/OlivineCity_PortOutside_hns/scripts.inc',
    'data/maps/Route40_hns/scripts.inc',
    'data/maps/Route41_hns/scripts.inc',
    'data/maps/CianwoodCity_hns/scripts.inc',
    'data/maps/CianwoodPokecenter_hns/scripts.inc',
    'data/maps/CianwoodShop_hns/scripts.inc',
    'data/maps/CianwoodGym_hns/scripts.inc',
    'data/maps/CianwoodHouse1_hns/scripts.inc',
    'data/maps/CianwoodHouse2_hns/scripts.inc',
    'data/maps/CianwoodHouse3_hns/scripts.inc',
    # Bloque 5
    'data/maps/Route42_hns/scripts.inc',
    'data/maps/MtMortar_1F_North_hns/scripts.inc',
    'data/maps/MtMortar_2F_hns/scripts.inc',
    'data/maps/MtMortar_B1F_hns/scripts.inc',
    'data/maps/Mahoganytown_hns/scripts.inc',
    'data/maps/MahoganyTown_House1_hns/scripts.inc',
    'data/maps/MahoganyTown_PokemonCenter_hns/scripts.inc',
    'data/maps/MahoganyTown_Shop_hns/scripts.inc',
    'data/maps/Gate_MahoganyTown_Route43_hns/scripts.inc',
    'data/maps/Gate_Route43_hns/scripts.inc',
    'data/maps/Route43_hns/scripts.inc',
    'data/maps/LakeOfRage_hns/scripts.inc',
    'data/maps/LakeOfRage_House1_hns/scripts.inc',
    'data/maps/LakeOfRage_House2_hns/scripts.inc',
    'data/maps/RocketHideout_B1F_hns/scripts.inc',
    'data/maps/RocketHideout_B2F_hns/scripts.inc',
    'data/maps/RocketHideout_B3F_hns/scripts.inc',
    'data/maps/MahoganyTown_Gym_hns/scripts.inc',
    'data/maps/GoldenrodCity_RadioTower_2F_hns/scripts.inc',
    'data/maps/GoldenrodCity_RadioTower_3F_hns/scripts.inc',
    'data/maps/GoldenrodCity_RadioTower_4F_hns/scripts.inc',
    'data/maps/GoldenrodCity_RadioTower_5F_hns/scripts.inc',
    'data/maps/GoldenrodCity_UndergroundEntrance_hns/scripts.inc',
    'data/maps/GoldenrodCity_UndergroundStorage_hns/scripts.inc',
    'data/maps/GoldenrodCity_UndergroundSwitches_hns/scripts.inc',
    'data/maps/GoldenrodCity_UndergroundTunnel_hns/scripts.inc',
    'src/randomizer.c',
    'include/move.h',
    'data/text/check_furniture.inc',
    'data/text/pc.inc',
    'src/player_pc.c',
    'data/scripts/berry_tree.inc',
    'data/maps/VioletCity_House2_hns/scripts.inc',
    'data/maps/VioletCity_Mart_hns/scripts.inc',
    'data/maps/SproutTower_1F_hns/scripts.inc',
    'data/maps/SproutTower_2F_hns/scripts.inc',
    'data/maps/RuinsOfAlph_PuzzleAndRewardChambers_hns/scripts.inc',
    'data/maps/Route32_PokemonCenter_hns/scripts.inc',
    'data/maps/AzaleaTown_House1_hns/scripts.inc',
    'data/maps/AzaleaTown_Mart_hns/scripts.inc',
    'data/maps/AzaleaTown_PokemonCenter_hns/scripts.inc',
    'data/maps/Route33_hns/scripts.inc',
    'data/maps/RuinsOfAlph_B1F_hns/scripts.inc',
    'include/nuzlocke.h',
    'src/nuzlocke.c',
    'src/map_name_popup.c',
    'src/battle_main.c',
    'src/naming_screen.c',
    'src/item_use.c',
    'data/scripts/field_move_scripts_hns.inc',
    'src/pokenav_main_menu.c',
    'src/pokenav_match_call_gfx.c',
    'src/pokenav_match_call_list.c',
    'src/pokenav_menu_handler_gfx.c',
    'src/pokenav_radio.c',
    'src/data/text/radio_strings.h',
    'src/data/region_map/region_map_sections.json',
    'src/data/region_map/region_map_entries.h',
    'data/maps/UnionCave_1F_hns/scripts.inc',
    'data/maps/UnionCave_B1F_hns/scripts.inc',
    'data/maps/UnionCave_B2F_hns/scripts.inc',
    'data/maps/Route44_hns/scripts.inc',
    'data/maps/IcePath_1F_hns/scripts.inc',
    'data/maps/IcePath_B1F_hns/scripts.inc',
    'data/maps/IcePath_B3F_hns/scripts.inc',
    'data/maps/BlackthornCity_hns/scripts.inc',
    'data/maps/BlackthornCity_Gym_hns/scripts.inc',
    'data/maps/BlackthornCity_House1_hns/scripts.inc',
    'data/maps/BlackthornCity_House2_hns/scripts.inc',
    'data/maps/BlackthornCity_House3_hns/scripts.inc',
    'data/maps/BlackthornCity_Mart_hns/scripts.inc',
    'data/maps/BlackthornCity_PokemonCenter_hns/scripts.inc',
    'data/maps/DragonsDen_Cavern_hns/scripts.inc',
    'data/maps/DragonsDen_Shrine_hns/scripts.inc',
    'data/text/pc_transfer.inc',
    'include/strings.h',
    'src/egg_hatch.c',
    'src/pokemon_summary_screen.c',
    'src/field_region_map.c',
    'graphics/pokenav/hns/options/hoenn_map.png',
    'graphics/pokenav/options/condition.png',
    'graphics/pokenav/left_headers/condition.png',
    'src/start_menu.c',
    'include/constants/items.h',
    'include/constants/vars.h',
    'include/constants/vars_hns.h',
    'include/item_use.h',
    'src/script_pokemon_util.c',
    'src/data/items.h'
)

foreach ($f in $files) {
    $src = "\\wsl$\Ubuntu\home\falan\pokehns-expansion\" + $f.Replace('/', '\')
    $dst = "Y:\heartandsoul_esp\pokehns-expansion\" + $f.Replace('/', '\')
    $dstDir = [System.IO.Path]::GetDirectoryName($dst)
    if (!(Test-Path $dstDir)) { New-Item -ItemType Directory -Path $dstDir -Force | Out-Null }
    Copy-Item -Path $src -Destination $dst -Force
    Write-Host "Synced $f"
}

# Actualizar siempre pokehns_fase1.gba en la raiz
Copy-Item "\\wsl$\Ubuntu\home\falan\pokehns-expansion\pokehns.gba" "Y:\heartandsoul_esp\pokehns_fase1.gba" -Force

# Determinar nombre de la release versionada
$dateStr = Get-Date -Format "yyyyMMdd"
if ($Version -ne "") {
    if ($Version -notlike "*.gba") {
        if ($Version -like "pokehns-*") {
            $releaseName = "$Version.gba"
        } elseif ($Version -like "*-es") {
            $releaseName = "pokehns-$Version.gba"
        } else {
            $releaseName = "pokehns-$Version-es.gba"
        }
    } else {
        $releaseName = $Version
    }
    $releasePath = "Y:\heartandsoul_esp\releases\$releaseName"
    Copy-Item "\\wsl$\Ubuntu\home\falan\pokehns-expansion\pokehns.gba" $releasePath -Force
    Write-Host "ROM updated in Windows:"
    Write-Host " -> Y:\heartandsoul_esp\pokehns_fase1.gba"
    Write-Host " -> releases\$releaseName"
} else {
    Write-Host "ROM updated in Windows:"
    Write-Host " -> Y:\heartandsoul_esp\pokehns_fase1.gba"
    Write-Host "(No se paso el parametro -Version, por lo que solo se actualizo pokehns_fase1.gba. Usa: .\sync_latest.ps1 -Version '0.7.1-bloque6' para crear una release numerada)"
}



