#!/usr/bin/env python3
"""
translate_phase1.py - Traducción automática Fase 1 de Pokémon Heart & Soul (HNS)
Traducciones oficiales Nintendo España / The Pokémon Company.

Uso:
    python3 translate_phase1.py [ruta_proyecto]
    Si no se especifica ruta, usa el directorio actual.
"""

import re
import os
import sys
import shutil
from datetime import datetime

# =====================================================================
# MOVIMIENTOS - Nombres oficiales español (Gen 1 - Gen 9)
# Fuente: Pokémon HeartGold/SoulSilver ES, Espada/Escudo ES, Escarlata/Púrpura ES
# =====================================================================
MOVE_NAMES = {
    # ── GEN 1 ──────────────────────────────────────────────────────
    "POUND":            "Destructor",
    "KARATE CHOP":      "Golpe Karate",
    "DOUBLE SLAP":      "Doble Bofetón",
    "COMET PUNCH":      "Puñetazo Cometa",
    "MEGA PUNCH":       "Megapuñetazo",
    "PAY DAY":          "Día de Pago",
    "FIRE PUNCH":       "Puñopuego",
    "ICE PUNCH":        "Puñohielo",
    "THUNDER PUNCH":    "Puñotrón",
    "SCRATCH":          "Arañazo",
    "VISE GRIP":        "Agarre",
    "GUILLOTINE":       "Guillotina",
    "RAZOR WIND":       "Viento Cortante",
    "SWORDS DANCE":     "Danza Espada",
    "CUT":              "Corte",
    "GUST":             "Torbellino",
    "WING ATTACK":      "Ataque Ala",
    "WHIRLWIND":        "Vendaval",
    "FLY":              "Vuelo",
    "BIND":             "Constricción",
    "SLAM":             "Golpe",
    "VINE WHIP":        "Látigo Cepa",
    "STOMP":            "Pisotón",
    "DOUBLE KICK":      "Doble Patada",
    "MEGA KICK":        "Megapatada",
    "JUMP KICK":        "Salto Patada",
    "ROLLING KICK":     "Patada Giro",
    "SAND ATTACK":      "Arenisca",
    "HEADBUTT":         "Cabezazo",
    "HORN ATTACK":      "Cornada",
    "FURY ATTACK":      "Furia",
    "HORN DRILL":       "Taladrador",
    "TACKLE":           "Placaje",
    "BODY SLAM":        "Golpe Cuerpo",
    "WRAP":             "Envoltura",
    "TAKE DOWN":        "Derribo",
    "THRASH":           "Pataleta",
    "DOUBLE-EDGE":      "Doble Filo",
    "TAIL WHIP":        "Látigo",
    "POISON STING":     "Púas Venenosas",
    "TWINEEDLE":        "Biaguijón",
    "PIN MISSILE":      "Lanzadera",
    "LEER":             "Mal de Ojo",
    "BITE":             "Mordisco",
    "GROWL":            "Gruñido",
    "ROAR":             "Rugido",
    "SING":             "Canto",
    "SUPERSONIC":       "Supersónico",
    "SONICBOOM":        "Bum Sónico",
    "DISABLE":          "Anulación",
    "ACID":             "Ácido",
    "EMBER":            "Ascuas",
    "FLAMETHROWER":     "Lanzallamas",
    "MIST":             "Niebla",
    "WATER GUN":        "Pistola Agua",
    "HYDRO PUMP":       "Hidrobomba",
    "SURF":             "Surf",
    "ICE BEAM":         "Rayo Hielo",
    "BLIZZARD":         "Ventisca",
    "PSYBEAM":          "Psicoataque",
    "BUBBLE BEAM":      "Burbuja",
    "AURORA BEAM":      "Rayo Aurora",
    "HYPER BEAM":       "Hiperrayo",
    "PECK":             "Picotazo",
    "DRILL PECK":       "Pico Taladro",
    "SUBMISSION":       "Llave Total",
    "LOW KICK":         "Patada Baja",
    "COUNTER":          "Contraataque",
    "SEISMIC TOSS":     "Seísmo",
    "STRENGTH":         "Fuerza",
    "ABSORB":           "Absorber",
    "MEGA DRAIN":       "Megaagotar",
    "LEECH SEED":       "Drenadoras",
    "GROWTH":           "Desarrollo",
    "RAZOR LEAF":       "Hoja Aguda",
    "SOLAR BEAM":       "Rayo Solar",
    "POISON POWDER":    "Polvo Veneno",
    "STUN SPORE":       "Espora Ardor",
    "SLEEP POWDER":     "Somnífero",
    "PETAL DANCE":      "Danza Pétalo",
    "STRING SHOT":      "Disparo Furia",
    "DRAGON RAGE":      "Ira Dragón",
    "FIRE SPIN":        "Llamarada",
    "THUNDER SHOCK":    "Impactrueno",
    "THUNDERBOLT":      "Rayo",
    "THUNDER WAVE":     "Onda Trueno",
    "THUNDER":          "Trueno",
    "ROCK THROW":       "Lanzarrocas",
    "EARTHQUAKE":       "Terremoto",
    "FISSURE":          "Fisura",
    "DIG":              "Excavar",
    "TOXIC":            "Tóxico",
    "CONFUSION":        "Confusión",
    "PSYCHIC":          "Psíquico",
    "HYPNOSIS":         "Hipnosis",
    "MEDITATE":         "Meditación",
    "AGILITY":          "Agilidad",
    "QUICK ATTACK":     "Ataque Rápido",
    "RAGE":             "Enfado",
    "TELEPORT":         "Teletransporte",
    "NIGHT SHADE":      "Sombra Noche",
    "MIMIC":            "Mímica",
    "SCREECH":          "Chirrido",
    "DOUBLE TEAM":      "Doble Equipo",
    "RECOVER":          "Recuperación",
    "HARDEN":           "Fortaleza",
    "MINIMIZE":         "Reducción",
    "SMOKESCREEN":      "Pantalla Humo",
    "CONFUSE RAY":      "Rayo Confuso",
    "WITHDRAW":         "Refugio",
    "DEFENSE CURL":     "Rizo Defensa",
    "BARRIER":          "Barrera",
    "LIGHT SCREEN":     "Pantalla de Luz",
    "HAZE":             "Bruma",
    "REFLECT":          "Reflejo",
    "FOCUS ENERGY":     "Concentración",
    "BIDE":             "Aguante",
    "METRONOME":        "Metrónomo",
    "MIRROR MOVE":      "Espejo",
    "SELF-DESTRUCT":    "Autodestrucción",
    "EGG BOMB":         "Bomba Huevo",
    "LICK":             "Lengüetazo",
    "SMOG":             "Polución",
    "SLUDGE":           "Fango",
    "BONE CLUB":        "Golpe Hueso",
    "FIRE BLAST":       "Deflagración",
    "WATERFALL":        "Cascada",
    "CLAMP":            "Mordaza",
    "SWIFT":            "Rapidez",
    "SKULL BASH":       "Cabeza Zinc",
    "SPIKE CANNON":     "Cañón Pua",
    "CONSTRICT":        "Constricción",
    "AMNESIA":          "Amnesia",
    "KINESIS":          "Kinesis",
    "SOFT-BOILED":      "Curación",
    "HIGH JUMP KICK":   "Gran Salto Patada",
    "GLARE":            "Mirada Letal",
    "DREAM EATER":      "Come Sueños",
    "POISON GAS":       "Gas Venenoso",
    "BARRAGE":          "Avalancha",
    "LEECH LIFE":       "Vampiabsorber",
    "LOVELY KISS":      "Dulce Beso",
    "SKY ATTACK":       "Ataque Aéreo",
    "TRANSFORM":        "Transformación",
    "BUBBLE":           "Burbuja",
    "DIZZY PUNCH":      "Puño Matraca",
    "SPORE":            "Espora",
    "FLASH":            "Destello",
    "PSYWAVE":          "Psicoonda",
    "SPLASH":           "Salpicar",
    "ACID ARMOR":       "Armadura Ácida",
    "CRABHAMMER":       "Martillazo",
    "EXPLOSION":        "Explosión",
    "FURY SWIPES":      "Garras Furia",
    "BONEMERANG":       "Bumerhueso",
    "REST":             "Descanso",
    "ROCK SLIDE":       "Avalancha",
    "HYPER FANG":       "Hiperfauce",
    "SHARPEN":          "Afilado",
    "CONVERSION":       "Transformación",
    "TRI ATTACK":       "Triataque",
    "SUPER FANG":       "Superfauce",
    "SLASH":            "Cuchillada",
    "SUBSTITUTE":       "Sustituto",
    "STRUGGLE":         "Forcejeo",
    "SKETCH":           "Croquis",
    # ── GEN 2 ──────────────────────────────────────────────────────
    "TRIPLE KICK":      "Triple Patada",
    "THIEF":            "Ladrón",
    "SPIDER WEB":       "Tela Araña",
    "MIND READER":      "Lectura Mental",
    "NIGHTMARE":        "Pesadilla",
    "FLAME WHEEL":      "Rueda Fuego",
    "SNORE":            "Ronquido",
    "CURSE":            "Maldición",
    "FLAIL":            "Languidez",
    "CONVERSION 2":     "Metamorfosis 2",
    "AEROBLAST":        "Aeroataque",
    "COTTON SPORE":     "Espora Algodón",
    "REVERSAL":         "Inversión",
    "SPITE":            "Rencor",
    "POWDER SNOW":      "Nieve Polvo",
    "PROTECT":          "Protección",
    "MACH PUNCH":       "Puño Bala",
    "SCARY FACE":       "Cara Susto",
    "FEINT ATTACK":     "Golpe Bajo",
    "SWEET KISS":       "Beso Dulce",
    "BELLY DRUM":       "Tamborileo",
    "SLUDGE BOMB":      "Bomba Fango",
    "MUD-SLAP":         "Fangada",
    "OCTAZOOKA":        "Octalanzador",
    "SPIKES":           "Trampa Rocas",
    "ZAP CANNON":       "Cañón Eléc",
    "FORESIGHT":        "Presciencia",
    "DESTINY BOND":     "Lazo Destino",
    "PERISH SONG":      "Canto Mortal",
    "ICY WIND":         "Viento Hielo",
    "DETECT":           "Detección",
    "BONE RUSH":        "Hueso Danza",
    "LOCK-ON":          "Fijar Blanco",
    "OUTRAGE":          "Enfurecimiento",
    "SANDSTORM":        "Tormenta Arena",
    "GIGA DRAIN":       "Gigaagotar",
    "ENDURE":           "Aguante",
    "CHARM":            "Encanto",
    "ROLLOUT":          "Rugido",
    "FALSE SWIPE":      "Golpe Falso",
    "SWAGGER":          "Fanfarronada",
    "MILK DRINK":       "Leche Cura",
    "SPARK":            "Chispa",
    "FURY CUTTER":      "Corte Furia",
    "STEEL WING":       "Ala Acero",
    "MEAN LOOK":        "Cara Rara",
    "ATTRACT":          "Seducción",
    "SLEEP TALK":       "Soñoliloquio",
    "HEAL BELL":        "Campana Cura",
    "RETURN":           "Retribución",
    "PRESENT":          "Regalo",
    "FRUSTRATION":      "Frustración",
    "SAFEGUARD":        "Pantalla Mágica",
    "PAIN SPLIT":       "Divide Dolor",
    "SACRED FIRE":      "Fuego Sagrado",
    "MAGNITUDE":        "Magnitud",
    "DYNAMIC PUNCH":    "Dinamopuño",
    "MEGAHORN":         "Megacuerno",
    "DRAGON BREATH":    "Aliento Dragón",
    "BATON PASS":       "Cambio Testigo",
    "ENCORE":           "Fin de Fiesta",
    "PURSUIT":          "Persecución",
    "RAPID SPIN":       "Giro Rápido",
    "SWEET SCENT":      "Aroma",
    "IRON TAIL":        "Cola Férrea",
    "METAL CLAW":       "Garra Metal",
    "VITAL THROW":      "Lanzamiento",
    "MORNING SUN":      "Sol Matutino",
    "SYNTHESIS":        "Síntesis",
    "MOONLIGHT":        "Luz Lunar",
    "HIDDEN POWER":     "Velo Oculto",
    "CROSS CHOP":       "Cruz Navaja",
    "TWISTER":          "Torbellino",
    "RAIN DANCE":       "Lluvia Danza",
    "SUNNY DAY":        "Día Soleado",
    "CRUNCH":           "Triturar",
    "MIRROR COAT":      "Espejo Coat",
    "PSYCH UP":         "Análisis",
    "EXTREME SPEED":    "Velocidad Extrema",
    "ANCIENT POWER":    "Poder Ancestral",
    "SHADOW BALL":      "Bola Sombra",
    "FUTURE SIGHT":     "Visión Futura",
    "ROCK SMASH":       "Golpe Roca",
    "WHIRLPOOL":        "Remolino",
    "BEAT UP":          "Paliza",
    # ── GEN 3 ──────────────────────────────────────────────────────
    "FAKE OUT":         "Sorpresa",
    "UPROAR":           "Estrépito",
    "STOCKPILE":        "Reserva",
    "SPIT UP":          "Escupir",
    "SWALLOW":          "Tragar",
    "HEAT WAVE":        "Calor",
    "HAIL":             "Granizo",
    "TORMENT":          "Tormento",
    "FLATTER":          "Lisonja",
    "WILL-O-WISP":      "Fuego Fatuo",
    "MEMENTO":          "Memento",
    "FACADE":           "Fachada",
    "FOCUS PUNCH":      "Puño Certero",
    "SMELLING SALTS":   "Sales",
    "FOLLOW ME":        "Sígueme",
    "NATURE POWER":     "Poder Natural",
    "CHARGE":           "Carga",
    "TAUNT":            "Provocación",
    "HELPING HAND":     "Ayuda",
    "TRICK":            "Truco",
    "ROLE PLAY":        "Papelón",
    "WISH":             "Deseo",
    "ASSIST":           "Auxilio",
    "INGRAIN":          "Arraigo",
    "SUPERPOWER":       "Superpotencia",
    "MAGIC COAT":       "Manto Mágico",
    "RECYCLE":          "Reciclaje",
    "REVENGE":          "Venganza",
    "BRICK BREAK":      "Rompe Pantalla",
    "YAWN":             "Bostezo",
    "KNOCK OFF":        "Golpe Bajo",
    "ENDEAVOR":         "Igualador",
    "ERUPTION":         "Erupción",
    "SKILL SWAP":       "Intercambio",
    "IMPRISON":         "Sellado",
    "REFRESH":          "Refresco",
    "GRUDGE":           "Rencilla",
    "SNATCH":           "Arrebato",
    "SECRET POWER":     "Poder Secreto",
    "DIVE":             "Buceo",
    "ARM THRUST":       "Puñada Doble",
    "CAMOUFLAGE":       "Camuflaje",
    "TAIL GLOW":        "Cola Brillo",
    "LUSTER PURGE":     "Brillo Pureza",
    "MIST BALL":        "Bola Niebla",
    "FEATHER DANCE":    "Plumas Danza",
    "TEETER DANCE":     "Danza Zigzag",
    "BLAZE KICK":       "Patada Ígnea",
    "MUD SPORT":        "Fango Activo",
    "ICE BALL":         "Bola Hielo",
    "NEEDLE ARM":       "Brazo Garfio",
    "SLACK OFF":        "Escaqueo",
    "HYPER VOICE":      "Hiper Voz",
    "POISON FANG":      "Colmillo Venenoso",
    "CRUSH CLAW":       "Garra Brutal",
    "BLAST BURN":       "Anillo Ígneo",
    "HYDRO CANNON":     "Hidrocometa",
    "METEOR MASH":      "Golpe Meteoro",
    "ASTONISH":         "Asombro",
    "WEATHER BALL":     "Bola Tiempo",
    "AROMATHERAPY":     "Aromaterapia",
    "FAKE TEARS":       "Falso Llanto",
    "AIR CUTTER":       "Cuchillo Aéreo",
    "OVERHEAT":         "Sofoco",
    "ODOR SLEUTH":      "Olfateo",
    "ROCK TOMB":        "Tumba Roca",
    "SILVER WIND":      "Viento Plata",
    "METAL SOUND":      "Ruido Metal",
    "GRASS WHISTLE":    "Silbato Yerba",
    "TICKLE":           "Cosquillas",
    "COSMIC POWER":     "Poder Cósmico",
    "WATER SPOUT":      "Chorro Agua",
    "SIGNAL BEAM":      "Señal Luminosa",
    "SHADOW PUNCH":     "Puño Sombra",
    "EXTRASENSORY":     "Supersensorial",
    "SKY UPPERCUT":     "Gancho Alto",
    "SAND TOMB":        "Trampa Arena",
    "SHEER COLD":       "Frío Polar",
    "MUDDY WATER":      "Agua Lodosa",
    "BULLET SEED":      "Semilla Bala",
    "AERIAL ACE":       "Acróbata",
    "ICICLE SPEAR":     "Carámbano",
    "IRON DEFENSE":     "Defensa Acerada",
    "BLOCK":            "Bloqueo",
    "HOWL":             "Alarido",
    "DRAGON CLAW":      "Garra Dragón",
    "FRENZY PLANT":     "Caña Furia",
    "BULK UP":          "Corpulencia",
    "BOUNCE":           "Rebote",
    "MUD SHOT":         "Lanzafango",
    "POISON TAIL":      "Cola Venenosa",
    "COVET":            "Codicia",
    "VOLT TACKLE":      "Voltio Cruel",
    "MAGICAL LEAF":     "Hoja Mágica",
    "WATER SPORT":      "Acuaplaning",
    "CALM MIND":        "Mente Serena",
    "LEAF BLADE":       "Hoja Aguda",
    "DRAGON DANCE":     "Danza Dragón",
    "ROCK BLAST":       "Roca Afilada",
    "SHOCK WAVE":       "Onda Voltio",
    "WATER PULSE":      "Pulso Agua",
    "DOOM DESIRE":      "Deseo Fúnebre",
    "PSYCHO BOOST":     "Psicosalva",
    # ── GEN 4 ──────────────────────────────────────────────────────
    "ROOST":            "Alas Descanso",
    "GRAVITY":          "Gravedad",
    "MIRACLE EYE":      "Ojo Mágico",
    "WAKE-UP SLAP":     "Bofetón",
    "HAMMER ARM":       "Brazo Martillo",
    "GYRO BALL":        "Giro Bola",
    "HEALING WISH":     "Deseo Cura",
    "BRINE":            "Salmuera",
    "NATURAL GIFT":     "Don Natural",
    "FEINT":            "Finta",
    "PLUCK":            "Picoteo",
    "TAILWIND":         "Viento Afín",
    "ACUPRESSURE":      "Acupresión",
    "METAL BURST":      "Contraataque Férreo",
    "U-TURN":           "Ida y Vuelta",
    "CLOSE COMBAT":     "Combate",
    "PAYBACK":          "Represalia",
    "ASSURANCE":        "Seguridad",
    "EMBARGO":          "Embargo",
    "FLING":            "Lanzamiento",
    "PSYCHO SHIFT":     "Turno Psíquico",
    "TRUMP CARD":       "Triunfo",
    "HEAL BLOCK":       "Antiterapia",
    "WRING OUT":        "Exprimir",
    "POWER TRICK":      "Truco Potencia",
    "GASTRO ACID":      "Ácido Gástrico",
    "LUCKY CHANT":      "Canto Suerte",
    "ME FIRST":         "Primero Yo",
    "COPYCAT":          "Imitador",
    "POWER SWAP":       "Intercambia Fuerzas",
    "GUARD SWAP":       "Intercambia Defensas",
    "PUNISHMENT":       "Castigo",
    "LAST RESORT":      "Último Recurso",
    "WORRY SEED":       "Semilla Inquietud",
    "SUCKER PUNCH":     "Punto Débil",
    "TOXIC SPIKES":     "Clavo Venenoso",
    "HEART SWAP":       "Intercambia Corazón",
    "AQUA RING":        "Anillo Acuático",
    "MAGNET RISE":      "Levitación Magnética",
    "FLARE BLITZ":      "Llamarada",
    "FORCE PALM":       "Golpe Fuerza",
    "AURA SPHERE":      "Esfera Aural",
    "ROCK POLISH":      "Pule Roca",
    "POISON JAB":       "Jab Veneno",
    "DARK PULSE":       "Pulso Umbrío",
    "NIGHT SLASH":      "Noche Cerrada",
    "AQUA TAIL":        "Acua Cola",
    "SEED BOMB":        "Semilla Bomba",
    "AIR SLASH":        "Tajo Aéreo",
    "X-SCISSOR":        "Tijera X",
    "BUG BUZZ":         "Zum Bicho",
    "DRAGON PULSE":     "Pulso Dragón",
    "DRAGON RUSH":      "Avalancha Dragón",
    "POWER GEM":        "Gema Poder",
    "DRAIN PUNCH":      "Drenado Puño",
    "VACUUM WAVE":      "Ola Vacío",
    "FOCUS BLAST":      "Defensa Bola",
    "ENERGY BALL":      "Bola Energía",
    "BRAVE BIRD":       "Pájaro Osado",
    "EARTH POWER":      "Poder Tierra",
    "SWITCHEROO":       "Trapicheo",
    "GIGA IMPACT":      "Giga Impacto",
    "NASTY PLOT":       "Jugarreta",
    "BULLET PUNCH":     "Puño Bala",
    "AVALANCHE":        "Avalancha",
    "ICE SHARD":        "Nieve Velo",
    "SHADOW CLAW":      "Garra Umbría",
    "THUNDER FANG":     "Colmillo Rayo",
    "ICE FANG":         "Colmillo Hielo",
    "FIRE FANG":        "Colmillo Ígneo",
    "SHADOW SNEAK":     "Sombra Vil",
    "MUD BOMB":         "Bomba Barro",
    "PSYCHO CUT":       "Psicocorte",
    "ZEN HEADBUTT":     "Zen Cabezazo",
    "MIRROR SHOT":      "Espejo Shot",
    "FLASH CANNON":     "Cañón Flash",
    "ROCK CLIMB":       "Escalada",
    "DEFOG":            "Antivaho",
    "TRICK ROOM":       "Sala Trampa",
    "DRACO METEOR":     "Cometa Draco",
    "DISCHARGE":        "Descarga",
    "LAVA PLUME":       "Erupción Lava",
    "LEAF STORM":       "Tormenta Floral",
    "POWER WHIP":       "Látigo Potencia",
    "ROCK WRECKER":     "Roca Destructora",
    "CROSS POISON":     "Cruz Venenosa",
    "GUNK SHOT":        "Lanzamiento Basura",
    "IRON HEAD":        "Cabeza de Hierro",
    "MAGNET BOMB":      "Bomba Magnética",
    "STONE EDGE":       "Filo Roca",
    "CAPTIVATE":        "Hechizar",
    "STEALTH ROCK":     "Trampa Rocas",
    "GRASS KNOT":       "Hierba Lazo",
    "CHATTER":          "Charla",
    "JUDGMENT":         "Sentencia",
    "BUG BITE":         "Picadura",
    "CHARGE BEAM":      "Rayo Carga",
    "WOOD HAMMER":      "Martillo Madera",
    "AQUA JET":         "Aqua Jet",
    "ATTACK ORDER":     "Orden Ataque",
    "DEFEND ORDER":     "Orden Defensa",
    "HEAL ORDER":       "Orden Curación",
    "HEAD SMASH":       "Golpe Cabeza",
    "DOUBLE HIT":       "Doble Impacto",
    "ROAR OF TIME":     "Rugido Temporal",
    "SPACIAL REND":     "Corte Espacial",
    "LUNAR DANCE":      "Danza Lunar",
    "CRUSH GRIP":       "Agarre Brutal",
    "MAGMA STORM":      "Tormenta de Magma",
    "DARK VOID":        "Oscuridad",
    "SEED FLARE":       "Explosión Floral",
    "OMINOUS WIND":     "Viento Ominoso",
    "SHADOW FORCE":     "Sombra Cruel",
    # ── GEN 5 ──────────────────────────────────────────────────────
    "HONE CLAWS":       "Afilar Garras",
    "WIDE GUARD":       "Guardia Amplia",
    "GUARD SPLIT":      "Repartir Defensa",
    "POWER SPLIT":      "Repartir Fuerza",
    "WONDER ROOM":      "Sala Mística",
    "PSYSHOCK":         "Impacto Psíquico",
    "VENOSHOCK":        "Venoshock",
    "AUTOTOMIZE":       "Autotomización",
    "RAGE POWDER":      "Polvo Ira",
    "TELEKINESIS":      "Telequinesis",
    "MAGIC ROOM":       "Sala Mágica",
    "SMACK DOWN":       "Derribo",
    "STORM THROW":      "Lanzamiento Tormenta",
    "FLAME BURST":      "Llamarada",
    "SLUDGE WAVE":      "Ola Fango",
    "QUIVER DANCE":     "Danza Aleteo",
    "HEAVY SLAM":       "Slam Pesado",
    "SYNCHRONOISE":     "Sincrorruido",
    "ELECTRO BALL":     "Bola Electro",
    "SOAK":             "Empapar",
    "FLAME CHARGE":     "Carga Ígnea",
    "COIL":             "Enrollar",
    "LOW SWEEP":        "Barrido Bajo",
    "ACID SPRAY":       "Spray Ácido",
    "FOUL PLAY":        "Juego Sucio",
    "SIMPLE BEAM":      "Haz Simple",
    "ENTRAINMENT":      "Arrastre",
    "AFTER YOU":        "Después de Ti",
    "ROUND":            "Ronda",
    "ECHOED VOICE":     "Voz Eco",
    "CHIP AWAY":        "Erosionar",
    "CLEAR SMOG":       "Niebla Despejada",
    "STORED POWER":     "Poder Almacenado",
    "QUICK GUARD":      "Guardia Rápida",
    "ALLY SWITCH":      "Cambio Aliado",
    "SCALD":            "Escaldar",
    "SHELL SMASH":      "Rompe Caparazón",
    "HEAL PULSE":       "Pulso Cura",
    "HEX":              "Maleficio",
    "SKY DROP":         "Caída Aérea",
    "SHIFT GEAR":       "Acelerar",
    "CIRCLE THROW":     "Lanzamiento Circular",
    "INCINERATE":       "Incineración",
    "QUASH":            "Rezagar",
    "ACROBATICS":       "Acrobacia",
    "REFLECT TYPE":     "Reflejo Tipo",
    "RETALIATE":        "Represalia",
    "FINAL GAMBIT":     "Golpe Postrero",
    "BESTOW":           "Conceder",
    "INFERNO":          "Infierno",
    "WATER PLEDGE":     "Promesa Agua",
    "FIRE PLEDGE":      "Promesa Fuego",
    "GRASS PLEDGE":     "Promesa Planta",
    "VOLT SWITCH":      "Voltio Cambio",
    "STRUGGLE BUG":     "Fuerza Bicho",
    "BULLDOZE":         "Apisonar",
    "FROST BREATH":     "Soplido Frío",
    "DRAGON TAIL":      "Cola Dragón",
    "WORK UP":          "Preparación",
    "ELECTROWEB":       "Telaraña Eléctrica",
    "WILD CHARGE":      "Voltio Salvaje",
    "DRILL RUN":        "Taladradora",
    "DUAL CHOP":        "Doble Tajo",
    "HEART STAMP":      "Sello Corazón",
    "HORN LEECH":       "Cuerno Vampírico",
    "SACRED SWORD":     "Espada Sagrada",
    "RAZOR SHELL":      "Concha Filo",
    "HEAT CRASH":       "Impacto Ígneo",
    "LEAF TORNADO":     "Tornado Hoja",
    "STEAMROLLER":      "Apisonadora",
    "COTTON GUARD":     "Escudo Algodón",
    "NIGHT DAZE":       "Noche Oscura",
    "PSYSTRIKE":        "Psicoimpacto",
    "TAIL SLAP":        "Coletazo",
    "HURRICANE":        "Huracán",
    "HEAD CHARGE":      "Carga Brutal",
    "GEAR GRIND":       "Muela Piñón",
    "SEARING SHOT":     "Disparo Abrasador",
    "TECHNO BLAST":     "Tecno Disparo",
    "RELIC SONG":       "Canto Ancestral",
    "SECRET SWORD":     "Espada Secreta",
    "GLACIATE":         "Glaciación",
    "BOLT STRIKE":      "Rayo Fulgor",
    "BLUE FLARE":       "Llama Azul",
    "FIERY DANCE":      "Danza Ígnea",
    "FREEZE SHOCK":     "Impacto Gélido",
    "ICE BURN":         "Quemadura Polar",
    "SNARL":            "Rugido Vil",
    "ICICLE CRASH":     "Carámbano Brutal",
    "V-CREATE":         "Chispa V",
    "FUSION FLARE":     "Destello Fusión",
    "FUSION BOLT":      "Rayo Fusión",
    # ── GEN 6 ──────────────────────────────────────────────────────
    "FLYING PRESS":     "Presión Aérea",
    "MAT BLOCK":        "Tatami",
    "BELCH":            "Eructo",
    "ROTOTILLER":       "Rotatiller",
    "STICKY WEB":       "Tela Pegajosa",
    "FELL STINGER":     "Aguijón Mortal",
    "PHANTOM FORCE":    "Fuerza Fantasma",
    "TRICK-OR-TREAT":   "Truco o Trato",
    "NOBLE ROAR":       "Rugido Noble",
    "ION DELUGE":       "Diluvio Iónico",
    "PARABOLIC CHARGE": "Carga Parabólica",
    "FOREST'S CURSE":   "Maldición del Bosque",
    "PETAL BLIZZARD":   "Tormenta de Pétalos",
    "FREEZE-DRY":       "Ultrafrío",
    "DISARMING VOICE":  "Voz Cautivadora",
    "PARTING SHOT":     "Tiro de Salida",
    "TOPSY-TURVY":      "Cambio Total",
    "DRAINING KISS":    "Beso Vampírico",
    "CRAFTY SHIELD":    "Escudo Astuto",
    "FLOWER SHIELD":    "Escudo Floral",
    "GRASSY TERRAIN":   "Terreno de Hierba",
    "MISTY TERRAIN":    "Terreno de Niebla",
    "ELECTRIFY":        "Electrificar",
    "PLAY ROUGH":       "Juego Brusco",
    "FAIRY WIND":       "Viento Feérico",
    "MOONBLAST":        "Explosion Lunar",
    "BOOMBURST":        "Explosión Sonora",
    "FAIRY LOCK":       "Cerradura Feérica",
    "KING'S SHIELD":    "Escudo Real",
    "PLAY NICE":        "Juego Limpio",
    "CONFIDE":          "Confidencia",
    "DIAMOND STORM":    "Tormenta de Diamante",
    "STEAM ERUPTION":   "Erupción Vapor",
    "HYPERSPACE HOLE":  "Hiperespacio",
    "WATER SHURIKEN":   "Shuriken de Agua",
    "MYSTICAL FIRE":    "Fuego Místico",
    "SPIKY SHIELD":     "Escudo de Pinchos",
    "AROMATIC MIST":    "Niebla Aromática",
    "EERIE IMPULSE":    "Impulso Eerie",
    "VENOM DRENCH":     "Ducha Veneno",
    "POWDER":           "Polvo",
    "GEOMANCY":         "Geomancia",
    "MAGNETIC FLUX":    "Flujo Magnético",
    "HAPPY HOUR":       "Hora Feliz",
    "ELECTRIC TERRAIN": "Terreno Eléctrico",
    "DAZZLING GLEAM":   "Flash Cañón",
    "CELEBRATE":        "Celebración",
    "HOLD HANDS":       "Coger la Mano",
    "BABY-DOLL EYES":   "Ojos de Muñeca",
    "NUZZLE":           "Carantona",
    "HOLD BACK":        "Frenar",
    "INFESTATION":      "Infestación",
    "POWER-UP PUNCH":   "Puño Poder",
    "OBLIVION WING":    "Ala del Olvido",
    "THOUSAND ARROWS":  "Mil Flechas",
    "THOUSAND WAVES":   "Mil Olas",
    "LANDS WRATH":      "Ira de la Tierra",
    "LIGHT OF RUIN":    "Luz Devastadora",
    "ORIGIN PULSE":     "Pulso Primigenio",
    "PRECIPICE BLADES": "Hojas Abismales",
    "DRAGON ASCENT":    "Ascenso Dragón",
    "HYPERSPACE FURY":  "Furia Hiperespacio",
    # ── GEN 7 ──────────────────────────────────────────────────────
    "SHORE UP":         "Sedimentar",
    "FIRST IMPRESSION": "Primera Impresión",
    "BANEFUL BUNKER":   "Búnker Tóxico",
    "SPIRIT SHACKLE":   "Grillete Espiritual",
    "DARKEST LARIAT":   "Lazo Oscuro",
    "SPARKLING ARIA":   "Aria Centelleante",
    "ICE HAMMER":       "Martillo Hielo",
    "FLORAL HEALING":   "Cura Floral",
    "HIGH HORSEPOWER":  "Pura Potencia",
    "STRENGTH SAP":     "Zumo Fuerza",
    "SOLAR BLADE":      "Hoja Solar",
    "LEAFAGE":          "Hojas",
    "SPOTLIGHT":        "Foco de Luz",
    "TOXIC THREAD":     "Hilo Tóxico",
    "LASER FOCUS":      "Enfoque Láser",
    "GEAR UP":          "Engranar",
    "THROAT CHOP":      "Garganta Golpe",
    "POLLEN PUFF":      "Pompón Polen",
    "ANCHOR SHOT":      "Disparo Ancla",
    "PSYCHIC TERRAIN":  "Terreno Psíquico",
    "LUNGE":            "Abalanzarse",
    "FIRE LASH":        "Látigo Ígneo",
    "POWER TRIP":       "Viaje Poder",
    "BURN UP":          "Quema Total",
    "SPEED SWAP":       "Cambio Velocidad",
    "SMART STRIKE":     "Golpe Certero",
    "PURIFY":           "Purificación",
    "REVELATION DANCE": "Danza Revelación",
    "CORE ENFORCER":    "Extintor de Habilidad",
    "TROP KICK":        "Patada Tropical",
    "INSTRUCT":         "Instrucción",
    "BEAK BLAST":       "Pico Explosivo",
    "CLANGING SCALES":  "Escamas Resonantes",
    "DRAGON HAMMER":    "Martillo Dragón",
    "BRUTAL SWING":     "Golpe Brutal",
    "AURORA VEIL":      "Velo Aurora",
    "SINISTER ARROW RAID": "Flechas Siniestras",
    "MALICIOUS MOONSAULT": "Mortal en Picado",
    "OCEANIC OPERETTA":    "Sinfonía Oceánica",
    "GUARDIAN OF ALOLA":   "Guardián de Alola",
    "SOUL-STEALING 7-STAR STRIKE": "Ataque de Siete Astros",
    "STOKED SPARKSURFER":  "Surfeo Electrizante",
    "PULVERIZING PANCAKE":  "Aplastamiento",
    "EXTREME EVOBOOST":     "Evolución Extrema",
    "GENESIS SUPERNOVA":    "Supernova Génesis",
    "MOON LIGHT":           "Luz Lunar",
    "10000000 VOLT THUNDERBOLT": "Rayo de 10.000.000 V",
    "MIND BLOWN":       "Explosión Mental",
    "PLASMA FISTS":     "Puños de Plasma",
    "PHOTON GEYSER":    "Géiser Fotónico",
    "LIGHT THAT BURNS THE SKY": "Luz que Quema el Cielo",
    "SEARING SUNRAZE SMASH": "Machacamiento Solar",
    "MENACING MOONRAZE MAELSTROM": "Torbellino Lunar",
    "LET'S SNUGGLE FOREVER": "Acurrucados Para Siempre",
    "SPLINTERED STORMSHARDS": "Fragmentos de Tormenta",
    "CLANGOROUS SOULBLAZE": "Llamarada Resonante",
    # ── GEN 8 ──────────────────────────────────────────────────────
    "ZIPPY ZAP":        "Electro Veloz",
    "SPLISHY SPLASH":   "Salpicada",
    "FLOATY FALL":      "Caída Flotante",
    "PIKA PAPOW":       "Pika Papow",
    "BOUNCY BUBBLE":    "Burbuja Rebote",
    "BUZZY BUZZ":       "Zum Zum",
    "SIZZLY SLIDE":     "Chirrido Ígneo",
    "GLITZY GLOW":      "Brillante Glow",
    "BADDY BAD":        "Maldad Total",
    "SAPPY SEED":       "Semilla Savia",
    "FREEZY FROST":     "Frost Helado",
    "SPARKLY SWIRL":    "Espiral Chispa",
    "VEEVEE VOLLEY":    "Volea Eevee",
    "DOUBLE IRON BASH": "Doble Golpe Férreo",
    "MAX GUARD":        "Máx. Guardia",
    "DYNAMAX CANNON":   "Cañón Dinamax",
    "SNIPE SHOT":       "Disparo Preciso",
    "JAW LOCK":         "Mandíbula Letal",
    "STUFF CHEEKS":     "Atracar Mejillas",
    "NO RETREAT":       "Sin Retirada",
    "TAR SHOT":         "Disparo Alquitrán",
    "MAGIC POWDER":     "Polvo Mágico",
    "DRAGON DARTS":     "Dardos Dragón",
    "TEATIME":          "Hora del Té",
    "OCTOLOCK":         "Octocerrojo",
    "BOLT BEAK":        "Pico Rayo",
    "FISHIOUS REND":    "Dentellada",
    "COURT CHANGE":     "Cambio de Campo",
    "CLANGOROUS SOUL":  "Alma Resonante",
    "BODY PRESS":       "Golpe Cuerpo",
    "DECORATE":         "Decorar",
    "DRUM BEATING":     "Redoble",
    "SNAP TRAP":        "Trampa Boca",
    "PYRO BALL":        "Bola de Fuego",
    "BEHEMOTH BLADE":   "Espada Gigante",
    "BEHEMOTH BASH":    "Golpe Gigante",
    "AURA WHEEL":       "Rueda Aural",
    "BREAKING SWIPE":   "Golpe Demoledor",
    "BRANCH POKE":      "Golpe Rama",
    "OVERDRIVE":        "Sobredrive",
    "APPLE ACID":       "Ácido Manzana",
    "GRAV APPLE":       "Manzana Pesada",
    "SPIRIT BREAK":     "Rompe Espíritu",
    "STRANGE STEAM":    "Vapor Extraño",
    "LIFE DEW":         "Rocío Vital",
    "OBSTRUCT":         "Obstrucción",
    "FALSE SURRENDER":  "Falsa Rendición",
    "METEOR ASSAULT":   "Asalto Meteorito",
    "ETERNABEAM":       "Haz Eterno",
    "STEEL BEAM":       "Rayo de Acero",
    "EXPANDING FORCE":  "Fuerza Expansiva",
    "STEEL ROLLER":     "Rodillo Acero",
    "SCALE SHOT":       "Escamas Bala",
    "METEOR BEAM":      "Rayo Meteoro",
    "SHELL SIDE ARM":   "Caña Venenosa",
    "MISTY EXPLOSION":  "Explosión Brumosa",
    "GRASSY GLIDE":     "Deslizamiento Grassy",
    "RISING VOLTAGE":   "Voltaje Creciente",
    "TERRAIN PULSE":    "Pulso Terrestre",
    "SKITTER SMACK":    "Tarascada",
    "BURNING JEALOUSY": "Envidia Ardiente",
    "LASH OUT":         "Desahogo",
    "POLTERGEIST":      "Poltergeist",
    "CORROSIVE GAS":    "Gas Corrosivo",
    "COACHING":         "Entrenamiento",
    "FLIP TURN":        "Viraje",
    "TRIPLE AXEL":      "Triple Axel",
    "DUAL WINGBEAT":    "Doble Aleteo",
    "SCORCHING SANDS":  "Arenas Ardientes",
    "JUNGLE HEALING":   "Cura Selva",
    "WICKED BLOW":      "Golpe Pérfido",
    "SURGING STRIKES":  "Marejada de Golpes",
    "THUNDER CAGE":     "Jaula Eléctrica",
    "DRAGON ENERGY":    "Energía Dragón",
    "FREEZING GLARE":   "Mirada Gélida",
    "FIERY WRATH":      "Ira Ígnea",
    "THUNDEROUS KICK":  "Patada Tronante",
    "GLACIAL LANCE":    "Lanza Glacial",
    "ASTRAL BARRAGE":   "Lluvia Astral",
    "EERIE SPELL":      "Hechizo Eerie",
    "DIRE CLAW":        "Garra Terrible",
    "PSYSHIELD BASH":   "Golpe Escudo Psíquico",
    "POWER SHIFT":      "Cambio de Poder",
    "STONE AXE":        "Hacha de Piedra",
    "SPRINGTIDE STORM": "Tormenta Primaveral",
    "MYSTICAL POWER":   "Poder Místico",
    "RAGING FURY":      "Furia Salvaje",
    "WAVE CRASH":       "Choque de Ola",
    "CHLOROBLAST":      "Cloroexplosión",
    "MOUNTAIN GALE":    "Ventarrón",
    "VICTORY DANCE":    "Danza Victoria",
    "HEADLONG RUSH":    "Arremetida",
    "BARB BARRAGE":     "Lluvia de Púas",
    "ESPER WING":       "Ala Esper",
    "BITTER MALICE":    "Malicia Amarga",
    "SHELTER":          "Refugio",
    "TRIPLE ARROWS":    "Triple Flecha",
    "INFERNAL PARADE":  "Desfile Infernal",
    "CEASELESS EDGE":   "Filo Incesante",
    "BLEAKWIND STORM":  "Vendaval Desolador",
    "WILDBOLT STORM":   "Tormenta Salvaje",
    "SANDSEAR STORM":   "Tormenta de Arena Abrasadora",
    "LUNAR BLESSING":   "Bendición Lunar",
    "TAKE HEART":       "Cobrar Ánimo",
    # ── GEN 9 ──────────────────────────────────────────────────────
    "TERA BLAST":           "Teraexplosión",
    "SILK TRAP":            "Trampa de Seda",
    "AXE KICK":             "Patada Hacha",
    "LAST RESPECTS":        "Último Respeto",
    "LUMINA CRASH":         "Estruendo Lumínico",
    "ORDER UP":             "¡A sus órdenes!",
    "JET PUNCH":            "Puño Cohete",
    "SPICY EXTRACT":        "Esencia Picante",
    "SPIN OUT":             "Derrape",
    "POPULATION BOMB":      "Bomba Poblacional",
    "ICE SPINNER":          "Peón de Hielo",
    "GLAIVE RUSH":          "Arremetida Espadón",
    "REVIVAL BLESSING":     "Bendición Revival",
    "SALT CURE":            "Cura con Sal",
    "TRIPLE DIVE":          "Triple Inmersión",
    "MORTAL SPIN":          "Giro Mortal",
    "DOODLE":               "Garabato",
    "FILLET AWAY":          "Autosacrificarse",
    "KOWTOW CLEAVE":        "Reverencia Filo",
    "FLOWER TRICK":         "Truco Floral",
    "TORCH SONG":           "Canción de la Antorcha",
    "AQUA STEP":            "Paso Acuático",
    "RAGING BULL":          "Toro Enfurecido",
    "MAKE IT RAIN":         "Que Llueva",
    "RUINATION":            "Ruina",
    "COLLISION COURSE":     "Ruta de Colisión",
    "ELECTRO DRIFT":        "Deriva Electro",
    "SHED TAIL":            "Muda de Cola",
    "CHILLY RECEPTION":     "Recibimiento Gélido",
    "TIDY UP":              "Limpiar",
    "SNOWSCAPE":            "Ventisca",
    "POUNCE":               "Saltar",
    "TRAILBLAZE":           "Desbrozar",
    "CHILLING WATER":       "Agua Helada",
    "HYPER DRILL":          "Hipertaladradora",
    "TWIN BEAM":            "Haz Doble",
    "RAGE FIST":            "Puño Rabioso",
    "ARMOR CANNON":         "Cañón Armadura",
    "BITTER BLADE":         "Filo Amargo",
    "DOUBLE SHOCK":         "Doble Descarga",
    "GIGATON HAMMER":       "Martillo Gigatón",
    "COMEUPPANCE":          "Merecido",
    "AQUA CUTTER":          "Cortador Acuático",
    "BLAZING TORQUE":       "Par Motor Ígneo",
    "WICKED TORQUE":        "Par Motor Siniestro",
    "NOXIOUS TORQUE":       "Par Motor Tóxico",
    "COMBAT TORQUE":        "Par Motor Combate",
    "MAGICAL TORQUE":       "Par Motor Mágico",
    "BLOOD MOON":           "Luna Sangre",
    "MATCHA GOTCHA":        "Matcha Gotcha",
    "SYRUP BOMB":           "Bomba de Jarabe",
    "IVY CUDGEL":           "Garrote de Hiedra",
    "ELECTRO SHOT":         "Tiro Electro",
    "TERA STARSTORM":       "Tormenta Estelar Tera",
    "FICKLE BEAM":          "Haz Caprichoso",
    "BURNING BULWARK":      "Baluarte Ardiente",
    "THUNDERCLAP":          "Trueno Relámpago",
    "MIGHTY CLEAVE":        "Filo Poderoso",
    "TACHYON CUTTER":       "Taquión Cuchilla",
    "HARD PRESS":           "Presión Firme",
    "DRAGON CHEER":         "Ánimo Dragón",
    "ALLURING VOICE":       "Voz Seductora",
    "TEMPER FLARE":         "Destello de Rabia",
    "SUPERCELL SLAM":       "Golpe Supercélula",
    "PSYCHIC NOISE":        "Ruido Psíquico",
    "UPPER HAND":           "Mano Alta",
    "MALIGNANT CHAIN":      "Cadena Maligna",
}

# =====================================================================
# HABILIDADES - Nombres oficiales español
# =====================================================================
ABILITY_NAMES = {
    # Gen 3
    "STENCH":           "Hedor",
    "DRIZZLE":          "Llovizna",
    "SPEED BOOST":      "Motor Impulso",
    "BATTLE ARMOR":     "Armadura Batalla",
    "STURDY":           "Robustez",
    "DAMP":             "Humedad",
    "LIMBER":           "Flexibilidad",
    "SAND VEIL":        "Velo Arena",
    "STATIC":           "Estática",
    "VOLT ABSORB":        "Absorbe Electr.",
    "WATER ABSORB":     "Absorbe Agua",
    "OBLIVIOUS":        "Oblivio",
    "CLOUD NINE":       "Nublado",
    "COMPOUND EYES":    "Ojo Compuesto",
    "INSOMNIA":         "Insomnio",
    "COLOR CHANGE":     "Cambio Color",
    "IMMUNITY":         "Inmunidad",
    "FLASH FIRE":       "Absorbefuego",
    "SHIELD DUST":      "Polvo Escudo",
    "OWN TEMPO":        "Ritmo Propio",
    "SUCTION CUPS":     "Ventosas",
    "INTIMIDATE":       "Intimidación",
    "SHADOW TAG":       "Sombra Trampa",
    "ROUGH SKIN":       "Piel Tosca",
    "WONDER GUARD":     "Guardián",
    "LEVITATE":         "Levitación",
    "EFFECT SPORE":     "Espora Efecto",
    "SYNCHRONIZE":      "Sincronía",
    "CLEAR BODY":       "Cuerpo Puro",
    "NATURAL CURE":     "Curación Natural",
    "LIGHTNING ROD":    "Pararrayos",
    "SERENE GRACE":     "Don Serenidad",
    "SWIFT SWIM":       "Nado Rápido",
    "CHLOROPHYLL":      "Clorofila",
    "ILLUMINATE":       "Iluminar",
    "TRACE":            "Calcador",
    "HUGE POWER":       "Gran Potencia",
    "POISON POINT":     "Punto Venenoso",
    "INNER FOCUS":      "Foco Interno",
    "MAGMA ARMOR":      "Armadura Magma",
    "WATER VEIL":       "Velo Acuático",
    "MAGNET PULL":      "Magnetismo",
    "SOUNDPROOF":       "Insonorización",
    "RAIN DISH":        "Coge Lluvia",
    "SAND STREAM":      "Torrearena",
    "PRESSURE":         "Presión",
    "THICK FAT":        "Grueso Gordo",
    "EARLY BIRD":       "Madrugar",
    "FLAME BODY":       "Cuerpo Llama",
    "RUN AWAY":         "Fuga",
    "KEEN EYE":         "Visión Lince",
    "HYPER CUTTER":     "Hipercorte",
    "PICKUP":           "Recoger",
    "TRUANT":           "Holgazán",
    "HUSTLE":           "Entusiasmo",
    "CUTE CHARM":       "Encanto",
    "PLUS":             "Plus",
    "MINUS":            "Menos",
    "FORECAST":         "Predicción",
    "STICKY HOLD":      "Pegajoso",
    "SHED SKIN":        "Mudar",
    "GUTS":             "Agallas",
    "MARVEL SCALE":     "Escama Especial",
    "LIQUID OOZE":      "Rezuma",
    "OVERGROW":         "Espesura",
    "BLAZE":            "Mar Llamas",
    "TORRENT":          "Torrente",
    "SWARM":            "Enjambre",
    "ROCK HEAD":        "Roca Dura",
    "DROUGHT":          "Sequía",
    "ARENA TRAP":       "Trampa Arena",
    "VITAL SPIRIT":     "Espíritu Vital",
    "WHITE SMOKE":      "Humo Blanco",
    "PURE POWER":       "Pura Potencia",
    "SHELL ARMOR":      "Armadura Concha",
    "AIR LOCK":         "Éter",
    # Gen 4
    "TANGLED FEET":     "Pies Largos",
    "MOTOR DRIVE":      "Motor Eléctrico",
    "RIVALRY":          "Rivalidad",
    "STEADFAST":        "Constante",
    "SNOW CLOAK":       "Velo Nieve",
    "GLUTTONY":         "Gula",
    "ANGER POINT":      "Punto Ira",
    "UNBURDEN":         "Ligereza",
    "HEATPROOF":        "Ignífugo",
    "SIMPLE":           "Simpleza",
    "DRY SKIN":         "Piel Seca",
    "DOWNLOAD":         "Descarga",
    "IRON FIST":        "Puño Férreo",
    "POISON HEAL":      "Cura Veneno",
    "ADAPTABILITY":     "Adaptable",
    "SKILL LINK":       "Enlace Destreza",
    "HYDRATION":        "Hidratación",
    "SOLAR POWER":      "Energía Solar",
    "QUICK FEET":       "Pies Rápidos",
    "NORMALIZE":        "Normalizador",
    "SNIPER":           "Francotirador",
    "MAGIC GUARD":      "Guardia Mágica",
    "NO GUARD":         "Sin Guardia",
    "STALL":            "Remolón",
    "TECHNICIAN":       "Técnico",
    "LEAF GUARD":       "Guardia Hoja",
    "KLUTZ":            "Torpe",
    "MOLD BREAKER":     "Rompemoldes",
    "SUPER LUCK":       "Suerte",
    "AFTERMATH":        "Consecuencias",
    "ANTICIPATION":     "Anticipación",
    "FOREWARN":         "Premonición",
    "UNAWARE":          "Ignorante",
    "TINTED LENS":      "Lente de Color",
    "FILTER":           "Filtro",
    "SLOW START":       "Inicio Lento",
    "SCRAPPY":          "Revoltoso",
    "STORM DRAIN":      "Imán Agua",
    "ICE BODY":         "Cuerpo Hielo",
    "SOLID ROCK":       "Roca Sólida",
    "SNOW WARNING":     "Granizo",
    "HONEY GATHER":     "Colecta Miel",
    "FRISK":            "Cacheo",
    "RECKLESS":         "Temerario",
    "MULTITYPE":        "Multitipo",
    "FLOWER GIFT":      "Don Floral",
    "BAD DREAMS":       "Mal Sueño",
    # Gen 5
    "PICKPOCKET":       "Carterista",
    "SHEER FORCE":      "Fuerza Bruta",
    "CONTRARY":         "Contrario",
    "UNNERVE":          "Tensión",
    "DEFIANT":          "Desafío",
    "DEFEATIST":        "Derrotista",
    "CURSED BODY":      "Cuerpo Maldito",
    "HEALER":           "Sanador",
    "FRIEND GUARD":     "Guardia Amigo",
    "WEAK ARMOR":       "Armadura Frágil",
    "HEAVY METAL":      "Metal Pesado",
    "LIGHT METAL":      "Metal Ligero",
    "MULTISCALE":       "Multiescama",
    "TOXIC BOOST":      "Potencia Tóxica",
    "FLARE BOOST":       "Impulso Ardiente",
    "HARVEST":          "Cosecha",
    "TELEPATHY":        "Telepatía",
    "MOODY":            "Variable",
    "OVERCOAT":         "Sobretodo",
    "POISON TOUCH":     "Toque Venenoso",
    "REGENERATOR":      "Regeneración",
    "BIG PECKS":        "Pectorales",
    "SAND RUSH":        "Ímpetu Arena",
    "WONDER SKIN":      "Piel Mística",
    "ANALYTIC":         "Analítico",
    "ILLUSION":         "Ilusión",
    "IMPOSTER":         "Impostor",
    "INFILTRATOR":      "Infiltrador",
    "MUMMY":            "Momia",
    "MOXIE":            "Agresividad",
    "JUSTIFIED":        "Templado",
    "RATTLED":          "Turbador",
    "MAGIC BOUNCE":     "Rebote Mágico",
    "SAP SIPPER":       "Come Hierba",
    "PRANKSTER":        "Bromista",
    "SAND FORCE":       "Fuerza Arena",
    "IRON BARBS":       "Puas Hierro",
    "ZEN MODE":         "Modo Zen",
    "VICTORY STAR":      "Estr. Victoria",
    "TURBOBLAZE":       "Turboflama",
    "TERAVOLT":         "Teravoltio",
    # Gen 6
    "AROMA VEIL":       "Velo Aromático",
    "FLOWER VEIL":      "Velo Floral",
    "CHEEK POUCH":      "Bolsa Carrillo",
    "PROTEAN":          "Multicolor",
    "FUR COAT":         "Piel Peluda",
    "MAGICIAN":         "Mago",
    "BULLETPROOF":      "Antibalas",
    "COMPETITIVE":      "Competitivo",
    "STRONG JAW":       "Mandíbula Fuerte",
    "REFRIGERATE":      "Frigorífico",
    "SWEET VEIL":       "Velo Dulce",
    "STANCE CHANGE":    "Cambio Forma",
    "GALE WINGS":       "Alas Vendaval",
    "MEGA LAUNCHER":    "Megalanzador",
    "GRASS PELT":       "Piel Herbácea",
    "SYMBIOSIS":        "Simbiosis",
    "TOUGH CLAWS":      "Garras Fuertes",
    "PIXILATE":         "Feérico",
    "GOOEY":            "Viscoso",
    "AERILATE":         "Viento",
    "PARENTAL BOND":    "Lazo Parental",
    "DARK AURA":        "Aura Oscura",
    "FAIRY AURA":       "Aura Feérica",
    "AURA BREAK":       "Antiura",
    "PRIMORDIAL SEA":   "Mar Primigenio",
    "DESOLATE LAND":    "Tierra Desolada",
    "DELTA STREAM":     "Delta Corriente",
    # Gen 7
    "STAKEOUT":         "Acecho",
    "WATER BUBBLE":     "Burbuja Agua",
    "STEELWORKER":      "Metalúrgico",
    "BERSERK":          "Berserker",
    "SLUSH RUSH":       "Ímpetu Nieve",
    "LONG REACH":       "Largo Alcance",
    "LIQUID VOICE":     "Voz Acuática",
    "TRIAGE":           "Triaje",
    "GALVANIZE":        "Galvanización",
    "SURGE SURFER":     "Surf Eléctrico",
    "SCHOOLING":        "Cardumen",
    "DISGUISE":         "Disfraz",
    "BATTLE BOND":      "Lazo de Combate",
    "POWER CONSTRUCT":  "Construir Fuerza",
    "CORROSION":        "Corrosión",
    "COMATOSE":         "Comatoso",
    "QUEENLY MAJESTY":  "Majestad Regia",
    "INNARDS OUT":      "Reflejar Daño",
    "DANCER":           "Bailarín",
    "BATTERY":          "Batería",
    "FLUFFY":           "Pelusa",
    "DAZZLING":         "Deslumbrante",
    "SOUL-HEART":       "Alma Corazón",
    "TANGLING HAIR":    "Cabello Enredado",
    "RECEIVER":         "Receptor",
    "POWER OF ALCHEMY": "Poder Alquimia",
    "BEAST BOOST":      "Ultraimpulso",
    "RKS SYSTEM":       "Sistema RKS",
    "ELECTRIC SURGE":   "Electricidad",
    "PSYCHIC SURGE":    "Psíquico",
    "MISTY SURGE":      "Niebla",
    "GRASSY SURGE":     "Hierba",
    "FULL METAL BODY":  "Cuerpo Férreo",
    "SHADOW SHIELD":    "Escudo Sombra",
    "PRISM ARMOR":      "Armadura Prisma",
    "NEUROFORCE":       "Neurofuerza",
    # Gen 8
    "INTREPID SWORD":   "Espada Valiente",
    "DAUNTLESS SHIELD": "Escudo Constante",
    "BALL FETCH":       "Busca Bola",
    "COTTON DOWN":      "Plumón Algodón",
    "PROPELLER TAIL":   "Cola Hélice",
    "MIRROR ARMOR":     "Armadura Espejo",
    "GULP MISSILE":     "Misil Tragado",
    "STALWART":         "Valiente",
    "STEAM ENGINE":     "Motor Vapor",
    "PUNK ROCK":        "Punk Rock",
    "SAND SPIT":        "Escupir Arena",
    "ICE SCALES":       "Escamas Hielo",
    "RIPEN":            "Madurar",
    "ICE FACE":         "Cara Hielo",
    "POWER SPOT":       "Punto Potencia",
    "MIMICRY":          "Mimetismo",
    "SCREEN CLEANER":   "Rompe Pantallas",
    "STEELY SPIRIT":    "Espíritu Férreo",
    "PERISH BODY":      "Cuerpo Mortal",
    "WANDERING SPIRIT": "Espíritu Errante",
    "GORILLA TACTICS":  "Tácticas Gorila",
    "NEUTRALIZING GAS":   "Gas Neutraliz.",
    "PASTEL VEIL":      "Velo Pastel",
    "HUNGER SWITCH":    "Alternancia",
    "QUICK DRAW":         "Saque Rápido",
    "UNSEEN FIST":      "Puño Invisible",
    "CURIOUS MEDICINE": "Medicina Curiosa",
    "TRANSISTOR":       "Transistor",
    "DRAGONS MAW":      "Fauces Dragón",
    "CHILLING NEIGH":   "Relincho Frío",
    "GRIM NEIGH":       "Relincho Sombrío",
    "AS ONE (ICE RIDER)": "Ambos Poderes",
    "AS ONE (SHADOW RIDER)": "Ambos Poderes",
    # Gen 9
    "COMMANDER":        "Comandante",
    "ELECTROMORPHOSIS": "Electromorfosis",
    "PROTOSYNTHESIS":   "Protoestasis",
    "QUARK DRIVE":      "Cuark Motor",
    "GOOD AS GOLD":     "Oro Puro",
    "VESSEL OF RUIN":   "Vasija Ruinosa",
    "SWORD OF RUIN":    "Espada Ruinosa",
    "TABLETS OF RUIN":  "Tableta Ruinosa",
    "BEADS OF RUIN":    "Cuentas Ruinosas",
    "ORICHALCUM PULSE": "Pulso Oricalco",
    "HADRON ENGINE":    "Motor Hadrón",
    "OPPORTUNIST":      "Oportunista",
    "CUD CHEW":         "Rumia",
    "SHARPNESS":        "Filo",
    "SUPREME OVERLORD": "Sumo Señor",
    "COSTAR":           "Coestrella",
    "TOXIC DEBRIS":       "Escombros Tox.",
    "ARMOR TAIL":       "Cola Blindada",
    "EARTH EATER":      "Come Tierra",
    "WIND RIDER":         "Jinete Viento",
    "GUARD DOG":        "Perro Guardián",
    "ROCKY PAYLOAD":    "Carga Rocosa",
    "WIND POWER":       "Poder del Viento",
    "ZERO TO HERO":     "De Cero a Héroe",
    "EMBODY ASPECT (TEAL)": "Encarnar Aspecto",
    "EMBODY ASPECT (HEARTHFLAME)": "Encarnar Aspecto",
    "EMBODY ASPECT (WELLSPRING)": "Encarnar Aspecto",
    "EMBODY ASPECT (CORNERSTONE)": "Encarnar Aspecto",
    "TERA SHIFT":       "Tera Cambio",
    "TERA SHELL":       "Tera Caparazón",
    "TERAFORM ZERO":    "Teraforma Cero",
    "POISON PUPPETEER":   "Titerero Veneno",
}

# =====================================================================
# OBJETOS - Nombres oficiales español (selección principal)
# =====================================================================
ITEM_NAMES = {
    # Pokéballs
    "POKE BALL":        "Poké Ball",
    "GREAT BALL":       "Super Ball",
    "ULTRA BALL":       "Ultra Ball",
    "MASTER BALL":      "Master Ball",
    "SAFARI BALL":      "Safari Ball",
    "LEVEL BALL":       "Level Ball",
    "LURE BALL":        "Señuelo Ball",
    "MOON BALL":        "Luna Ball",
    "FRIEND BALL":      "Amistad Ball",
    "LOVE BALL":        "Amor Ball",
    "HEAVY BALL":       "Peso Ball",
    "FAST BALL":        "Rápida Ball",
    "SPORT BALL":       "Sport Ball",
    "PREMIER BALL":     "Honor Ball",
    "REPEAT BALL":      "Repetición Ball",
    "TIMER BALL":       "Tiempo Ball",
    "NEST BALL":        "Nido Ball",
    "NET BALL":         "Red Ball",
    "DIVE BALL":        "Buceo Ball",
    "LUXURY BALL":      "Lujo Ball",
    "HEAL BALL":        "Cura Ball",
    "QUICK BALL":       "Rapaz Ball",
    "DUSK BALL":        "Ocaso Ball",
    "CHERISH BALL":     "Lazo Ball",
    "PARK BALL":        "Parque Ball",
    "DREAM BALL":       "Sueño Ball",
    "BEAST BALL":       "Ultra Ball",
    "STRANGE BALL":     "Extraña Ball",
    # Pociones
    "POTION":           "Poción",
    "ANTIDOTE":         "Antídoto",
    "BURN HEAL":        "Cura Quemadura",
    "ICE HEAL":         "Cura Congelación",
    "AWAKENING":        "Despertar",
    "PARLYZ HEAL":      "Cura Parálisis",
    "FULL RESTORE":     "Restauración Total",
    "MAX POTION":       "Súper Poción",
    "HYPER POTION":     "Hiperpoción",
    "SUPER POTION":     "Superpoción",
    "FULL HEAL":        "Cura Total",
    "REVIVE":           "Revivir",
    "MAX REVIVE":       "Revivir Máx.",
    "FRESH WATER":      "Agua Fresca",
    "SODA POP":         "Refresco",
    "LEMONADE":         "Limonada",
    "MOOMOO MILK":      "Leche MuMu",
    "ENERGY POWDER":    "Polvo Energía",
    "ENERGY ROOT":      "Raíz Energía",
    "HEAL POWDER":      "Polvo Curación",
    "REVIVAL HERB":     "Hierba Revivir",
    "ETHER":            "Éter",
    "MAX ETHER":        "Éter Máx.",
    "ELIXIR":           "Elixir",
    "MAX ELIXIR":       "Elixir Máx.",
    "LAVA COOKIE":      "Galleta Lava",
    "BERRY JUICE":      "Zumo Baya",
    "SACRED ASH":       "Ceniza Sagrada",
    # Vitaminas / Potenciadores
    "HP UP":            "Vitamina PS",
    "PROTEIN":          "Proteína",
    "IRON":             "Hierro",
    "CARBOS":           "Carbono",
    "CALCIUM":          "Calcio",
    "RARE CANDY":       "Caramelo Raro",
    "PP UP":            "PP Plus",
    "ZINC":             "Zinc",
    "PP MAX":           "PP Máx.",
    # Objetos de evolución
    "FIRE STONE":       "Piedra Fuego",
    "WATER STONE":      "Piedra Agua",
    "THUNDER STONE":    "Piedra Trueno",
    "LEAF STONE":       "Piedra Hoja",
    "MOON STONE":       "Piedra Lunar",
    "SUN STONE":        "Piedra Solar",
    "SHINY STONE":      "Piedra Brillante",
    "DUSK STONE":       "Piedra Noche",
    "DAWN STONE":       "Piedra Alba",
    "OVAL STONE":       "Piedra Oval",
    "LINK CABLE":       "Cable Link",
    "KINGS ROCK":       "Roca del Rey",
    "METAL COAT":       "Revestimiento Metálico",
    "DRAGON SCALE":     "Escama Dragón",
    "UPGRADE":          "Mejora",
    "DUBIOUS DISC":     "Disco Raro",
    "MAGMARIZER":       "Magmarizador",
    "ELECTIRIZER":      "Electrizador",
    "PROTECTOR":        "Protector",
    "REAPER CLOTH":     "Tela Segadora",
    "WHIPPED DREAM":    "Sueño Batido",
    "SACHET":           "Saquito",
    "ICE STONE":        "Piedra Hielo",
    # MT/MO
    "TM01":  "MT01",  "TM02":  "MT02",  "TM03":  "MT03",  "TM04":  "MT04",
    "TM05":  "MT05",  "TM06":  "MT06",  "TM07":  "MT07",  "TM08":  "MT08",
    "TM09":  "MT09",  "TM10":  "MT10",  "TM11":  "MT11",  "TM12":  "MT12",
    "TM13":  "MT13",  "TM14":  "MT14",  "TM15":  "MT15",  "TM16":  "MT16",
    "TM17":  "MT17",  "TM18":  "MT18",  "TM19":  "MT19",  "TM20":  "MT20",
    "TM21":  "MT21",  "TM22":  "MT22",  "TM23":  "MT23",  "TM24":  "MT24",
    "TM25":  "MT25",  "TM26":  "MT26",  "TM27":  "MT27",  "TM28":  "MT28",
    "TM29":  "MT29",  "TM30":  "MT30",  "TM31":  "MT31",  "TM32":  "MT32",
    "TM33":  "MT33",  "TM34":  "MT34",  "TM35":  "MT35",  "TM36":  "MT36",
    "TM37":  "MT37",  "TM38":  "MT38",  "TM39":  "MT39",  "TM40":  "MT40",
    "TM41":  "MT41",  "TM42":  "MT42",  "TM43":  "MT43",  "TM44":  "MT44",
    "TM45":  "MT45",  "TM46":  "MT46",  "TM47":  "MT47",  "TM48":  "MT48",
    "TM49":  "MT49",  "TM50":  "MT50",  "TM51":  "MT51",  "TM52":  "MT52",
    "TM53":  "MT53",  "TM54":  "MT54",  "TM55":  "MT55",  "TM56":  "MT56",
    "TM57":  "MT57",  "TM58":  "MT58",  "TM59":  "MT59",  "TM60":  "MT60",
    "TM61":  "MT61",  "TM62":  "MT62",  "TM63":  "MT63",  "TM64":  "MT64",
    "TM65":  "MT65",  "TM66":  "MT66",  "TM67":  "MT67",  "TM68":  "MT68",
    "TM69":  "MT69",  "TM70":  "MT70",  "TM71":  "MT71",  "TM72":  "MT72",
    "TM73":  "MT73",  "TM74":  "MT74",  "TM75":  "MT75",  "TM76":  "MT76",
    "TM77":  "MT77",  "TM78":  "MT78",  "TM79":  "MT79",  "TM80":  "MT80",
    "TM81":  "MT81",  "TM82":  "MT82",  "TM83":  "MT83",  "TM84":  "MT84",
    "TM85":  "MT85",  "TM86":  "MT86",  "TM87":  "MT87",  "TM88":  "MT88",
    "TM89":  "MT89",  "TM90":  "MT90",  "TM91":  "MT91",  "TM92":  "MT92",
    "TM93":  "MT93",  "TM94":  "MT94",  "TM95":  "MT95",  "TM96":  "MT96",
    "TM97":  "MT97",  "TM98":  "MT98",  "TM99":  "MT99",  "TM100": "MT100",
    "HM01":  "MO01",  "HM02":  "MO02",  "HM03":  "MO03",  "HM04":  "MO04",
    "HM05":  "MO05",  "HM06":  "MO06",  "HM07":  "MO07",  "HM08":  "MO08",
    # Objetos held (selección)
    "CHOICE BAND":      "Banda Elegida",
    "CHOICE SCARF":     "Pañuelo Elegido",
    "CHOICE SPECS":     "Gafas Elegidas",
    "LIFE ORB":         "Orbe Vida",
    "FOCUS SASH":       "Cinto Fuerza",
    "LEFTOVERS":        "Sobras",
    "ROCKY HELMET":     "Casco Rocoso",
    "EVIOLITE":         "Evolucionita",
    "ASSAULT VEST":     "Chaleco Asalto",
    "HEAVY-DUTY BOOTS": "Botas Pesadas",
    "CLEAR AMULET":     "Amuleto Puro",
    "COVERT CLOAK":     "Capa Encubierta",
    "LOADED DICE":      "Dado Cargado",
    "BOOSTER ENERGY":    "Energía Plus",
    "BLACK GLASSES":    "Gafas Negras",
    "CHARCOAL":         "Carbón",
    "MYSTIC WATER":     "Agua Mística",
    "MIRACLE SEED":     "Semilla Milagro",
    "SOFT SAND":        "Arena Fina",
    "HARD STONE":       "Roca Dura",
    "SILVER POWDER":    "Polvo Plata",
    "TWISTED SPOON":    "Cuchara Torcida",
    "SHARP BEAK":       "Pico Agudo",
    "SPELL TAG":        "Etiqueta Hechizo",
    "METAL COAT":       "Revestimiento Metálico",
    "SILK SCARF":       "Pañuelo Seda",
    "BLACK BELT":       "Cinturón Negro",
    "MAGNET":           "Imán",
    "POISON BARB":      "Púa Venenosa",
    "NEVER-MELT ICE":   "Hielo Eterno",
    "DRAGON FANG":      "Colmillo Dragón",
    "AMULET COIN":      "Moneda Amuleto",
    "CLEANSE TAG":      "Etiqueta Pura",
    "SMOKE BALL":       "Bola de Humo",
    "SOOTHE BELL":      "Campana Amistad",
    "MENTAL HERB":      "Hierba Mental",
    "WHITE HERB":       "Hierba Blanca",
    "POWER HERB":       "Hierba Potencia",
    "SCOPE LENS":       "Lupa Ámbito",
    "ZOOM LENS":        "Lente de Aumento",
    "WIDE LENS":        "Lupa Amplia",
    "MUSCLE BAND":      "Banda Músculo",
    "WISE GLASSES":     "Gafas Sabias",
    "METRONOME":        "Metrónomo",
    "EXPERT BELT":      "Cinturón Experto",
    "FLAME ORB":        "Orbe Llama",
    "TOXIC ORB":        "Orbe Tóxico",
    "LIGHT BALL":       "Bola Luz",
    "THICK CLUB":       "Porra Pesada",
    "LUCKY PUNCH":      "Puño Suerte",
    "MACHO BRACE":      "Pulsera Fuerte",
    "POWER WEIGHT":     "Peso Potencia",
    "POWER BRACER":     "Brazal Potencia",
    "POWER BELT":       "Cinturón Potencia",
    "POWER LENS":       "Lente Potencia",
    "POWER BAND":       "Banda Potencia",
    "POWER ANKLET":     "Tobillera Potencia",
    "EXP. SHARE":       "Repartir Exp.",
    "EXP. ALL":         "Exp. para Todos",
    "LUCKY EGG":        "Huevo Suerte",
    "SHELL BELL":       "Concha Amulet",
    "BIG ROOT":         "Raíz Grande",
    "TERRAIN EXTENDER":  "Extens. Terreno",
    "PROTECTIVE PADS":  "Almohadillas",
    "ROOM SERVICE":     "Servicio Habitación",
    "MIRROR HERB":      "Hierba Espejo",
    "PUNCHING GLOVE":   "Guante de Boxeo",
    # Bayas (selección básica)
    "CHERI BERRY":      "Baya Cheri",
    "CHESTO BERRY":     "Baya Zidra",
    "PECHA BERRY":      "Baya Melon",
    "RAWST BERRY":      "Baya Rawst",
    "ASPEAR BERRY":     "Baya Aspear",
    "LEPPA BERRY":      "Baya Leppa",
    "ORAN BERRY":       "Baya Oran",
    "PERSIM BERRY":     "Baya Persim",
    "LUM BERRY":        "Baya Lum",
    "SITRUS BERRY":     "Baya Zidra",
    "FIGY BERRY":       "Baya Figy",
    "WIKI BERRY":       "Baya Wiki",
    "MAGO BERRY":       "Baya Mago",
    "AGUAV BERRY":      "Baya Aguav",
    "IAPAPA BERRY":     "Baya Iapapa",
    "RAZZ BERRY":       "Baya Frambu",
    "BLUK BERRY":       "Baya Ment",
    "NANAB BERRY":      "Baya Nanab",
    "WEPEAR BERRY":     "Baya Peral",
    "PINAP BERRY":      "Baya Piña",
    "POMEG BERRY":      "Baya Grana",
    "KELPSY BERRY":     "Baya Kelpsy",
    "QUALOT BERRY":     "Baya Qualot",
    "HONDEW BERRY":     "Baya Hondew",
    "GREPA BERRY":      "Baya Grepa",
    "TAMATO BERRY":     "Baya Tamato",
    "CORNN BERRY":      "Baya Maizal",
    "MAGOST BERRY":     "Baya Magost",
    "RABUTA BERRY":     "Baya Rabuta",
    "NOMEL BERRY":      "Baya Nomel",
    "SPELON BERRY":     "Baya Spelon",
    "PAMTRE BERRY":     "Baya Pamtre",
    "WATMEL BERRY":     "Baya Sandía",
    "DURIN BERRY":      "Baya Durin",
    "BELUE BERRY":      "Baya Belue",
    "OCCA BERRY":       "Baya Occa",
    "PASSHO BERRY":     "Baya Passho",
    "WACAN BERRY":      "Baya Wacan",
    "RINDO BERRY":      "Baya Rindo",
    "YACHE BERRY":      "Baya Yache",
    "CHOPLE BERRY":     "Baya Chople",
    "KEBIA BERRY":      "Baya Kebia",
    "SHUCA BERRY":      "Baya Shuca",
    "COBA BERRY":       "Baya Coba",
    "PAYAPA BERRY":     "Baya Payapa",
    "TANGA BERRY":      "Baya Tanga",
    "CHARTI BERRY":     "Baya Charti",
    "KASIB BERRY":      "Baya Kasib",
    "HABAN BERRY":      "Baya Haban",
    "COLBUR BERRY":     "Baya Colbur",
    "BABIRI BERRY":     "Baya Babiri",
    "CHILAN BERRY":     "Baya Chilan",
    "LIECHI BERRY":     "Baya Liechi",
    "GANLON BERRY":     "Baya Ganlon",
    "SALAC BERRY":      "Baya Salac",
    "PETAYA BERRY":     "Baya Petaya",
    "APICOT BERRY":     "Baya Apicot",
    "LANSAT BERRY":     "Baya Lansat",
    "STARF BERRY":      "Baya Starf",
    "ENIGMA BERRY":     "Baya Enigma",
    "MICLE BERRY":      "Baya Micle",
    "CUSTAP BERRY":     "Baya Custap",
    "JABOCA BERRY":     "Baya Jaboca",
    "ROWAP BERRY":      "Baya Rowap",
    "ROSELI BERRY":     "Baya Roseli",
    "KEE BERRY":        "Baya Kee",
    "MARANGA BERRY":    "Baya Maranga",
}

# =====================================================================
# FUNCIONES DE APLICACIÓN
# =====================================================================

def backup_file(filepath):
    """Crea copia de seguridad del fichero."""
    backup = filepath + ".bak_" + datetime.now().strftime("%Y%m%d_%H%M%S")
    shutil.copy2(filepath, backup)
    return backup

def apply_move_names(filepath, translations, dry_run=False):
    """Reemplaza nombres en COMPOUND_STRING("NAME") en moves_info.h."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    count = 0
    for en, es in translations.items():
        pattern = r'(\.name\s*=\s*COMPOUND_STRING\s*\(\s*")' + re.escape(en) + r'("\s*\))'
        replacement = r'\g<1>' + es + r'\g<2>'
        new_content, n = re.subn(pattern, replacement, content)
        if n > 0:
            count += n
            content = new_content

    if not dry_run and count > 0:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

    return count

def apply_ability_names(filepath, translations, dry_run=False):
    """Reemplaza nombres de habilidades en _(\"NAME\")."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    count = 0
    for en, es in translations.items():
        # abilities.h usa .name = _("NAME")
        pattern = r'(\.name\s*=\s*_\s*\(\s*")' + re.escape(en) + r'("\s*\))'
        replacement = r'\g<1>' + es + r'\g<2>'
        new_content, n = re.subn(pattern, replacement, content)
        if n > 0:
            count += n
            content = new_content

    if not dry_run and count > 0:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

    return count

def apply_item_names(filepath, translations, dry_run=False):
    """Reemplaza nombres de objetos en ITEM_NAME("NAME")."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    count = 0
    for en, es in translations.items():
        # items.h usa ITEM_NAME("NAME") o COMPOUND_STRING("NAME")
        for macro in ["ITEM_NAME", "COMPOUND_STRING"]:
            pattern = r'(' + macro + r'\s*\(\s*")' + re.escape(en) + r'("\s*\))'
            replacement = r'\g<1>' + es + r'\g<2>'
            new_content, n = re.subn(pattern, replacement, content)
            if n > 0:
                count += n
                content = new_content

    if not dry_run and count > 0:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

    return count

def main():
    project_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    dry_run = "--dry-run" in sys.argv

    if dry_run:
        print("[MODO SIMULACIÓN - No se escriben cambios]")

    moves_file    = os.path.join(project_dir, "src", "data", "moves_info.h")
    abilities_file = os.path.join(project_dir, "src", "data", "abilities.h")
    items_file    = os.path.join(project_dir, "src", "data", "items.h")

    print("=" * 60)
    print("  TRADUCCIÓN FASE 1 - Pokémon Heart & Soul (HNS)")
    print("=" * 60)

    for label, filepath, func, trans in [
        ("Movimientos (nombres)",  moves_file,     apply_move_names,    MOVE_NAMES),
        ("Habilidades (nombres)",  abilities_file,  apply_ability_names, ABILITY_NAMES),
        ("Objetos (nombres)",      items_file,      apply_item_names,    ITEM_NAMES),
    ]:
        if not os.path.exists(filepath):
            print(f"\n  [SKIP] {label}: {filepath} no encontrado")
            continue

        if not dry_run:
            bak = backup_file(filepath)
            print(f"\n  [BAK] {os.path.basename(bak)}")

        n = func(filepath, trans, dry_run=dry_run)
        status = "OK" if n > 0 else "SIN CAMBIOS"
        print(f"  [{status}] {label}: {n} sustituciones")

    print("\n" + "=" * 60)
    print("  LISTO - Ejecuta 'make modern' para compilar")
    print("=" * 60)

if __name__ == "__main__":
    main()
