VermilionCity_Mart_hns_MapScripts::
	.byte 0

VermilionCity_Mart_EventScript_BirdMan::
	msgbox VermilionMart_Text_SuperNerd, MSGBOX_NPC
	end

VermilionCity_Mart_EventScript_Woman::
	msgbox VermilionMart_Text_Beauty, MSGBOX_NPC
	end

VermilionMart_Text_SuperNerd:
	.string "El TEAM ROCKET ya no está\n"
	.string "en KANTO.\p"
	.string "Solo con eso ya soy feliz.$"

VermilionMart_Text_Beauty:
	.string "Estoy pensando en ir de compras\n"
	.string "a CIUDAD AZAFRÁN.$"
