Route20_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route20_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

Route20_EventScript_ShellBell::
	finditem ITEM_BLASTOISINITE
	end

Route20_OnTransition:
	callnative SetTimeBasedEncounters
	end

Route20_EventScript_Nicole::
	trainerbattle_single TRAINER_NICOLE_HNS, Route20_Text_SwimmerfNicoleSeen, Route20_Text_SwimmerfNicoleBeaten, Route20_EventScript_RegisterNicole
	specialvar VAR_RESULT, ShouldTryRematchBattle
	goto_if_eq VAR_RESULT, TRUE, Route20_EventScript_RematchNicole
	msgbox Route20_Text_SwimmerfNicoleAfterBattle, MSGBOX_AUTOCLOSE
	end

Route20_EventScript_RegisterNicole::
	special PlayerFaceTrainerAfterBattle
	waitmovement 0
	msgbox Route20_Text_NicoleRegister, MSGBOX_DEFAULT
	register_matchcall TRAINER_NICOLE_HNS
	release
	end

Route20_EventScript_RematchNicole::
	trainerbattle_rematch TRAINER_NICOLE_HNS, Route20_Text_NicoleRematchIntro, Route20_Text_NicoleRematchDefeat
	msgbox Route20_Text_NicolePostRematch, MSGBOX_AUTOCLOSE
	goto_if_defeated TRAINER_NICOLE_2_HNS, Route20_EventScript_RematchNicoleTryGiveItem
	end

Route20_EventScript_RematchNicoleTryGiveItem::
	checkitem ITEM_HEART_SCALE
	goto_if_eq VAR_RESULT, TRUE, Common_EventScript_NoOp
	giveitem ITEM_HEART_SCALE
	closemessage
	end

Route20_EventScript_Lori::
	trainerbattle_single TRAINER_LORI_HNS, Route20_Text_SwimmerfLoriSeen, Route20_Text_SwimmerfLoriBeaten
	msgbox Route20_Text_SwimmerfLoriAfterBattle, MSGBOX_AUTOCLOSE
	end	

Route20_EventScript_Cameron::
	trainerbattle_single TRAINER_CAMERON_HNS, Route20_Text_SwimmermCameronSeen, Route20_Text_SwimmermCameronBeaten
	msgbox Route20_Text_SwimmermCameronAfterBattle, MSGBOX_AUTOCLOSE
	end	

Route20_EventScript_SeafoamSign::
	msgbox Route20_Text_SeafoamSign, MSGBOX_SIGN
	end

Route20_EventScript_GymSign::
	msgbox Route20_Text_CinnabarIsland_GymUnusedSign, MSGBOX_SIGN
	end

Route20_EventScript_Seel::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_SEEL, CRY_MODE_NORMAL
	msgbox Route20_Text_Seel, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route20_EventScript_Dewgong::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_DEWGONG, CRY_MODE_NORMAL
	msgbox Route20_Text_Dewgong, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route20_EventScript_Dennis::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MAGIKARP, CRY_MODE_NORMAL
	msgbox Route20_Text_Dennis, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route20_EventScript_Headlocker::
	lock
	faceplayer
	msgbox Route20_Text_Headlocker, MSGBOX_DEFAULT
	closemessage
	turnobject LOCALID_ROUTE20_HEADLOCKER, DIR_SOUTH
	release
	end

Route20_Text_Dennis:
	.string "DENNIS: SHAAAAAAAA!$"

Route20_Text_Headlocker:
	.string "Hay un POKéMON raro en esta\n"
	.string "ruta.\p"
	.string "A veces lleva un objeto evolutivo\n"
	.string "raro.\p"
	.string "¡Eso es doblemente raro!\p"
	.string "Debo completar mi POKéDEX, ¡llevo\n"
	.string "horas pescando aquí!$"

Route20_Text_Seel:
	.string "SEEL: Seel seel!$"

Route20_Text_Dewgong:
	.string "DEWGONG: Goooong!$"

Route20_Text_SeafoamSign:
	.string "ISLAS ESPUMA$"

Route20_Text_NicoleRegister:
	.string "¡Tu POKéMON nada muy rápido!\n"
	.string "¡Dame tu número!$"

Route20_Text_NicoleRematchIntro:
	.string "¡Tanto nadar ha fortalecido a mi\n"
	.string "POKéMON! ¡Combatamos!$"

Route20_Text_NicoleRematchDefeat:
	.string "La corriente me arrastra otra vez…$"

Route20_Text_NicolePostRematch:
	.string "¡Gane o pierda, mi POKéMON y yo\n"
	.string "nos ponemos en forma!$"

Route20_Text_SwimmerfNicoleSeen:
	.string "En el agua me siento muy ligera.$"

Route20_Text_SwimmerfNicoleBeaten:
	.string "¡Oh, no!$"

Route20_Text_SwimmerfNicoleAfterBattle:
	.string "Nadar ejercita todo el cuerpo.\p"
	.string "Es muy bueno para ti.$"

Route20_Text_SwimmerfLoriSeen:
	.string "¡Qué colección de MEDALLAS tan\n"
	.string "impresionante! ¡Combatamos!$"

Route20_Text_SwimmerfLoriBeaten:
	.string "¡No!$"

Route20_Text_SwimmerfLoriAfterBattle:
	.string "SURF ya no es el único movimiento\n"
	.string "MO que se usa en el agua.$"

Route20_Text_SwimmermCameronSeen:
	.string "Supongo que es imposible nadar\n"
	.string "hasta JOHTO.$"

Route20_Text_SwimmermCameronBeaten:
	.string "¡Ay!$"

Route20_Text_SwimmermCameronAfterBattle:
	.string "Además del mar, también nado en\n"
	.string "estanques y ríos.$"

Route20_Text_CinnabarIsland_GymUnusedSign:
	.string "¿Qué pone en este cartel?\p"
	.string "LÍDER DEL GIMNASIO CANELA: BLAINE$"
