CableClub_Text_WelcomeWhichCableClubService:
	.string "Bienvenido al CLUB CABLE POKéMON.\p"
	.string "¿Qué servicio quieres utilizar?$"

CableClub_Text_WhichService:
	.string "¿Qué servicio quieres utilizar?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Intercambia POKéMON con alguien\n"
	.string "mediante un cable Game Link GBA.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Combate con otro ENTRENADOR usando\n"
	.string "un cable Game Link GBA.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Usa el RINCÓN DE REGISTROS mediante\n"
	.string "un cable Game Link GBA.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Cierra este menú.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Para un COMBATE DOBLE necesitas\n"
	.string "al menos dos POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Para intercambiar debes llevar\n"
	.string "al menos dos POKéMON.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "No puedes intercambiar un POKéMON\n"
	.string "que lleve la BAYA {STR_VAR_1}.$"

gText_PleaseWaitForLink::
	.string "Espera, por favor.\n"
	.string "… … Botón B: Cancelar$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Cuando todos estén preparados…\n"
	.string "Botón A: Confirmar\l"
	.string "Botón B: Cancelar$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Conectar con {STR_VAR_1} jugadores.\n"
	.string "Botón A: Confirmar\l"
	.string "Botón B: Cancelar$"

gText_AwaitingLinkup::
	.string "Esperando conexión…\n"
	.string "… … Botón B: Cancelar$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Debes guardar antes de conectarte.\n"
	.string "¿Quieres guardar?$"

CableClub_Text_PleaseEnter:
	.string "Adelante, por favor.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Te acompañaré hasta tu sala.$"

Text_SomeoneIsNotReadyToLink:
	.string "Alguien no está preparado.\p"
	.string "Vuelve cuando todos estén listos.$"

Text_LinkErrorPleaseReset:
	.string "Ha ocurrido un error de conexión…\n"
	.string "Reinicia y vuelve a intentarlo.$"

Text_PlayersMadeDifferentSelections:
	.string "Los jugadores conectados han hecho\n"
	.string "selecciones distintas.$"

CableClub_Text_PleaseVisitAgain:
	.string "¡Esperamos volver a verte!$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "El número de participantes\n"
	.string "no es correcto.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "No admite {STR_VAR_1} jugadores\n"
	.string "al modo COMBATE INDIVIDUAL.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "No admite {STR_VAR_1} jugadores\n"
	.string "al modo COMBATE DOBLE.$"

CableClub_Text_NeedFourPlayers:
	.string "Este modo de combate requiere\n"
	.string "cuatro jugadores.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Comprueba cuántos jugadores hay\n"
	.string "y vuelve a empezar.$"

Text_TerminateLinkConfirmation:
	.string "La conexión terminará si sales.\n"
	.string "¿Estás de acuerdo?$"

Text_TerminateLinkPleaseWait:
	.string "Cerrando la conexión…\n"
	.string "Te acompañaremos fuera de la sala.\l"
	.string "Espera, por favor.$"

CableClub_Text_TooBusyToNotice:
	.string "Este ENTRENADOR está demasiado\n"
	.string "ocupado para darse cuenta…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "¡Bien! ¡Has visto la FICHA de\n"
	.string "ENTRENADOR de {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "¡Has visto la FICHA de ENTRENADOR\n"
	.string "de {STR_VAR_1}!\p"
	.string "¡Es una ficha {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Ocupa tu puesto y comienza\n"
	.string "el combate.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Toma asiento y comienza\n"
	.string "el intercambio.$"

RecordCorner_Text_ThanksForComing:
	.string "Gracias por venir.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Se sobrescribirán los datos\n"
	.string "de la FICHA de ENTRENADOR.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "¡Espero volver a verte!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Lo siento muchísimo.\p"
	.string "Aún no podemos intercambiar con\n"
	.string "ENTRENADORES de regiones lejanas…$"

CableClub_Text_OtherTrainerNotReady:
	.string "El otro ENTRENADOR no está listo.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Llevas al menos un POKéMON\n"
	.string "que no puede entrar.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Toma asiento y espera.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} ha enviado\n"
	.string "un {STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Hay un error de transmisión.\p"
	.string "No puedes mezclar datos con Rubí\n"
	.string "o Zafiro japoneses.\p"
	.string "Tampoco puedes mezclar a la vez\n"
	.string "Esmeralda japonés con Rubí o\l"
	.string "Zafiro de otras regiones.$"

CableClub_Text_AdapterNotConnected:
	.string "El Adaptador Inalámbrico no está\n"
	.string "bien conectado.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Los participantes deben acercarse\n"
	.string "al mostrador de recepción.$"

@ Unused
CableClub_Text_Hello:
	.string "¡Hola!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Espera, por favor.$"

CableClub_Text_YouMayTradeHere::
	.string "Aquí puedes intercambiar POKéMON\n"
	.string "con otro ENTRENADOR.$"

CableClub_Text_YouMayBattleHere::
	.string "Aquí puedes combatir con amigos.$"

CableClub_Text_CanMakeBerryPowder::
	.string "De dos a cinco ENTRENADORES pueden\n"
	.string "hacer POLVO DE BAYA juntos.$"

CableClub_Text_CanMixRecords::
	.string "Permite mezclar los registros\n"
	.string "de dos a cuatro jugadores.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Guía de servicios del CLUB\n"
	.string "INALÁMBRICO.$"

CableClub_Text_CancelSelectedItem::
	.string "Cancela la opción seleccionada.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "¿Qué modo de combate quieres?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Vuelve al paso anterior.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Para usar MACHACABAYAS necesitas\n"
	.string "al menos una BAYA.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Para entrar en la SALA UNIÓN debes\n"
	.string "llevar al menos dos POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "No puede entrar ningún POKéMON con\n"
	.string "la BAYA {STR_VAR_1} en la SALA.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Esta es la SALA UNIÓN del CLUB\n"
	.string "INALÁMBRICO POKéMON.\p"
	.string "El Adaptador Inalámbrico no está\n"
	.string "bien conectado.\p"
	.string "Vuelve cuando quieras.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "¡Perdona!$"

CableClub_Text_PlayerIsWaiting:
	.string "{STR_VAR_1} parece estar jugando.\n"
	.string "¡Adelante!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Puedo explicarte las reglas.\p"
	.string "¿Sobre qué juego quieres saber?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“SALTO POKéMON”\p"
	.string "Pulsa A para que tu POKéMON salte\n"
	.string "la cuerda de LÁTIGO CEPA.\p"
	.string "Solo participan POKéMON pequeños,\n"
	.string "de unos 70 cm o menos.\p"
	.string "Quienes nadan, excavan o vuelan\n"
	.string "no pueden participar.\p"
	.string "Si todos saltan al compás,\n"
	.string "ocurrirán cosas buenas.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“RECOGE BAYAS CON DODRIO”\p"
	.string "Mueve sus tres cabezas para atrapar\n"
	.string "las BAYAS que caen.\p"
	.string "Pulsa derecha, arriba o izquierda\n"
	.string "en la cruceta para moverlas.\p"
	.string "Necesitas un DODRIO para jugar.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Si quieres jugar, habla con\n"
	.string "el anciano que está a mi lado.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "¡Hola, bienvenido!\n"
	.string "¿Vienes a jugar por comunicación\l"
	.string "inalámbrica?\p"
	.string "¿Puedes esperar un momento?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "De acuerdo. ¡Vuelve pronto!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "El Adaptador Inalámbrico no está\n"
	.string "conectado. ¡Vuelve cuando lo esté!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Bien, ¿a qué juego quieres jugar?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "¿Qué POKéMON quieres inscribir?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Perfecto, ya puedes empezar.\n"
	.string "¡Que no te ganen los demás!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "¿Ya te vas?\n"
	.string "¡Vuelve cuando quieras!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "No parece que tengas ningún POKéMON\n"
	.string "que pueda participar…\p"
	.string "¿Quieres que te explique cuáles\n"
	.string "pueden hacerlo?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "En SALTO POKéMON participan POKéMON\n"
	.string "de unos 70 cm o menos.\p"
	.string "No pueden entrar quienes no saltan,\n"
	.string "como los que solo nadan, excavan\l"
	.string "o vuelan. Eso es todo.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "En RECOGE BAYAS solo puede\n"
	.string "participar DODRIO.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Inténtalo de nuevo desde el inicio.$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Bienvenido al RINCÓN DIRECTO del\n"
	.string "CLUB INALÁMBRICO POKéMON.\p"
	.string "Aquí puedes conectar directamente\n"
	.string "con tus amigos.\p"
	.string "¿En qué sala quieres entrar?$"

CableClub_Text_TradePokemon:
	.string "¿Quieres intercambiar POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "¿A qué modo de combate quieres\n"
	.string "jugar?$"

CableClub_Text_AccessRecordCorner:
	.string "¿Quieres acceder al RINCÓN\n"
	.string "DE REGISTROS?$"

CableClub_Text_UseBerryCrush:
	.string "¿Quieres usar MACHACABAYAS?$"

CableClub_Text_ExplainBattleModes:
	.string "Hay tres modos de combate.\p"
	.string "El COMBATE INDIVIDUAL es para dos\n"
	.string "ENTRENADORES con algún POKéMON.\p"
	.string "Cada uno usa un POKéMON a la vez.\p"
	.string "El COMBATE DOBLE es para dos\n"
	.string "ENTRENADORES con dos POKéMON.\p"
	.string "Cada uno usa dos POKéMON a la vez.\p"
	.string "El COMBATE MÚLTIPLE es para cuatro\n"
	.string "ENTRENADORES con algún POKéMON.\p"
	.string "Cada uno usa un POKéMON a la vez.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Decidid cuál de los dos será\n"
	.string "el LÍDER.\p"
	.string "El otro debe elegir “UNIRSE”.$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Decidid cuál de los cuatro será\n"
	.string "el LÍDER DEL GRUPO.\p"
	.string "Los demás deben elegir “UNIRSE”.$"

CableClub_Text_ChooseGroupLeader:
	.string "Decidid quién será el LÍDER\n"
	.string "DEL GRUPO.\p"
	.string "Los demás deben elegir “UNIRSE”.$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Bienvenido a la SALA UNIÓN del\n"
	.string "CLUB INALÁMBRICO POKéMON.\p"
	.string "Aquí puedes relacionarte con otros\n"
	.string "ENTRENADORES, incluso desconocidos.\p"
	.string "¿Quieres entrar en la sala?$"

CableClub_Text_UnionRoomInfo:
	.string "En la SALA UNIÓN verás jugadores\n"
	.string "cercanos que también hayan entrado.\p"
	.string "Podrás saludarlos y hacer muchas\n"
	.string "otras cosas.\p"
	.string "Puedes llevar dos POKéMON de hasta\n"
	.string "Nv. 30 para combatir cara a cara.\p"
	.string "También puedes charlar con entre\n"
	.string "dos y cinco personas o registrar\l"
	.string "un POKéMON para intercambiar.\p"
	.string "¿Quieres entrar en la sala?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Disfruta de la SALA UNIÓN.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "¡Hola!\n"
	.string "Me llamo TEALA.\p"
	.string "Debe de ser tu primera vez aquí.\p"
	.string "Te explicaré cómo funciona el\n"
	.string "sistema de conexión inalámbrica.\p"
	.string "Antes te enseñaré esta planta\n"
	.string "del CENTRO POKéMON. Sígueme.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "Arriba hay dos salas.\p"
	.string "A la izquierda está la SALA UNIÓN.\n"
	.string "Allí conectarás con ENTRENADORES\l"
	.string "cercanos que también hayan entrado.\p"
	.string "Podéis charlar, combatir e\n"
	.string "intercambiar.\p"
	.string "A la derecha: el RINCÓN DIRECTO.\n"
	.string "Allí puedes intercambiar y combatir\l"
	.string "con tus amigos.\p"
	.string "Si no conectas el Adaptador\n"
	.string "Inalámbrico, aún puedes usar un\l"
	.string "cable Game Link GBA.\p"
	.string "En ese caso, ve al RINCÓN DIRECTO.\p"
	.string "¡Disfruta de la comunicación\n"
	.string "inalámbrica!$"

CableClub_Text_AskAboutLinking:
	.string "¡Hola, {PLAYER}!\p"
	.string "Soy TEALA, la encargada del piso\n"
	.string "superior del CENTRO POKéMON.\p"
	.string "¿Quieres preguntarme algo sobre\n"
	.string "las conexiones?$"

CableClub_Text_ExplainWirelessClub:
	.string "Te explicaré el funcionamiento del\n"
	.string "CLUB INALÁMBRICO POKéMON.\p"
	.string "En esta planta hay dos salas.\p"
	.string "A la izquierda está la SALA UNIÓN.\n"
	.string "Allí conectarás con ENTRENADORES\l"
	.string "cercanos para charlar, combatir\l"
	.string "e intercambiar.\p"
	.string "A la derecha: el RINCÓN DIRECTO,\n"
	.string "para jugar con tus amigos.\p"
	.string "Si no os encontráis, acercaos\n"
	.string "más entre vosotros.\p"
	.string "Sin Adaptador Inalámbrico puedes\n"
	.string "usar un cable Game Link GBA en\l"
	.string "el RINCÓN DIRECTO.\p"
	.string "¡Disfruta de la comunicación\n"
	.string "inalámbrica!$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "¡Disfruta de la comunicación\n"
	.string "inalámbrica!$"
