Text_PictureBookShelf:
	.string "Hay una colección de libros con\n"
	.string "ilustraciones de POKéMON.$"

Text_BookShelf:
	.string "Está repleto de libros de todo tipo.$"

Text_PokemonCenterBookShelf:
	.string "¡Revistas POKéMON!\n"
	.string "AMIGO POKéMON…\p"
	.string "MANUAL POKéMON…\n"
	.string "POKéMON ADORABLES…$"

Text_Vase:
	.string "Este jarrón parece muy caro…\n"
	.string "Echas un vistazo dentro…\p"
	.string "Pero está completamente vacío.$"

Text_EmptyTrashCan:
	.string "Está vacía.$"

Text_ShopShelf:
	.string "Las estanterías están a rebosar de\n"
	.string "artículos y productos POKéMON.$"

Text_Blueprint:
	.string "¿Es una especie de plano?\n"
	.string "¡Es demasiado complicado!$"
