@ Crystal-accurate phone dialogue for HnS rematch trainers
@ Greetings from Crystal callee/caller files prepended to each text

@ Joey - Youngster, Route 30
MatchCall_HNS_Joey_General1::
	.string "¡Hola, {PLAYER}! ¿Qué tal estás?\p"

	.string "¿Qué tal están tus POKéMON?\p"

	.string "Mi {STR_VAR_3} está ansioso por\n"
	.string "luchar, como siempre.\p"

	.string "Es el único que tengo. ¡Con él,\n"
	.string "llegaré a ser un gran\l"
	.string "entrenador!$"

MatchCall_HNS_Joey_General2::
	.string "¡Hola, {PLAYER}! ¿Tienes un\n"
	.string "minuto?\p"

	.string "¡Mi {STR_VAR_3} parece más listo\n"
	.string "que antes!\p"

	.string "¡Dudo que tengas un POKéMON tan\n"
	.string "guay como éste en tu equipo!$"

MatchCall_HNS_Joey_General3::
	.string "¡Hola, {PLAYER}! ¿Qué tal estás?\p"

	.string "Estoy estudiando los movimientos\n"
	.string "de {STR_VAR_3} y pensando\l"
	.string "estrategias.\p"

	.string "Cuando encuentre una buena,\n"
	.string "¡lucharemos!$"

MatchCall_HNS_Joey_Battle::
	.string "¡Hola, {PLAYER}!\p"

	.string "¡Reunámonos para luchar!\p"

	.string "¡Esta vez no lo tendrás tan\n"
	.string "fácil!$"

MatchCall_HNS_Wade_General1::
	.string "¡Hola, {PLAYER}!\p"

	.string "¿Qué tal están tus POKéMON?\p"

	.string "Mis POKéMON tienen demasiada\n"
	.string "energía.\p"

	.string "Puede llegar a ser un problema.\p"

	.string "De todos mis POKéMON,\n"
	.string "{STR_VAR_3} es el más difícil de\l"
	.string "controlar.\p"

	.string "Trabajar con él cansa mucho.$"

MatchCall_HNS_Wade_General2::
	.string "¡Hola, {PLAYER}! ¿A que hace un\n"
	.string "día estupendo?\p"

	.string "¿Tus POKéMON están creciendo?\p"

	.string "Mis POKéMON lo hacen demasiado\n"
	.string "rápido para mí. ¡Es abrumador!\p"

	.string "{STR_VAR_3} es el que más rápido\n"
	.string "crece.\p"

	.string "Creo que será muy fuerte.$"

MatchCall_HNS_Wade_General3::
	.string "¡Hola, {PLAYER}!\p"

	.string "Hace poco derrotamos de un golpe\n"
	.string "a un {STR_VAR_3} salvaje.\p"

	.string "Cayó con tanta facilidad que\n"
	.string "sentí pena por el pobre.$"

MatchCall_HNS_Wade_FoundItem::
	.string "¡Hola, {PLAYER}!\p"

	.string "Encontré todo tipo de BAYAS.\p"

	.string "Si quieres, puedo compartirlas\n"
	.string "contigo.\p"

	.string "Te esperaré en la RUTA 31.$"

MatchCall_HNS_Wade_Battle::
	.string "¡Hola, {PLAYER}!\p"

	.string "¿Te apetece luchar contra mí?\p"

	.string "¡No será como la última vez!$"

MatchCall_HNS_Ralph_General1::
	.string "¡Hola, {PLAYER}! ¿Qué tal va la\n"
	.string "pesca?\p"

	.string "¿Estás cuidando bien de tus\n"
	.string "POKéMON?\p"

	.string "¡Debes tratar bien a tus\n"
	.string "compañeros!$"

MatchCall_HNS_Ralph_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "He estado pasando más tiempo con\n"
	.string "mi {STR_VAR_3} que con mis\l"
	.string "niños.\p"

	.string "En realidad es un poco triste.$"

MatchCall_HNS_Ralph_General3::
	.string "¡Hola, {PLAYER}! ¡Escucha esto!\p"

	.string "Acabo de derrotar a un\n"
	.string "{STR_VAR_3} salvaje.\p"

	.string "Se lo he dicho a mi niño, pero\n"
	.string "se burló de mí diciendo que él\l"
	.string "hubiera hecho lo mismo, pero más\l"
	.string "fácilmente.\p"

	.string "Se ha vuelto un poco gallito…$"

MatchCall_HNS_Ralph_Battle::
	.string "¡Hola, {PLAYER}!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Liz_General1::
	.string "¡Hola, {PLAYER}! Tenía algo de\n"
	.string "tiempo, así que pensé en\l"
	.string "llamarte.\p"

	.string "De todos modos, ¿qué tal están\n"
	.string "tus POKéMON?\p"

	.string "Yo llevo cada día a mi\n"
	.string "{STR_VAR_3} al CENTRO POKéMON de\l"
	.string "CIUDAD MALVA,\p"

	.string "¡así que está fenomenal!\p"

	.string "¡Soy amiga de la recepcionista!$"

MatchCall_HNS_Liz_General2::
	.string "¡Hola, {PLAYER}! Oh, tienes que\n"
	.string "oír esto.\p"

	.string "¡Mi {STR_VAR_3} es tan\n"
	.string "encantador!\p"

	.string "¡Siempre está pegado a mí!$"

MatchCall_HNS_Liz_General3::
	.string "¡Hola, {PLAYER}! ¡Escucha,\n"
	.string "escucha!\p"

	.string "¿No te parece que PEGASO, del\n"
	.string "GIMNASIO de CIUDAD MALVA, es\l"
	.string "guapo y genial?\p"

	.string "Pero dicen que su padre, que\n"
	.string "está entrenando por ahí, es aún\l"
	.string "más guapo y genial que PEGASO.\p"

	.string "¡Ojalá pudiera conocerlo!$"

MatchCall_HNS_Liz_Battle::
	.string "¡Hola, {PLAYER}!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Anthony_General1::
	.string "¡Hola, {PLAYER}!\p"

	.string "¿Están tus POKéMON tan animados\n"
	.string "como siempre?\p"

	.string "Mi {STR_VAR_3} y yo tenemos\n"
	.string "mucha energía.\p"

	.string "Escalamos montañas todos los\n"
	.string "días a modo de entrenamiento.$"

MatchCall_HNS_Anthony_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "El otro día, vi como mi\n"
	.string "{STR_VAR_3} comía BAYAS.\p"

	.string "Parecía que estaba disfrutando\n"
	.string "de su comida, así que decidí\l"
	.string "probarlas.\p"

	.string "¡No estoy seguro de que la gente\n"
	.string "pueda comerlas, pero estaban\l"
	.string "deliciosas!$"

MatchCall_HNS_Anthony_General3::
	.string "¡Hola, {PLAYER}!\p"

	.string "Últimamente, me he cruzado a\n"
	.string "menudo con {STR_VAR_3} salvajes.\p"

	.string "Es fácil cuidarlos.$"

MatchCall_HNS_Anthony_Battle::
	.string "¡Hola, {PLAYER}!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Todd_General1::
	.string "¡Hola, {PLAYER}! ¿Qué tal?\p"

	.string "¿Cómo mejoras a tus POKéMON?\p"

	.string "Hago de todo, como dejarlos en\n"
	.string "la GUARDERÍA y\p"

	.string "fortalecerlos con objetos.$"

MatchCall_HNS_Todd_General2::
	.string "¡Hola, {PLAYER}! ¿Qué tal?\p"

	.string "Mi {STR_VAR_3} se parece cada\n"
	.string "vez más a mí.\p"

	.string "¡Está muy bonito!$"

MatchCall_HNS_Todd_General3::
	.string "¡Hola, {PLAYER}! ¿Qué tal?\p"

	.string "¿Sabes?\p"

	.string "Ahora podemos acabar fácilmente\n"
	.string "con los {STR_VAR_3}.\p"

	.string "Debo visitar el GIMNASIO TRIGAL.$"

MatchCall_HNS_Todd_Battle::
	.string "¡Hola, {PLAYER}!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Gina_General1::
	.string "¡Hola, {PLAYER}! ¿Qué tal estás?\p"

	.string "¿Tus POKéMON son duros?\p"

	.string "Yo me entreno todos los días con\n"
	.string "{STR_VAR_3}.$"

MatchCall_HNS_Gina_General2::
	.string "¡Hola, {PLAYER}! ¿Qué tal estás?\p"

	.string "Mi {STR_VAR_3} y yo estamos cada\n"
	.string "vez más sincronizados.$"

MatchCall_HNS_Gina_General3::
	.string "¡Hola, {PLAYER}! ¿Qué tal estás?\p"

	.string "Luchamos con un {STR_VAR_3}\n"
	.string "salvaje y conseguimos atraparle.\p"

	.string "¡Ya le estamos cogiendo el\n"
	.string "truco!$"

MatchCall_HNS_Gina_Battle::
	.string "¡Hola, {PLAYER}!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Irwin_General1::
	.string "Eh, ¿hola, {PLAYER}? ¡Soy tu\n"
	.string "amigo IRWIN!\p"

	.string "¡El otro día vi un combate\n"
	.string "increíble!\p"

	.string "Ojalá pudiera combatir así.\p"

	.string "¡Un momento, sí puedo! ¡Solo\n"
	.string "necesito un rival!$"

MatchCall_HNS_Irwin_General2::
	.string "Eh, ¿hola, {PLAYER}? ¡Soy tu\n"
	.string "amigo IRWIN!\p"

	.string "¡Je, je, acabo de llamar!\p"

	.string "¡Creo que podemos ser buenos\n"
	.string "amigos!$"

MatchCall_HNS_Irwin_General3::
	.string "Eh, ¿hola, {PLAYER}? ¡Soy tu\n"
	.string "amigo IRWIN!\p"

	.string "¡Oír lo de tus aventuras me\n"
	.string "alegra el alma!\p"

	.string "¡Te lo aseguro!$"

MatchCall_HNS_Irwin_Battle::
	.string "Eh, ¿hola, {PLAYER}? ¡Soy tu\n"
	.string "amigo IRWIN!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Arnie_General1::
	.string "¡Hola, {PLAYER}! ¿Qué tal va\n"
	.string "todo?\p"

	.string "Seguro que tus POKéMON son más\n"
	.string "fuertes que antes.$"

MatchCall_HNS_Arnie_General2::
	.string "¡Hola, {PLAYER}! ¿Qué tal va\n"
	.string "todo?\p"

	.string "¡Siempre estoy con mi\n"
	.string "{STR_VAR_3}!\p"

	.string "¡Es tan mono! ¡Me encanta!$"

MatchCall_HNS_Arnie_General3::
	.string "¡Hola, {PLAYER}! ¿Qué tal va\n"
	.string "todo?\p"

	.string "Cambiando de tema, he visto a un\n"
	.string "{STR_VAR_3} por primera vez.\p"

	.string "La verdad, fue fácil vencerlo.$"

MatchCall_HNS_Arnie_Battle::
	.string "¡Hola, {PLAYER}!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Alan_General1::
	.string "¡Hola, {PLAYER}! ¡Soy ALAN!\p"

	.string "{PLAYER}, ¿estás criando bien a\n"
	.string "tus POKéMON?\p"

	.string "He leído que debes criar con\n"
	.string "cariño y cuidado a todos los\l"
	.string "POKéMON que captures.$"

MatchCall_HNS_Alan_General2::
	.string "¡Hola, {PLAYER}! ¡Soy ALAN!\p"

	.string "Mi {STR_VAR_3} está cada vez más\n"
	.string "fuerte, ¡justo como calculé!$"

MatchCall_HNS_Alan_General3::
	.string "¡Hola, {PLAYER}! ¡Soy ALAN!\p"

	.string "Por cierto, el otro día\n"
	.string "noqueamos a un {STR_VAR_3}\l"
	.string "salvaje.\p"

	.string "¡Estudiar funciona!$"

MatchCall_HNS_Alan_FoundItem::
	.string "¡Hola, {PLAYER}! ¡Soy ALAN!\p"

	.string "¡Je, je, he cogido algo\n"
	.string "interesante!\p"

	.string "¡Es tuyo!\p"

	.string "¿Por qué no vienes a la RUTA 36\n"
	.string "y te lo llevas?$"

MatchCall_HNS_Alan_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy ALAN!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Dana_General1::
	.string "¡Hola, {PLAYER}! ¡Soy DANA!\p"

	.string "Mi {STR_VAR_3} está tan lleno de\n"
	.string "energía que da un poco de miedo.\p"

	.string "¿Qué tal están tus POKéMON?$"

MatchCall_HNS_Dana_General2::
	.string "¡Hola, {PLAYER}! ¡Soy DANA!\p"

	.string "¡Mi {STR_VAR_3} está precioso!\p"

	.string "¡Le he hecho un montón de fotos!$"

MatchCall_HNS_Dana_General3::
	.string "¡Hola, {PLAYER}! ¡Soy DANA!\p"

	.string "Acabé con un {STR_VAR_3} salvaje\n"
	.string "en un segundo.\p"

	.string "Debe de ser porque la última vez\n"
	.string "me diste consejos de combate.$"

MatchCall_HNS_Dana_FoundItem::
	.string "¡Hola, {PLAYER}! ¡Soy DANA!\p"

	.string "¿Sabes una cosa? ¡Conseguí un\n"
	.string "gran regalo!\p"

	.string "¡Como prometí, es tuyo! Sabía\n"
	.string "que te gustaría.\p"

	.string "¡Ven a por él! ¡Te espero en la\n"
	.string "RUTA 38!$"

MatchCall_HNS_Dana_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy DANA!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Chad_General1::
	.string "¡Hola, {PLAYER}! ¡Soy CHAD!\p"

	.string "¿Qué tal están tus POKéMON?\p"

	.string "Ya conoces al PROF. OAK, ¡así\n"
	.string "que seguro que tus POKéMON están\l"
	.string "bien!\p"

	.string "Los míos también están bien.\p"

	.string "Claro que intento convertirme en\n"
	.string "profesor POKéMON.$"

MatchCall_HNS_Chad_General2::
	.string "¡Hola, {PLAYER}! ¡Soy CHAD!\p"

	.string "Hace poco empecé a observar a\n"
	.string "los {STR_VAR_3} salvajes.\p"

	.string "Gracias a mis observaciones\n"
	.string "estoy aprendiendo todo tipo de\l"
	.string "cosas.\p"

	.string "Ojalá pronto pueda ser\n"
	.string "investigador POKéMON como el\l"
	.string "PROF. OAK.$"

MatchCall_HNS_Chad_General3::
	.string "¡Hola, {PLAYER}! ¡Soy CHAD!\p"

	.string "¡Voy a estudiar mucho para que\n"
	.string "el PROF. OAK me haga su\l"
	.string "ayudante!$"

MatchCall_HNS_Chad_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy CHAD!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Derek_General1::
	.string "¡Hola, {PLAYER}! ¡Soy DEREK!\p"

	.string "¡Tienes que oír esto!\p"

	.string "¡Mi adorable {STR_VAR_3} me miró\n"
	.string "y me sonrió!\p"

	.string "¡Será porque somos almas\n"
	.string "gemelas!$"

MatchCall_HNS_Derek_General2::
	.string "¡Hola, {PLAYER}! ¡Soy DEREK!\p"

	.string "Escucha esto.\p"

	.string "Mi {STR_VAR_3} sonríe alegre si\n"
	.string "le pellizco el moflete.\p"

	.string "Pero sólo si lo hago yo.\p"

	.string "Debo de ser especial.$"

MatchCall_HNS_Derek_General3::
	.string "¡Hola, {PLAYER}! ¡Soy DEREK!\p"

	.string "¿Cómo está tu PIKACHU?\p"

	.string "¡Reunámonos para presumir de\n"
	.string "nuestros PIKACHU!$"

MatchCall_HNS_Derek_FoundItem::
	.string "¡Hola, {PLAYER}! ¡Soy DEREK!\p"

	.string "Quiero darte una PEPITA.\p"

	.string "Estoy en la RUTA 39. ¡Ven a\n"
	.string "recogerlo!$"

MatchCall_HNS_Derek_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy DEREK!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Tully_General1::
	.string "¡Hola, {PLAYER}! ¡Soy TULLY!\p"

	.string "¿Qué tal va tu viaje?\p"

	.string "¡No puedo quejarme de mi pesca!$"

MatchCall_HNS_Tully_General2::
	.string "¡Hola, {PLAYER}! ¡Soy TULLY!\p"

	.string "Mi {STR_VAR_3} ha vuelto a\n"
	.string "crecer.\p"

	.string "Sólo era así de grande cuando lo\n"
	.string "atrapé, pero ahora es mucho\l"
	.string "mayor.$"

MatchCall_HNS_Tully_General3::
	.string "¡Hola, {PLAYER}! ¡Soy TULLY!\p"

	.string "Ya lo creo, noqueé a un\n"
	.string "{STR_VAR_3} salvaje.\p"

	.string "Era enorme, así de grande.\p"

	.string "Eh, seguro que no te lo crees\n"
	.string "por teléfono…$"

MatchCall_HNS_Tully_FoundItem::
	.string "¡Hola, {PLAYER}! ¡Soy TULLY!\p"

	.string "Pesqué una cosita interesante en\n"
	.string "la orilla.\p"

	.string "Como te prometí, es tuyo.\p"

	.string "Te esperaré en la RUTA 42.$"

MatchCall_HNS_Tully_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy TULLY!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Brent_General1::
	.string "¡Hola, {PLAYER}! ¡Soy BRENT!\p"

	.string "El otro día te vi salir de un\n"
	.string "CENTRO POKéMON.\p"

	.string "Curas a tus POKéMON a menudo,\n"
	.string "¿verdad? Me has impresionado.\p"

	.string "Je, mi {STR_VAR_3} es tan fuerte\n"
	.string "que apenas necesita ir al CENTRO\l"
	.string "POKéMON. ¡Je, je!$"

MatchCall_HNS_Brent_General2::
	.string "¡Hola, {PLAYER}! ¡Soy BRENT!\p"

	.string "Sí, conseguí un POKéMON raro\n"
	.string "mediante intercambio hace un\l"
	.string "rato.\p"

	.string "¿Quieres saber cuál es?\p"

	.string "Je, je, ¡es un secreto!$"

MatchCall_HNS_Brent_General3::
	.string "¡Hola, {PLAYER}! ¡Soy BRENT!\p"

	.string "¿Sabías que…?\p"

	.string "BILL proviene de CIUDAD TRIGAL.\p"

	.string "Como es obvio, a BILL no se le\n"
	.string "da bien luchar.$"

MatchCall_HNS_Brent_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy BRENT!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Tiffany_General1::
	.string "¡Hola, {PLAYER}! ¡Soy TIFFANY!\p"

	.string "¿Qué tal van tus POKéMON?\p"

	.string "Espero que les lleves a un\n"
	.string "CENTRO POKéMON todos los días.\p"

	.string "Dosifica sus fuerzas.\p"

	.string "Mi {STR_VAR_3} es bonito y\n"
	.string "vivaracho precisamente porque le\l"
	.string "llevo todos los días a un CENTRO\l"
	.string "POKéMON.$"

MatchCall_HNS_Tiffany_General2::
	.string "¡Hola, {PLAYER}! ¡Soy TIFFANY!\p"

	.string "Mi {STR_VAR_3} es adorable, ¿no\n"
	.string "crees?\p"

	.string "Siempre duermo con él, ¡es\n"
	.string "blando y calentito!$"

MatchCall_HNS_Tiffany_General3::
	.string "¡Hola, {PLAYER}! ¡Soy TIFFANY!\p"

	.string "Oh, y teníamos que luchar contra\n"
	.string "un {STR_VAR_3} salvaje hace un\l"
	.string "rato…\p"

	.string "¡Mi CLEFAIRY casi se desmaya!\p"

	.string "¿No es horrible? ¡Odio a los\n"
	.string "{STR_VAR_3}!$"

MatchCall_HNS_Tiffany_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy TIFFANY!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Vance_General1::
	.string "¡Hola, {PLAYER}! ¡Soy VANCE!\p"

	.string "¿Estáis bien tus POKéMON y tú?\p"

	.string "Parece que mi {STR_VAR_3} será\n"
	.string "lo bastante fuerte\p"

	.string "¡para enfrentarse a las aves\n"
	.string "legendarias y vencerlas!$"

MatchCall_HNS_Vance_General2::
	.string "¡Hola, {PLAYER}! ¡Soy VANCE!\p"

	.string "Mi {STR_VAR_3} está más y más\n"
	.string "fuerte.\p"

	.string "¡Hemos despegado!$"

MatchCall_HNS_Vance_General3::
	.string "¡Hola, {PLAYER}! ¡Soy VANCE!\p"

	.string "¡Podemos derrotar a {STR_VAR_3}\n"
	.string "sin problemas!\p"

	.string "¿Sí? ¿Tú también? ¡Estupendo!$"

MatchCall_HNS_Vance_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy VANCE!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Wilton_General1::
	.string "¡Hola, {PLAYER}! ¡Soy WILTON!\p"

	.string "¿Han crecido algo tus POKéMON?\p"

	.string "Mi {STR_VAR_3} ha crecido un\n"
	.string "poco.$"

MatchCall_HNS_Wilton_General2::
	.string "¡Hola, {PLAYER}! ¡Soy WILTON!\p"

	.string "¡Mi {STR_VAR_3} está\n"
	.string "impresionante!\p"

	.string "¡También soy mejor pescador!$"

MatchCall_HNS_Wilton_General3::
	.string "¡Hola, {PLAYER}! ¡Soy WILTON!\p"

	.string "Hemos vencido a un {STR_VAR_3}\n"
	.string "salvaje…\p"

	.string "La verdad, me divierte más\n"
	.string "pescar que vencer POKéMON\l"
	.string "salvajes.$"

MatchCall_HNS_Wilton_FoundItem::
	.string "¡Hola, {PLAYER}! ¡Soy WILTON!\p"

	.string "Enganché un objeto pescando.\p"

	.string "Ven a recogerlo en la RUTA 44.$"

MatchCall_HNS_Wilton_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy WILTON!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Kenji_General1::
	.string "¡Hola, {PLAYER}! ¡Soy KENJI!\p"

	.string "¡{PLAYER}! Qué buen tiempo,\n"
	.string "¿verdad?$"

MatchCall_HNS_Kenji_General2::
	.string "¡Hola, {PLAYER}! ¡Soy KENJI!\p"

	.string "¿Continúas viajando?\p"

	.string "Yo sigo entrenándome a fondo.\p"

	.string "¡Oooooaaarrrgh!$"

MatchCall_HNS_Kenji_General3::
	.string "¡Hola, {PLAYER}! ¡Soy KENJI!\p"

	.string "Ahora estoy entrenándome.\p"

	.string "Tendrás que llamarme en otro\n"
	.string "momento.\p"

	.string "¡Oooooaaarrrgh!$"

MatchCall_HNS_Kenji_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy KENJI!\p"

	.string "¡Estoy descansando!\p"

	.string "¿Por qué no te pasas un rato?$"

MatchCall_HNS_Kenji_FoundItem::
	.string "¡Hola, {PLAYER}! ¡Soy KENJI!\p"

	.string "Estoy descansando del\n"
	.string "entrenamiento.\p"

	.string "He encontrado algo bueno. ¡Ven a\n"
	.string "por ello si lo quieres!$"

MatchCall_HNS_Parry_General1::
	.string "¡Hola, {PLAYER}! ¡Soy PARRY!\p"

	.string "¿Qué tal están tus POKéMON?\p"

	.string "¡Mi {STR_VAR_3} y yo estamos muy\n"
	.string "bien! ¡Ja, ja, ja, ja!$"

MatchCall_HNS_Parry_General2::
	.string "¡Hola, {PLAYER}! ¡Soy PARRY!\p"

	.string "No hay nada como mi {STR_VAR_3}.$"

MatchCall_HNS_Parry_General3::
	.string "¡Hola, {PLAYER}! ¡Soy PARRY!\p"

	.string "¡Noqueamos a un {STR_VAR_3}\n"
	.string "salvaje!\p"

	.string "Estuvo bien, pero quería\n"
	.string "atraparlo…$"

MatchCall_HNS_Parry_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy PARRY!\p"

	.string "Volveremos a luchar, ¿verdad?$"

MatchCall_HNS_Erin_General1::
	.string "¡Hola, {PLAYER}! ¡Soy ERIN!\p"

	.string "¿Estás mejorando a tus POKéMON?\p"

	.string "¡El {STR_VAR_3} de  está muy\n"
	.string "bien!$"

MatchCall_HNS_Erin_General2::
	.string "¡Hola, {PLAYER}! ¡Soy ERIN!\p"

	.string "El {STR_VAR_3} de  está mucho\n"
	.string "más fuerte que antes.$"

MatchCall_HNS_Erin_General3::
	.string "¡Hola, {PLAYER}! ¡Soy ERIN!\p"

	.string "Y, y… ¡Acabo de derrotar a\n"
	.string "{STR_VAR_3}!\p"

	.string "¡He entrenado bien a mis\n"
	.string "POKéMON!$"

MatchCall_HNS_Erin_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy ERIN!\p"

	.string "¡Trabajo duro para entrenar a\n"
	.string "mis POKéMON!\p"

	.string "¡Vuelve para luchar de nuevo!$"

MatchCall_HNS_Jack_General1::
	.string "¡Hola, {PLAYER}! ¡Soy JACK!\p"

	.string "¿Qué tal están tus POKéMON?\p"

	.string "Mi {STR_VAR_3} es muy curioso,\n"
	.string "es un problema.\p"

	.string "Quizá es como yo…$"

MatchCall_HNS_Jack_General2::
	.string "¡Hola, {PLAYER}! ¡Soy JACK!\p"

	.string "La inteligencia de mi\n"
	.string "{STR_VAR_3} sigue creciendo.\p"

	.string "¡Va a ser más listo que los\n"
	.string "tuyos!$"

MatchCall_HNS_Jack_General3::
	.string "¡Hola, {PLAYER}! ¡Soy JACK!\p"

	.string "¿Sabías qué…?\p"

	.string "Cuando llueve, el ataque TRUENO\n"
	.string "siempre golpea.\p"

	.string "Mi amigo ha oído algunos trucos\n"
	.string "geniales. Cuando me los diga, te\l"
	.string "llamaré para contártelos.$"

MatchCall_HNS_Jack_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy JACK!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Beverly_General1::
	.string "¡Hola, {PLAYER}! ¡Soy BEVERLY!\p"

	.string "¿Son felices tus POKéMON?\p"

	.string "Mi {STR_VAR_3} está sano. Come\n"
	.string "mucho todos los días.$"

MatchCall_HNS_Beverly_General2::
	.string "¡Hola, {PLAYER}! ¡Soy BEVERLY!\p"

	.string "¡He arreglado a mi {STR_VAR_3} y\n"
	.string "está más guapo que nunca!$"

MatchCall_HNS_Beverly_General3::
	.string "¡Hola, {PLAYER}! ¡Soy BEVERLY!\p"

	.string "¿Están tus POKéMON en forma?\p"

	.string "Hablemos de POKéMON otra vez.$"

MatchCall_HNS_Beverly_FoundItem::
	.string "¡Hola, {PLAYER}! ¡Soy BEVERLY!\p"

	.string "Mi marido obtuvo algunas\n"
	.string "PEPITAS.\p"

	.string "Si quieres, puedes quedarte con\n"
	.string "una por ayudarme.\p"

	.string "Estaré en el PARQUE NACIONAL.\n"
	.string "Por favor, ven a verme cuando\l"
	.string "puedas.$"

MatchCall_HNS_Beverly_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy BEVERLY!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Huey_General1::
	.string "¡Hola, {PLAYER}! ¡Soy HUEY!\p"

	.string "¿Qué tal va todo?$"

MatchCall_HNS_Huey_General2::
	.string "¡Hola, {PLAYER}! ¡Soy HUEY!\p"

	.string "Tenemos que luchar en otra\n"
	.string "ocasión.\p"

	.string "Descuida, seguiré retándote\n"
	.string "hasta que te gane.$"

MatchCall_HNS_Huey_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy HUEY!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Gaven_General1::
	.string "¡Hola, {PLAYER}! ¡Soy GAVEN!\p"

	.string "¿Qué tal están tus POKéMON?\p"

	.string "Mi {STR_VAR_3} lo está haciendo\n"
	.string "mejor que nunca.\p"

	.string "¡Si seguimos así, seremos\n"
	.string "CAMPEONES POKéMON!$"

MatchCall_HNS_Gaven_General2::
	.string "¡Hola, {PLAYER}! ¡Soy GAVEN!\p"

	.string "Mi {STR_VAR_3} puede ser mejor\n"
	.string "de lo que imaginaba.\p"

	.string "Dudo que vea a un {STR_VAR_3}\n"
	.string "mejor que el mío.$"

MatchCall_HNS_Gaven_General3::
	.string "¡Hola, {PLAYER}! ¡Soy GAVEN!\p"

	.string "Me obsesiona la idea de\n"
	.string "vencerte.$"

MatchCall_HNS_Gaven_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy GAVEN!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Beth_General1::
	.string "¡Hola, {PLAYER}! ¡Soy BETH!\p"

	.string "¿Eres del tipo de persona que va\n"
	.string "a menudo a los CENTROS POKéMON?\p"

	.string "Yo voy todos los días. Cuidar de\n"
	.string "la salud de tus POKéMON es uno\l"
	.string "de los principios básicos de\l"
	.string "entrenar POKéMON.$"

MatchCall_HNS_Beth_General2::
	.string "¡Hola, {PLAYER}! ¡Soy BETH!\p"

	.string "¿Recuerdas a mi dulce\n"
	.string "{STR_VAR_3}?\p"

	.string "{STR_VAR_3} corre muy rápido.\p"

	.string "Montar sobre su espalda cuando\n"
	.string "se pone en marcha es muy\l"
	.string "emocionante.$"

MatchCall_HNS_Beth_General3::
	.string "¡Hola, {PLAYER}! ¡Soy BETH!\p"

	.string "¡Debemos luchar en otra ocasión!$"

MatchCall_HNS_Beth_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy BETH!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Jose_General1::
	.string "¡Hola, {PLAYER}! ¡Soy JOSE!\p"

	.string "Tus POKéMON, ¿aún se entrenan?\p"

	.string "Mi {STR_VAR_3} tiene mucha\n"
	.string "energía.\p"

	.string "Cuando despega, no vuelve en un\n"
	.string "rato.$"

MatchCall_HNS_Jose_General2::
	.string "¡Hola, {PLAYER}! ¡Soy JOSE!\p"

	.string "Escucha, el puerro de mi\n"
	.string "{STR_VAR_3} tiene un aroma\l"
	.string "delicioso.\p"

	.string "¡Ese aroma me abre el apetito!$"

MatchCall_HNS_Jose_General3::
	.string "¡Hola, {PLAYER}! ¡Soy JOSE!\p"

	.string "Hace un tiempo, mi FARFETCH'D\n"
	.string "derrotó a {STR_VAR_3}.\p"

	.string "Deberías haber visto a\n"
	.string "FARFETCH'D con ese puerro.\p"

	.string "¡Impresionante!$"

MatchCall_HNS_Jose_FoundItem::
	.string "¡Hola, {PLAYER}! ¡Soy JOSE!\p"

	.string "Mi FARFETCH'D llevaba en el pico\n"
	.string "algo bonito.\p"

	.string "Como prometí, puedes quedártelo.\p"

	.string "Búscame en la RUTA 27 y te lo\n"
	.string "daré.$"

MatchCall_HNS_Jose_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy JOSE!\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Reena_General1::
	.string "Hola, {PLAYER}. Soy REENA.\p"

	.string "Eh, ¿qué tal van tus POKéMON?\p"

	.string "¿Qué? ¿Genial? Ya veo…\p"

	.string "¿Qué? ¿Mis POKéMON?\p"

	.string "¡Claro que lo están haciendo\n"
	.string "bien! ¿A qué te refieres?$"

MatchCall_HNS_Reena_General2::
	.string "Hola, {PLAYER}. Soy REENA.\p"

	.string "Escucha, joven…\p"

	.string "¿Te acuerdas de mi {STR_VAR_3}?\p"

	.string "Exactamente. Ese bonito\n"
	.string "{STR_VAR_3}.\p"

	.string "¿No opinas que es una pareja\n"
	.string "perfecta para mí?$"

MatchCall_HNS_Reena_General3::
	.string "Hola, {PLAYER}. Soy REENA.\p"

	.string "No te enorgullezcas tanto por\n"
	.string "haberme vencido…\p"

	.string "¡Ha sido chiripa!$"

MatchCall_HNS_Reena_Battle::
	.string "Hola, {PLAYER}. Soy REENA.\p"

	.string "Te estaba esperando. ¡Luchemos!$"

MatchCall_HNS_Alex_General1::
	.string "¡Hola, {PLAYER}! ¡Soy ALEX!\p"

	.string "Mis majestuosos POKéMON mejoran\n"
	.string "cada día.\p"

	.string "¡{STR_VAR_3} se está volviendo\n"
	.string "muy fuerte!$"

MatchCall_HNS_Alex_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "He oído que otras regiones\n"
	.string "tienen reyes y reinas. ¿Por qué\l"
	.string "KANTO no tiene\p"

	.string "realeza?$"

MatchCall_HNS_Alex_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy ALEX!\p"

	.string "¡Mis majestuosos POKéMON están\n"
	.string "listos para la revancha! ¡Ven a\l"
	.string "la RUTA 13!$"

MatchCall_HNS_Riley_General1::
	.string "¡Hola, {PLAYER}! Soy RILEY.\p"

	.string "La RUTA CICLISTA es lo mejor. No\n"
	.string "hay nada como sentir el viento\l"
	.string "en la cara.\p"

	.string "¡A {STR_VAR_3} también le\n"
	.string "encanta la velocidad!$"

MatchCall_HNS_Riley_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "Los chavales de JOHTO no sois\n"
	.string "malos. Quizá te juzgué mal.\p"

	.string "¡Pero no dejes que se te suba a\n"
	.string "la cabeza!$"

MatchCall_HNS_Riley_Battle::
	.string "¡Hola, {PLAYER}! Soy RILEY.\p"

	.string "¡Ven a la RUTA CICLISTA! ¡Quiero\n"
	.string "la revancha!$"

MatchCall_HNS_Trevor_General1::
	.string "¡Hola, {PLAYER}! Soy TREVOR.\p"

	.string "¿Sabías que los POKéMON se\n"
	.string "encariñan más si entrenáis en\l"
	.string "lugares memorables?\p"

	.string "Parece que a {STR_VAR_3} le\n"
	.string "gusta este lugar.$"

MatchCall_HNS_Trevor_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "Algunos movimientos son más\n"
	.string "fuertes cuando tu\p"

	.string "¡POKéMON siente más cariño por\n"
	.string "ti!$"

MatchCall_HNS_Trevor_Battle::
	.string "¡Hola, {PLAYER}! Soy TREVOR.\p"

	.string "¡Mis amigos están listos para\n"
	.string "combatir! ¡Ven a vernos a la\l"
	.string "RUTA 14!$"

MatchCall_HNS_Kyle_General1::
	.string "¡¿Quién eres?! ¿Te he llamado\n"
	.string "yo?\p"

	.string "Soy KYLE. ¡No lo olvides!$"

MatchCall_HNS_Kyle_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "¿Recuerdas? ¿Los secretos de la\n"
	.string "pesca?$"

MatchCall_HNS_Kyle_Battle::
	.string "¡Hola, {PLAYER}! Soy KYLE.\p"

	.string "¡He pescado nuevos POKéMON muy\n"
	.string "fuertes!\p"

	.string "¡Ven a combatir a la RUTA 12!$"

MatchCall_HNS_Carter_General1::
	.string "¡Hola, {PLAYER}! Soy CARTER.\p"

	.string "He estado reuniendo POKéMON\n"
	.string "iniciales raros.\p"

	.string "¡Mi {STR_VAR_3} es mi nuevo\n"
	.string "orgullo!$"

MatchCall_HNS_Carter_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "¿Sabías que hay POKéMON\n"
	.string "iniciales de muchas regiones?\p"

	.string "¡Quiero reunirlos a todos!$"

MatchCall_HNS_Carter_Battle::
	.string "¡Hola, {PLAYER}! Soy CARTER.\p"

	.string "¡Tengo nuevos iniciales que\n"
	.string "enseñarte! ¡Ven a la RUTA 14!$"

MatchCall_HNS_Hillary_General1::
	.string "Hola, {PLAYER}. Soy la PROFESORA\n"
	.string "HILLARY.\p"

	.string "¿Por qué no estás en clase?$"

MatchCall_HNS_Hillary_General2::
	.string "Hola, {PLAYER}.\p"

	.string "¿Estás jugando en vez de hacer\n"
	.string "los deberes?$"

MatchCall_HNS_Hillary_Battle::
	.string "Hola, {PLAYER}. Soy HILLARY.\p"

	.string "¡Mis POKéMON han pasado al\n"
	.string "siguiente nivel!\p"

	.string "¡Ven a ponernos a prueba en la\n"
	.string "RUTA 15!$"

MatchCall_HNS_Rob_General1::
	.string "¡Hola, {PLAYER}! Soy ROB!\p"

	.string "¡El BOSQUE VERDE está lleno de\n"
	.string "BICHOS geniales!$"

MatchCall_HNS_Rob_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "¡Vi a un LÍDER de tipo BICHO en\n"
	.string "el BOSQUE VERDE!$"

MatchCall_HNS_Rob_Battle::
	.string "¡Hola, {PLAYER}! Soy ROB!\p"

	.string "¡Mi equipo de tipo BICHO es más\n"
	.string "fuerte que nunca!\p"

	.string "¡Ven a la RUTA 2 para la\n"
	.string "revancha!$"

MatchCall_HNS_Nicole_General1::
	.string "¡Hola, {PLAYER}! ¡Soy NICOLE!\p"

	.string "¡Hoy hay unas olas estupendas! A\n"
	.string "mis POKéMON les encanta nadar en\l"
	.string "alta mar.\p"

	.string "¡{STR_VAR_3} se está volviendo\n"
	.string "rapidísimo!$"

MatchCall_HNS_Nicole_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "Nadar con POKéMON es el mejor\n"
	.string "ejercicio.$"

MatchCall_HNS_Nicole_Battle::
	.string "¡Hola, {PLAYER}! ¡Soy NICOLE!\p"

	.string "¡Mis POKéMON de tipo AGUA están\n"
	.string "deseando combatir!\p"

	.string "¡Ven a la RUTA 20!$"

MatchCall_HNS_Billy_General1::
	.string "¡Hola, {PLAYER}! Soy BILLY.\p"

	.string "He estudiado estrategias de\n"
	.string "combate en clase.\p"

	.string "¡{STR_VAR_3} y yo las hemos\n"
	.string "practicado!$"

MatchCall_HNS_Billy_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "Se acercan los exámenes, pero\n"
	.string "prefiero combatir.\p"

	.string "Saber de libros no lo es todo,\n"
	.string "¿verdad?$"

MatchCall_HNS_Billy_Battle::
	.string "¡Hola, {PLAYER}! Soy BILLY.\p"

	.string "¡He aprendido algunos trucos\n"
	.string "nuevos! ¡Ven a la RUTA 15!$"

MatchCall_HNS_Kenny_General1::
	.string "¡Hola, {PLAYER}! Soy KENNY.\p"

	.string "¿De verdad los mares y los ríos\n"
	.string "dieron forma a todas las\l"
	.string "montañas?$"

MatchCall_HNS_Kenny_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "Soy KENNY. ¡He visitado el museo\n"
	.string "de CIUDAD PLATEADA!\p"

	.string "¿Sabías que toda la región de\n"
	.string "KANTO estuvo bajo el agua?$"

MatchCall_HNS_Kenny_Battle::
	.string "¡Hola, {PLAYER}! Soy KENNY.\p"

	.string "¡He entrenado duro en las\n"
	.string "montañas!\p"

	.string "¡Ven a combatir a la RUTA 13!$"

MatchCall_HNS_Joel_General1::
	.string "¡Hola, {PLAYER}! Soy JOEL.\p"

	.string "He practicado para lucirme en\n"
	.string "combate.\p"

	.string "¡{STR_VAR_3} tiene nuevos\n"
	.string "movimientos muy vistosos!$"

MatchCall_HNS_Joel_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "Soy JOEL.\p"

	.string "Ha habido un accidente en la\n"
	.string "RUTA CICLISTA.\p"

	.string "No hay nada más genial que ir\n"
	.string "con cuidado.$"

MatchCall_HNS_Joel_Battle::
	.string "¡Hola, {PLAYER}! Soy JOEL.\p"

	.string "¡Ahora luzco bien Y combato con\n"
	.string "estilo! ¡Ven a la RUTA CICLISTA!$"

MatchCall_HNS_Charles_General1::
	.string "¡Hola, {PLAYER}! Soy CHARLES.\p"

	.string "En TESELIA era todo un\n"
	.string "rompecorazones.\p"

	.string "¡Ahora soy la estrella de la\n"
	.string "carretera!$"

MatchCall_HNS_Charles_General2::
	.string "¡Hola, {PLAYER}!\p"

	.string "La RUTA CICLISTA de noche es\n"
	.string "otra cosa.\p"

	.string "Las farolas y el viento… ¡eso es\n"
	.string "libertad!$"

MatchCall_HNS_Charles_Battle::
	.string "¡Hola, {PLAYER}! Soy CHARLES.\p"

	.string "¡Las estrellas de la carretera\n"
	.string "quieren revancha! ¡Ven a la RUTA\l"
	.string "CICLISTA!$"
