MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Este movimiento solo puede\n"
	.string "aprenderse una vez. ¿De acuerdo?$"

MoveTutor_Text_SwaggerTeach:
	.string "¡Je! ¡Mi POKéMON es el mejor!\n"
	.string "¡Mola más que ningún otro!\p"
	.string "Iba presumiendo con mucho\n"
	.string "CONTONEO cuando el PRESIDENTE me\l"
	.string "echó una buena bronca.\p"
	.string "Se me quitaron las ganas de fardar.\p"
	.string "Si quieres, puedo enseñar\n"
	.string "CONTONEO a uno de tus POKéMON.$"

MoveTutor_Text_SwaggerDeclined:
	.string "¿No? ¿No sabes entrar en ambiente?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Muy bien. ¿Qué POKéMON quiere\n"
	.string "aprender CONTONEO?$"

MoveTutor_Text_SwaggerTaught:
	.string "A partir de ahora, alabaré a mi\n"
	.string "POKéMON sin presumir.$"

MoveTutor_Text_RolloutTeach:
	.string "¿Sabías que puedes avanzar mucho\n"
	.string "por ahí sin cambiar de dirección?\p"
	.string "Hasta yo podría ir rodando.\p"
	.string "¿Crees que tu POKéMON también\n"
	.string "querrá rodar?\p"
	.string "Puedo enseñarle DESENROLLAR,\n"
	.string "si quieres.$"

MoveTutor_Text_RolloutDeclined:
	.string "No tienes por qué cortarte.\n"
	.string "¡Vamos a rodar!$"

MoveTutor_Text_RolloutWhichMon:
	.string "¡Je, je! ¡Perfecto! ¿A qué\n"
	.string "POKéMON se lo enseño?$"

MoveTutor_Text_RolloutTaught:
	.string "Rodar por la hierba me hace feliz.\n"
	.string "¡Venga, vamos a rodar!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Hay un movimiento que se vuelve\n"
	.string "más fuerte si se usa seguido.\p"
	.string "Es de tipo BICHO y mola un montón.\p"
	.string "Se llama CORTEFURIA.\n"
	.string "¿Quieres que se lo enseñe a uno?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "No estamos en la misma onda.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "¡Bien!\n"
	.string "¿A qué POKéMON se lo enseño?$"

MoveTutor_Text_FuryCutterTaught:
	.string "¡Me emociona ver si CORTEFURIA\n"
	.string "sigue acertando una y otra vez!$"

MoveTutor_MimicTeach:
	.string "¡Ah, jovencito!\p"
	.string "Yo también soy joven, pero imito\n"
	.string "la forma de hablar y comportarse\l"
	.string "de los ancianos del pueblo.\p"
	.string "¿Qué me dices, jovencito?\n"
	.string "¿Quieres que enseñe MIMÉTICO a\l"
	.string "uno de tus POKéMON?$"

MoveTutor_MimicDeclined:
	.string "¡Oh, qué pena! ¡Quería enseñar\n"
	.string "MIMÉTICO a tu POKéMON!$"

MoveTutor_Text_MimicWhichMon:
	.string "¡Jo, jo! ¡Así se hará!\n"
	.string "Enséñame el POKéMON elegido.$"

MoveTutor_Text_MimicTaught:
	.string "MIMÉTICO es un movimiento profundo.\p"
	.string "¿Podrás hacerlo tan bien como yo?$"

MoveTutor_Text_MetronomeTeach:
	.string "¡Quiero un montón de cosas!\n"
	.string "Pero me he gastado la paga…\p"
	.string "¿No sería genial un hechizo que\n"
	.string "hiciera aparecer dinero al mover\l"
	.string "un dedo?\p"
	.string "Puedo enseñar METRÓNOMO a tu\n"
	.string "POKéMON, si quieres.\p"
	.string "No saldrá dinero, pero moverá\n"
	.string "el dedo. ¿Qué me dices?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Vale. Aquí estaré si cambias\n"
	.string "de opinión.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "¡Vale, se lo enseñaré!\n"
	.string "¿Qué POKéMON eliges?$"

MoveTutor_Text_MetronomeTaught:
	.string "Cuando un POKéMON mueve el dedo\n"
	.string "como un METRÓNOMO, pueden ocurrir\l"
	.string "cosas maravillosas.\p"
	.string "¡Ojalá pudiéramos usarlo nosotros!$"

MoveTutor_Text_SleepTalkTeach:
	.string "¡Hum! Mi mujer usa PODER OCULTO\n"
	.string "para mantenerse despierta.\p"
	.string "Debería echarse una siesta como yo\n"
	.string "y usar SONÁMBULO.\p"
	.string "Puedo enseñar SONÁMBULO a tu\n"
	.string "POKéMON. ¿Te interesa?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Vale, vale. Tú también quieres\n"
	.string "seguir despierto con PODER OCULTO…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "¡Ah, una criatura agradecida!\n"
	.string "¿A qué POKéMON se lo enseño?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Nunca me ha salido el truco de\n"
	.string "la moneda de mi mujer.\p"
	.string "Sería feliz si me saliera incluso\n"
	.string "mientras uso SONÁMBULO…$"

MoveTutor_Text_SubstituteTeach:
	.string "Cuando contemplo el mundo desde\n"
	.string "esta azotea…\p"
	.string "Pienso que sería genial que hubiera\n"
	.string "más de una como yo para vivir\l"
	.string "muchas vidas distintas.\p"
	.string "Claro que es imposible.\n"
	.string "Je, je…\p"
	.string "¡Ya sé! ¿Quieres que enseñe\n"
	.string "SUSTITUTO a uno de tus POKéMON?$"

MoveTutor_Text_SubstituteDeclined:
	.string "¿No?\p"
	.string "Con él, un POKéMON puede crear\n"
	.string "una copia de sí mismo.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Je, je…\n"
	.string "¿Qué POKéMON aprenderá SUSTITUTO?$"

MoveTutor_Text_SubstituteTaught:
	.string "¡Las personas debemos disfrutar\n"
	.string "nuestra vida al máximo!\p"
	.string "¡Espero que tú también lo hagas!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "¡No puedo seguir así!\p"
	.string "¡No tengo ninguna esperanza!\p"
	.string "Soy un ENTRENADOR de tipo LUCHA,\n"
	.string "así que nunca ganaré en este\l"
	.string "GIMNASIO por mucho que lo intente.\p"
	.string "¡Puño! ¡Puño! ¡Puño!\n"
	.string "¡Puño! ¡Puño! ¡Puño!\p"
	.string "¡Eh, no me mires así!\n"
	.string "¡Solo estoy golpeando el suelo!\p"
	.string "¿O quieres que enseñe PUÑO DINÁMICO\n"
	.string "a uno de tus POKéMON?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "¡Maldición! ¿Tú también te burlas?\n"
	.string "¡Puño! ¡Puño! ¡Puño!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "¿En serio? ¡Eres buena persona!\n"
	.string "¿A qué POKéMON se lo enseño?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "¡Gana en el GIMNASIO CELESTE usando\n"
	.string "ese PUÑO DINÁMICO!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Ay…\p"
	.string "El LÍDER del GIMNASIO es realmente\n"
	.string "encantador y admirable.\p"
	.string "Pero eso también significa que\n"
	.string "tengo muchas rivales.\p"
	.string "Su encanto es de DOBLE FILO.\n"
	.string "Ni siquiera logré que me mirara.\p"
	.string "¡Deja que enseñe DOBLE FILO\n"
	.string "a uno de tus POKéMON!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Tú también me rechazas…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "¿A qué POKéMON le enseño\n"
	.string "DOBLE FILO?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "¡No volveré a vivir por amor!\n"
	.string "¡Me haré más fuerte!$"

MoveTutor_Text_ExplosionTeach:
	.string "No pienso quedarme para siempre\n"
	.string "estancado en este pueblucho.\p"
	.string "Ya verás: iré a la ciudad y me\n"
	.string "convertiré en todo un éxito.\p"
	.string "¡Mi popularidad causará una\n"
	.string "auténtica EXPLOSIÓN!\p"
	.string "Ya que me has oído, enseñaré\n"
	.string "EXPLOSIÓN a uno de tus POKéMON.$"

MoveTutor_Text_ExplosionDeclined:
	.string "¡Aaah! ¿Me rechazas porque vivo\n"
	.string "en el campo?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "¡Bien! ¡Habrá una EXPLOSIÓN!\n"
	.string "¿Qué POKéMON quiere explotar?$"

MoveTutor_Text_ExplosionTaught:
	.string "Llevo mucho tiempo enseñando\n"
	.string "EXPLOSIÓN a los POKéMON, pero aún\l"
	.string "no he provocado la mía.\p"
	.string "Quizá sea porque, en el fondo,\n"
	.string "prefiero quedarme aquí…$"

MoveTutor_Text_HeadbuttTeach:
	.string "¿Qué estoy haciendo?\p"
	.string "Sacudo árboles con GOLPE CABEZA.\p"
	.string "¿Tu POKéMON también querrá\n"
	.string "dar cabezazos?\p"
	.string "Puedo enseñarle GOLPE CABEZA.\n"
	.string "¡Es divertido!$"

MoveTutor_Text_HeadbuttWhichMon:
	.string "¡Je, je! ¿A qué POKéMON quieres\n"
	.string "que se lo enseñe?$"

MoveTutor_Text_HeadbuttDeclined:
	.string "No seas tímido.\n"
	.string "¡Vamos a darnos cabezazos!$"

MoveTutor_Text_HeadbuttTaught:
	.string "Sacude árboles con GOLPE CABEZA.\n"
	.string "A veces caerán POKéMON dormidos.$"
