MoveRelearner_Text_WouldLearnNewMoves:
	.string "Hola, soy el Recuerda-Movimientos.\n"
	.string "¿Quieres recordar algún ataque?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Por nivel$"

MoveRelearner_Text_EggMoves:
	.string "Mov. Huevo$"

MoveRelearner_Text_TMMoves:
	.string "Mov. MT$"

MoveRelearner_Text_TutormoveMoves:
	.string "Mov. Tutor$"

MoveRelearner_Text_SeeYa:
	.string "¡Hasta luego!$"

MoveRelearner_Text_AnythingElse:
	.string "¿Puedo ayudarte en algo más?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Elige un Pokémon, por favor.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "No llevas ningún Pokémon.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Lo siento…\n"
	.string "Un Huevo no puede aprender ataques.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Lo siento…\p"
	.string "No parece que ese Pokémon pueda\n"
	.string "recordar ningún movimiento.$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "movimiento$"

MoveRelearner_Text_EggMoveLWR::
	.string "movimiento huevo$"

MoveRelearner_Text_TMMoveLWR::
	.string "movimiento MT$"

MoveRelearner_Text_TutorMoveLWR::
	.string "movimiento tutor$"

MoveRelearner_Text_MoveLWR::
	.string "movimiento$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "¿Qué {STR_VAR_3} debería recordar?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "¡Vuelve cuando quieras!$"
