gText_Oak_Welcome::
	.string "¡Hola! ¡Perdona la espera!\p"
	.string "¡Te doy la bienvenida al mundo de POKéMON!\p"
	.string "Me llamo OAK.\p"
	.string "La gente me llama el PROFESOR\n"
	.string "POKéMON.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "A esto lo llamamos un “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "Este mundo está habitado por criaturas\n"
	.string "llamadas POKéMON.\p"
	.string "Los humanos y los POKéMON vivimos juntos,\n"
	.string "apoyándonos unos a otros.\p"
	.string "Algunos juegan con POKéMON,\n"
	.string "otros luchan con ellos.\p"
	.string "Pero aún no lo sabemos todo sobre\n"
	.string "los POKéMON.\p"
	.string "Todavía quedan muchos misterios por\n"
	.string "resolver. Por eso estudio a los\l"
	.string "POKéMON cada día.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "¿Y tú eres?$"

gText_Oak_BoyOrGirl::
	.string "¿Eres un chico?\n"
	.string "¿O eres una chica?$"

gText_Oak_WhatChallenge::
	.string "¿Qué desafío esperas?$"

gText_Oak_ChallengeSelected::
	.string "¡Eso me parece el nivel de\n"
	.string "desafío adecuado!$" 

gText_Oak_WhatsYourName::
	.string "¿Y cuál es tu nombre?$"

gText_Oak_SoItsPlayer::
	.string "¡Oh! ¿Así que eres {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}, ¿estás a punto?\p"
	.string "Tu propia aventura está a punto de\n"
	.string "comenzar.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "Encontrarás momentos divertidos y\n"
	.string "desafíos difíciles.\p"
	.string "¡Un mundo de sueños y aventuras\n"
	.string "con POKéMON te aguarda! ¡Vamos!\p"
	.string "¡Nos veremos más adelante!\p"
	.string "$"
