gText_Oak_Welcome::
	.string "¡Hola! ¡Siento haberte hecho esperar!\p"
	.string "¡Te doy la bienvenida al mundo\n"
	.string "de los POKéMON!\p"
	.string "Me llamo OAK.\p"
	.string "La gente me llama el PROFESOR\n"
	.string "POKéMON.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "A esto lo llamamos un “POKéMON”.\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "Este mundo está habitado por\n"
	.string "criaturas llamadas POKéMON.\p"
	.string "Los humanos y los POKéMON viven\n"
	.string "juntos prestándose ayuda.\p"
	.string "Algunos juegan con los POKéMON,\n"
	.string "otros luchan con ellos.\p"
	.string "Pero aún no lo sabemos todo sobre\n"
	.string "los POKéMON.\p"
	.string "Aún quedan muchos misterios por\n"
	.string "resolver. ¡Por eso investigo a los\l"
	.string "POKéMON todos los días!\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "¿Y tú quién eres?$"

gText_Oak_BoyOrGirl::
	.string "¿Eres un chico?\n"
	.string "¿O eres una chica?$"

gText_Oak_WhatChallenge::
	.string "¿Qué clase de desafío estás\n"
	.string "esperando?$"

gText_Oak_ChallengeSelected::
	.string "¡Me parece el nivel de desafío\n"
	.string "perfecto para ti!$" 

gText_Oak_WhatsYourName::
	.string "¿Y cómo te llamas?$"

gText_Oak_SoItsPlayer::
	.string "¡Ah! ¿Así que eres {PLAYER}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}, ¿estás a punto?\p"
	.string "Tu propia aventura está a punto\n"
	.string "de comenzar.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "Pasarás momentos muy divertidos y\n"
	.string "afrontarás duros desafíos.\p"
	.string "¡Te aguarda un mundo de sueños y\n"
	.string "aventuras junto a los POKéMON!\p"
	.string "¡Nos veremos más adelante!\p"
	.string "$"
