gText_ObtainedTheItem::
	.string "¡Has obtenido {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "La BOLSA está llena…$"

gText_PutItemInPocket::
	.string "{PLAYER} guardó {STR_VAR_2}\n"
	.string "en el BOLSILLO {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "¡Qué pena!\n"
	.string "La BOLSA está llena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} guardó {STR_VAR_2}\n"
	.string "en la BOLSA.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "¡Has obtenido {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "¡{PLAYER} encontró {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"

gText_FoundXCoins::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"

gText_NothingToPutThemIn::
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"
