Text_BootUpPC:
	.string "¡{PLAYER} encendió el PC!$"

gText_WhichPCShouldBeAccessed::
	.string "¿A qué PC deseas acceder?$"

gText_AccessedSomeonesPC::
	.string "Accediste al PC DE ALGUIEN.$"

gText_StorageSystemOpened::
	.string "Se abrió el Sistema de\n"
	.string "Almacenamiento POKéMON.$"

gText_AccessedPlayersPC::
	.string "Accediste al PC de {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Accediste al PC de AREDIA.$"

gText_AccessedBillsPC::
	.string "Accediste al PC de BILL.$"
