gText_WouldYouLikeToRestYourPkmn::
	.string "¡Hola! Te damos la bienvenida\n"
	.string "al CENTRO POKéMON.\p"
	.string "Aquí recuperamos la salud de tus\n"
	.string "cansados POKéMON.\p"
	.string "¿Quieres que nos ocupemos de ellos?$"

gText_IllTakeYourPkmn::
	.string "Muy bien, déjame a tus POKéMON\n"
	.string "unos segundos.$"

gText_RestoredPkmnToFullHealth::
	.string "Gracias por esperar.\p"
	.string "¡Tus POKéMON están rebosantes\n"
	.string "de energía!$"

gText_WeHopeToSeeYouAgain::
	.string "¡Esperamos verte de nuevo!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "¡Me alegra verte, {PLAYER}!\n"
	.string "Lo de siempre, ¿verdad?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Gracias por esperar.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Sorry, but you are playing with\n"
    .string "the POKéCENTER challenge!\p"
    .string "Good luck!{PAUSE_UNTIL_PRESS}$"
