	.align 2
gText_ConfirmSave::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOff::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} guardó la partida.$"

gText_DifferentSaveFile::
	.string "¡ATENCIÓN!\p"
	.string "Ya existe un archivo guardado con\n"
	.string "otra partida diferente.\p"
	.string "Si guardas ahora, la aventura anterior,\n"
	.string "incluyendo objetos y POKéMON,\l"
	.string "se perderá para siempre.\p"
	.string "¿Seguro que quieres sobrescribirla?$"

gText_SaveError::
	.string "Error al guardar.\p"
	.string "Por favor, revisa la\n"
	.string "memoria de respaldo.$"

gText_SavingDontTurnOffPower::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"
