FuchsiaCity_House1_hns_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_BillsOlderSister::
	msgbox FuchsiaCity_House1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Youngster::
	msgbox FuchsiaCity_House1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_BillsOlderSister:
	.string "Mi abuelo está con mi hermano BILL\n"
	.string "en el CABO CELESTE.$"

FuchsiaCity_House1_Text_Youngster:
	.string "Vi unos POKéMON raros y lentos en\n"
	.string "el CARRIL BICI.$"
