VermilionCity_House1_hns_MapScripts::
	.byte 0

VermilionCity_House1_EventScript_Fisher::
	msgbox VermilionCity_House1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCity_House1_EventScript_Photo::
	msgbox VermilionCity_House1_Text_Photo, MSGBOX_NPC
	end
VermilionCity_House1_Text_FishingDude:
	.string "Soy el PESCADOR, el mayor de los\n"
	.string "HERMANOS PESCADORES.\p"
	.string "¿Conoces al GURÚ PESCADOR del\n"
	.string "LAGO DE LA FURIA?\p"
	.string "Sueña con ver al mejor MAGIKARP\n"
	.string "del mundo.\p"
	.string "¿Podrías enseñarle los MAGIKARP\n"
	.string "que captures?\p"
	.string "Quién sabe, quizá captures el\n"
	.string "MAGIKARP de sus sueños.$"

VermilionCity_House1_Text_Photo:
	.string "Es una foto de gente pescando…\p"
	.string "Parece que se lo pasan genial…$"
