LavenderTown_House2_hns_MapScripts::
	.byte 0

LavenderTown_House2_EventScript_Woman::
	msgbox LavenderSpeechHouse_Text_PokefanF, MSGBOX_NPC
	end

LavenderSpeechHouse_Text_PokefanF:
	.string "El PUEBLO LAVANDA\n"
	.string "es un pequeño y\p"
	.string "apacible lugar,\n"
	.string "al pie de las\l"
	.string "montañas.\p"
	.string "Desde que se\n"
	.string "construyó la TORRE\p"
	.string "RADIO, acude algo\n"
	.string "más de gente.$"
