DiglettsCave_EntranceNorth_hns_MapScripts::
	.byte 0


DiglettsCave_EntranceNorth_EventScript_Brock::
    lock
    faceplayer
    msgbox DiglettsCave_EntranceNorth_Text_Brock, MSGBOX_DEFAULT
    closemessage
    fadescreenswapbuffers FADE_TO_BLACK
    setflag FLAG_HIDE_DIGLETT_BROCK
    removeobject LOCALID_DIGLETT_BROCK
    fadescreenswapbuffers FADE_FROM_BLACK
    clearflag FLAG_HIDE_DOJO_BROCK
    release
    end

DiglettsCave_EntranceNorth_Text_Brock:
    .string "BROCK: Los rincones pequeños\n"
    .string "rodeados de rocas transmiten paz,\l"
    .string "¿no crees?\p"
	.string "Si quieres la revancha, estaré\n"
	.string "en el DOJO KARATE.$"



