BlackthornCity_House1_hns_MapScripts::
	.byte 0

BlackthornCity_House1EventScript_Granny::
	msgbox BlackthornCity_House1_Text_Granny, MSGBOX_NPC
	end

BlackthornCity_House1EventScript_Dratini::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_DRATINI, CRY_MODE_NORMAL
	msgbox BlackthornCity_House1_Text_Dratini, MSGBOX_DEFAULT
	waitmoncry
	release
	end

BlackthornCity_House1_Text_Granny:
	.string "Aquí, en ENDRINO, vive un clan de\n"
	.string "Entrenadores que domina a los\l"
	.string "dragones.\p"
	.string "Por eso este pueblo está lleno de\n"
	.string "leyendas sobre dragones.$"

BlackthornCity_House1_Text_Dratini:
	.string "DRATINI: ¡Draaa!$"
