CeruleanCity_Mart_hns_MapScripts::
	.byte 0

CeruleanCity_Mart_EventScript_Juggler::
	msgbox CeruleanMart_Text_CooltrainerM, MSGBOX_NPC
	end

CeruleanCity_Mart_EventScript_CooltrainerF::
	msgbox CeruleanMart_Text_CooltrainerF, MSGBOX_NPC
	end

CeruleanMart_Text_CooltrainerM:
	.string "Encontrarás muchos\n"
	.string "entrenadores de\p"
	.string "camino hacia\n"
	.string "CABO CELESTE.\p"
	.string "Quieren saber cómo\n"
	.string "son en comparación\p"
	.string "con otros\n"
	.string "entrenadores.$"
CeruleanMart_Text_CooltrainerF:
	.string "MISTY es casi la\n"
	.string "única persona de\p"
	.string "la ciudad capaz de\n"
	.string "vencer a los\p"
	.string "ENTRENADORES de\n"
	.string "CABO CELESTE.$"
