LavenderTown_Mart_hns_MapScripts::
	.byte 0

LavenderTown_Mart_EventScript_Pokefan::
	msgbox LavenderMart_Text_PokefanM, MSGBOX_NPC
	end

LavenderTown_Mart_EventScript_Rocker::
	msgbox LavenderMart_Text_Rocker, MSGBOX_NPC
	end

LavenderMart_Text_PokefanM:
	.string "Si vas a explorar\n"
	.string "una cueva, debes\p"
	.string "llevar siempre\n"
	.string "REPELENTE.\p"
	.string "Aunque me gusta la\n"
	.string "exploración, aún\p"
	.string "no he recorrido\n"
	.string "todas las cuevas.$"
LavenderMart_Text_Rocker:
	.string "He oído hablar de\n"
	.string "un artesano que\p"
	.string "fabrica POKé BALL\n"
	.string "a medida en PUEBLO\p"
	.string "AZALEA, en JOHTO.\n"
	.string "¡Yo quiero una!$"
