Route15_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route15_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

Route15_OnTransition:
	callnative SetTimeBasedEncounters
	end

Route15_EventScript_Colette::
	trainerbattle_single TRAINER_COLETTE_HNS, Route15_Text_TeacherColetteSeen, Route15_Text_TeacherColetteBeaten
	msgbox Route15_Text_TeacherColetteAfterBattle, MSGBOX_AUTOCLOSE
	end

Route15_EventScript_Hillary::
	trainerbattle_single TRAINER_HILLARY_HNS, Route15_Text_TeacherHillarySeen, Route15_Text_TeacherHillaryBeaten, Route15_EventScript_RegisterHillary
	specialvar VAR_RESULT, ShouldTryRematchBattle
	goto_if_eq VAR_RESULT, TRUE, Route15_EventScript_RematchHillary
	msgbox Route15_Text_TeacherHillaryAfterBattle, MSGBOX_AUTOCLOSE
	end

Route15_EventScript_RegisterHillary::
	special PlayerFaceTrainerAfterBattle
	waitmovement 0
	msgbox Route15_Text_HillaryRegister, MSGBOX_DEFAULT
	register_matchcall TRAINER_HILLARY_HNS
	release
	end

Route15_EventScript_RematchHillary::
	trainerbattle_rematch TRAINER_HILLARY_HNS, Route15_Text_HillaryRematchIntro, Route15_Text_HillaryRematchDefeat
	msgbox Route15_Text_HillaryPostRematch, MSGBOX_AUTOCLOSE
	goto_if_defeated TRAINER_HILLARY_2_HNS, Route15_EventScript_RematchHillaryTryGiveItem
	end

Route15_EventScript_RematchHillaryTryGiveItem::
	checkitem ITEM_TM_ENERGY_BALL
	goto_if_eq VAR_RESULT, TRUE, Common_EventScript_NoOp
	giveitem ITEM_TM_ENERGY_BALL
	closemessage
	end

Route15_EventScript_Kipp::
	trainerbattle_single TRAINER_KIPP_HNS, Route15_Text_SchoolboyKippSeen, Route15_Text_SchoolboyKippBeaten
	msgbox Route15_Text_SchoolboyKippAfterBattle, MSGBOX_AUTOCLOSE
	end

Route15_EventScript_Tommy::
	trainerbattle_single TRAINER_TOMMY_HNS, Route15_Text_SchoolboyTommySeen, Route15_Text_SchoolboyTommyBeaten
	msgbox Route15_Text_SchoolboyTommyAfterBattle, MSGBOX_AUTOCLOSE
	end

Route15_EventScript_Johnny::
	trainerbattle_single TRAINER_JOHNNY_HNS, Route15_Text_SchoolboyJohnnySeen, Route15_Text_SchoolboyJohnnyBeaten
	msgbox Route15_Text_SchoolboyJohnnyAfterBattle, MSGBOX_AUTOCLOSE
	end

Route15_EventScript_Billy::
	trainerbattle_single TRAINER_BILLY_HNS, Route15_Text_SchoolboyBillySeen, Route15_Text_SchoolboyBillyBeaten, Route15_EventScript_RegisterBilly
	specialvar VAR_RESULT, ShouldTryRematchBattle
	goto_if_eq VAR_RESULT, TRUE, Route15_EventScript_RematchBilly
	msgbox Route15_Text_SchoolboyBillyAfterBattle, MSGBOX_AUTOCLOSE
	end

Route15_EventScript_RegisterBilly::
	special PlayerFaceTrainerAfterBattle
	waitmovement 0
	msgbox Route15_Text_BillyRegister, MSGBOX_DEFAULT
	register_matchcall TRAINER_BILLY_HNS
	release
	end

Route15_EventScript_RematchBilly::
	trainerbattle_rematch TRAINER_BILLY_HNS, Route15_Text_BillyRematchIntro, Route15_Text_BillyRematchDefeat
	msgbox Route15_Text_BillyPostRematch, MSGBOX_AUTOCLOSE
	goto_if_defeated TRAINER_BILLY_2_HNS, Route15_EventScript_RematchBillyTryGiveItem
	end

Route15_EventScript_RematchBillyTryGiveItem::
	checkitem ITEM_TM_FACADE
	goto_if_eq VAR_RESULT, TRUE, Common_EventScript_NoOp
	giveitem ITEM_TM_FACADE
	closemessage
	end

Route15_EventScript_Sign::
	msgbox Route15_Text_Sign, MSGBOX_SIGN
	end

Route15_EventScript_PPup::
	finditem ITEM_PP_UP
	end

Route15_Text_TeacherColetteSeen:
	.string "¿Has olvidado"
	.string "\n$algo?"
Route15_Text_TeacherColetteBeaten:
	.string "Kyaaah!$"

Route15_Text_TeacherColetteAfterBattle:
	.string "Antes de ser maestra, solía\n"
	.string "olvidarme de muchas cosas.$"

Route15_Text_TeacherHillarySeen:
	.string "Creo que si hace"
	.string "\nsol, los niños"
	.string "\pdeberían estar"
	.string "\njugando en el"
	.string "\ppatio en lugar"
	.string "\n$de estar en clase."
Route15_Text_TeacherHillaryBeaten:
	.string "$No quería perder…"
Route15_Text_TeacherHillaryAfterBattle:
	.string "Es importante"
	.string "\nestudiar, pero"
	.string "\phacer deporte"
	.string "\n$también."
Route15_Text_HillaryRegister:
	.string "¡Me has dado una lección!\n"
	.string "¿Me das tu número?$"

Route15_Text_HillaryRematchIntro:
	.string "¡Esta vez te daré yo la lección!$"

Route15_Text_HillaryRematchDefeat:
	.string "Vuelta a empezar…$"

Route15_Text_HillaryPostRematch:
	.string "Enseñar a POKéMON es como enseñar\n"
	.string "a niños. ¡Hace falta paciencia!$"

Route15_Text_SchoolboyKippSeen:
	.string "Espera. Tengo que"
	.string "\n$llamar a mamá."
Route15_Text_SchoolboyKippBeaten:
	.string "¡Lo siento, mamá!"
	.string "\n$¡Me han vencido!"
Route15_Text_SchoolboyKippAfterBattle:
	.string "Mi madre se"
	.string "\npreocupa mucho por"
	.string "\pmí, tengo que"
	.string "\n$llamarla siempre."
Route15_Text_SchoolboyTommySeen:
	.string "Luchemos."
	.string "\n$¡No perderé!"
Route15_Text_SchoolboyTommyBeaten:
	.string "¡Olvidé hacer los deberes!$"

Route15_Text_SchoolboyTommyAfterBattle:
	.string "¡Sayonara! Lo he"
	.string "\naprendido en la"
	.string "\l$clase de japonés."
Route15_Text_SchoolboyJohnnySeen:
	.string "Vamos de excursión a la TORRE\n"
	.string "RADIO de LAVANDA.$"

Route15_Text_SchoolboyJohnnyBeaten:
	.string "¡Eres demasiado"
	.string "\n$fuerte!"
Route15_Text_SchoolboyJohnnyAfterBattle:
	.string "Estoy cansado de caminar.\n"
	.string "Necesito descansar.$"

Route15_Text_SchoolboyBillySeen:
	.string "¡Mi asignatura favorita es\n"
	.string "gimnasia!$"

Route15_Text_SchoolboyBillyBeaten:
	.string "¡Oh, no! ¿Cómo pude perder?$"

Route15_Text_SchoolboyBillyAfterBattle:
	.string "¡Si los POKéMON"
	.string "\nfueran una"
	.string "\pasignatura, yo"
	.string "\n$sería el mejor!"
Route15_Text_BillyRegister:
	.string "Debí prestar más atención en clase.\n"
	.string "¿Me das tu número?$"

Route15_Text_BillyRematchIntro:
	.string "¡He estudiado mucho!\n"
	.string "¡Te enseñaré lo que aprendí!$"

Route15_Text_BillyRematchDefeat:
	.string "Necesito estudiar más…$"

Route15_Text_BillyPostRematch:
	.string "Los libros no lo son todo.\n"
	.string "¡También necesito luchar!$"

Route15_Text_Sign:
	.string "RUTA 15"
	.string "\pCIUDAD FUCSIA -"
	.string "\n$PUEBLO LAVANDA"
