#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("SAPPHIRE");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("RUBY");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("EMERALD");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("AQUA");
const u8 gText_ExpandedPlaceholder_Magma[] = _("MAGMA");
const u8 gText_ExpandedPlaceholder_Archie[] = _("ARCHIE");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("MAXIE");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("KYOGRE");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("GROUDON");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("BRENDAN");
const u8 gText_ExpandedPlaceholder_May[] = _("MAY");
const u8 gText_ExpandedPlaceholder_Red[] = _("RED");
const u8 gText_ExpandedPlaceholder_Green[] = _("GREEN");
const u8 gText_ExpandedPlaceholder_Silver[] = _("SILVER");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("EGG");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("POKéMON");
const u8 gText_Player[] = _("PLAYER"); // Unused
const u8 gText_Pokedex[] = _("POKéDEX"); // Unused
const u8 gText_Time[] = _("TIME");
const u8 gText_Badges[] = _("BADGES"); // Unused
const u8 gText_AButton[] = _("A Button"); // Unused
const u8 gText_BButton[] = _("B Button"); // Unused
const u8 gText_RButton[] = _("R Button"); // Unused
const u8 gText_LButton[] = _("L Button"); // Unused
const u8 gText_Start[] = _("START"); // Unused
const u8 gText_Select[] = _("SELECT"); // Unused
const u8 gText_ControlPad[] = _("+ Control Pad"); // Unused
const u8 gText_LButtonRButton[] = _("L Button  R Button"); // Unused
const u8 gText_Controls[] = _("CONTROLS"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}NEXT");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}NEXT {B_BUTTON}BACK");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}NEXT {B_BUTTON}CANCEL");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}{B_BUTTON}CANCEL");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}EXIT");
const u8 gText_Boy[] = _("CHICO");
const u8 gText_Girl[] = _("CHICA");
const u8 gText_ThisIsAPokemon[] = _("A esto lo llamamos un “POKéMON”.{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("????? POKéMON");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 0x0C}??'??”");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("????.? lbs.");
const u8 gText_UnkWeightMetric[] = _("???.? kg.");
const u8 gText_EmptyPkmnCategory[] = _("                       POKéMON"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 0x0C}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("GRITO DE");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("TAMAÑO COMPARADO CON ");
const u8 gText_PokedexRegistration[] = _("Registro en Pokédex completado.");
const u8 gText_HTHeight[] = _("ALT.");
const u8 gText_WTWeight[] = _("PESO");
const u8 gText_SearchingPleaseWait[] = _("Buscando…\nPor favor espera.");
const u8 gText_SearchCompleted[] = _("Búsqueda completada.");
const u8 gText_NoMatchingPkmnWereFound[] = _("No se encontraron POKéMON coincidentes.");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("Busca POKéMON según los\nparámetros seleccionados.");
const u8 gText_SwitchPokedexListings[] = _("Cambia el listado de la POKéDEX.");
const u8 gText_ReturnToPokedex[] = _("Vuelve a la POKéDEX.");
const u8 gText_SelectPokedexMode[] = _("Elige el modo de POKéDEX.");
const u8 gText_SelectPokedexListingMode[] = _("Elige el modo de orden de POKéDEX.");
const u8 gText_ListByFirstLetter[] = _("Ordena por la primera letra del nombre.\nSolo POKéMON avistados.");
const u8 gText_ListByBodyColor[] = _("Ordena por color del cuerpo.\nSolo POKéMON avistados.");
const u8 gText_ListByType[] = _("Ordena por tipo.\nSolo POKéMON atrapados.");
const u8 gText_ExecuteSearchSwitch[] = _("Ejecuta la búsqueda/cambio.");
#if IS_HNS
const u8 gText_DexHoennTitle[] = _("DEX DE JOHTO");
#else
const u8 gText_DexHoennTitle[] = _("DEX DE HOENN");
#endif
const u8 gText_DexNatTitle[] = _("DEX NACIONAL");
const u8 gText_DexSortNumericalTitle[] = _("MODO NUMÉRICO");
const u8 gText_DexSortAtoZTitle[] = _("MODO A A LA Z");
const u8 gText_DexSortHeaviestTitle[] = _("MODO MÁS PESADOS");
const u8 gText_DexSortLightestTitle[] = _("MODO MÁS LIGEROS");
const u8 gText_DexSortTallestTitle[] = _("MODO MÁS ALTOS");
const u8 gText_DexSortSmallestTitle[] = _("MODO MÁS BAJOS");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DEF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchColorRed[] = _("ROJO");
const u8 gText_DexSearchColorBlue[] = _("AZUL");
const u8 gText_DexSearchColorYellow[] = _("AMARILLO");
const u8 gText_DexSearchColorGreen[] = _("VERDE");
const u8 gText_DexSearchColorBlack[] = _("NEGRO");
const u8 gText_DexSearchColorBrown[] = _("MARRÓN");
const u8 gText_DexSearchColorPurple[] = _("MORADO");
const u8 gText_DexSearchColorGray[] = _("GRIS");
const u8 gText_DexSearchColorWhite[] = _("BLANCO");
const u8 gText_DexSearchColorPink[] = _("ROSA");
#if IS_HNS
const u8 gText_DexHoennDescription[] = _("POKéDEX de la región de JOHTO");
#else
const u8 gText_DexHoennDescription[] = _("POKéDEX de la región de HOENN");
#endif
const u8 gText_DexNatDescription[] = _("POKéDEX edición Nacional");
const u8 gText_DexSortNumericalDescription[] = _("Los POKéMON se ordenan según su\nnúmero.");
const u8 gText_DexSortAtoZDescription[] = _("POKéMON vistos y atrapados se ordenan\nalfabéticamente.");
const u8 gText_DexSortHeaviestDescription[] = _("POKéMON atrapados se ordenan del\nmás pesado al más ligero.");
const u8 gText_DexSortLightestDescription[] = _("POKéMON atrapados se ordenan del\nmás ligero al más pesado.");
const u8 gText_DexSortTallestDescription[] = _("POKéMON atrapados se ordenan del\nmás alto al más bajo.");
const u8 gText_DexSortSmallestDescription[] = _("POKéMON atrapados se ordenan del\nmás bajo al más alto.");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("SIN ESPECIFICAR");
const u8 gText_DexSearchTypeNone[] = _("NINGUNO");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("¡Bienvenido al SALÓN DE LA FAMA!");
const u8 gText_HOFDexRating[] = _("POKéMON avistados: {STR_VAR_1}!\nPOKéMON atrapados: {STR_VAR_2}!\p¡Evaluación de la POKéDEX del PROF. ELM!\pPROF. ELM: Veamos…\p");
const u8 gText_HOFDexSaving[] = _("GUARDANDO…\nNO APAGUES LA CONSOLA.");
const u8 gText_HOFCorrupted[] = _("Los datos del SALÓN DE LA FAMA están dañados.");
const u8 gText_HOFNumber[] = _("SALÓN DE LA FAMA N.º {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("¡CAMPEÓN DE LA LIGA!\n¡ENHORABUENA!");
const u8 gText_Number[] = _("N.º ");
const u8 gText_Level[] = _("Nv. ");
const u8 gText_IdNumberSlash[] = _("N.º ID /"); // Unused
const u8 gText_Name[] = _("NOMBRE");
const u8 gText_IDNumber[] = _("N.º ID");
const u8 gText_BirchInTrouble[] = _("¡El PROF. ELM está en apuros!\n¡Elige un POKéMON y sálvalo!");
const u8 gText_ConfirmStarterChoice[] = _("¿Eliges a este POKéMON?");
const u8 gText_Pokemon4[] = _("POKéMON"); // Unused
const u8 gText_FlyToWhere[] = _("FLY to where?");
const u8 gMenuText_Use[] = _("USAR");
const u8 gMenuText_Toss[] = _("TIRAR");
const u8 gMenuText_Register[] = _("ASIGNAR");
const u8 gMenuText_Give[] = _("DAR");
const u8 gMenuText_Confirm[] = _("CONFIRMAR");
const u8 gText_Cancel[] = _("CANCELAR");
const u8 gText_Cancel2[] = _("CANCELAR");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("NINGUNO");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{LV}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 0x01}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("Vuelve al menú\nanterior.");
const u8 gText_WhatWouldYouLike[] = _("¿Qué te gustaría hacer?");
const u8 gMenuText_Give2[] = _("DAR");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" BAYA"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1} FICHAS");
const u8 gText_CloseBag[] = _("CERRAR MOCHILA");
const u8 gText_Var1IsSelected[] = _("Has seleccionado\n{STR_VAR_1}.");
const u8 gText_CantWriteMail[] = _("No puedes escribir\nCARTAS aquí.");
const u8 gText_NoPokemon[] = _("No tienes ningún\nPOKéMON.");
const u8 gText_MoveVar1Where[] = _("¿Dónde quieres mover\n{STR_VAR_1}?");
const u8 gText_Var1CantBeHeld[] = _("No se puede equipar {STR_VAR_1}.");
const u8 gText_TossHowManyVar1s[] = _("¿Cuántas unidades de\n{STR_VAR_1} quieres tirar?");
const u8 gText_ThrewAwayVar2Var1s[] = _("Tiraste {STR_VAR_2}\n{STR_VAR_1}.");
const u8 gText_ConfirmTossItems[] = _("¿Seguro que quieres\ntirar {STR_VAR_2}\n{STR_VAR_1}?");
#if IS_HNS
    const u8 gText_DadsAdvice[] = _("Consejo de ELM…\n¡{PLAYER}, cada cosa a su tiempo y en\lsu lugar!{PAUSE_UNTIL_PRESS}");
#else
    const u8 gText_DadsAdvice[] = _("Consejo de PAPÁ…\n¡{PLAYER}, cada cosa a su tiempo y en\lsu lugar!{PAUSE_UNTIL_PRESS}");
#endif
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} usó\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("Pero el efecto del REPELENTE\ntodavía perdura.{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("Pero el efecto del CEBO\ntodavía perdura.{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("La CAJA está llena.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("el campo");
const u8 gText_TheBattle[] = _("el combate");
const u8 gText_ThePokemonList[] = _("la LISTA POKéMON");
const u8 gText_TheShop[] = _("la tienda");
const u8 gText_ThePC[] = _("el PC");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Volver a\n{STR_VAR_1}.");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS] =        COMPOUND_STRING("OBJETOS"),
    [POCKET_POKE_BALLS] =   COMPOUND_STRING("POKé BALLS"),
    [POCKET_TM_HM]  =       COMPOUND_STRING("MT & MO"),
    [POCKET_BERRIES] =      COMPOUND_STRING("BAYAS"),
    [POCKET_KEY_ITEMS] =    COMPOUND_STRING("OBJ. CLAVE"),
    [POCKET_MEDICINE] =     COMPOUND_STRING("MEDICINA"),
#if I_COMBINE_BAG_POCKETS == FALSE
    [POCKET_BATTLE_ITEMS] = COMPOUND_STRING("COMBATE"),
    [POCKET_TREASURES] =    COMPOUND_STRING("TESOROS"),
#endif
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 0x03}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 0x11}{STR_VAR_1}{CLEAR 0x05}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("COMPRAR");
const u8 gText_ShopSell[] = _("VENDER");
const u8 gText_ShopQuit[] = _("SALIR");
const u8 gText_ThatItemIsSoldOut[] = _("Lo siento, ese objeto está agotado.{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("AGOTADO");
const u8 gText_InBagVar1[] = _("EN MOCHILA: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("Salir de la tienda.");
const u8 gText_Var1CertainlyHowMany[] = _("¿{STR_VAR_1}? De acuerdo.\n¿Cuántos quieres?");
const u8 gText_Var1CertainlyHowMany2[] = _("¿{STR_VAR_1}? De acuerdo.\n¿Cuántos quieres?");
const u8 gText_Var1AndYouWantedVar2[] = _("¿{STR_VAR_1}? ¿Quieres {STR_VAR_2}?\nSerán ¥{STR_VAR_3}.");
const u8 gText_Var1AndYouWantedVar2BP[] = _("¿{STR_VAR_1}? ¿Quieres {STR_VAR_2}?\nSerán {STR_VAR_3} BP.");
const u8 gText_Var1IsItThatllBeVar2[] = _("¿{STR_VAR_1}?\nSerán ¥{STR_VAR_2}. ¿Lo quieres?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("¿Querías {STR_VAR_1}?\nSerán ¥{STR_VAR_2}. ¿Te parece bien?");
const u8 gText_YouWantedVar1ThatllBeVar2BP[] = _("¿Querías {STR_VAR_1}?\nSerán {STR_VAR_2} BP. ¿Te parece bien?");
const u8 gText_HereYouGoThankYou[] = _("¡Aquí tienes!\nMuchas gracias.");
const u8 gText_ThankYouIllSendItHome[] = _("¡Gracias!\nLo enviaré al PC de tu casa.");
const u8 gText_ThanksIllSendItHome[] = _("¡Gracias!\nLo enviaré a tu PC en casa.");
const u8 gText_YouDontHaveMoney[] = _("No tienes suficiente dinero.{PAUSE_UNTIL_PRESS}");
const u8 gText_YouDontHaveEnoughBP[] = _("No tienes suficientes\nBP.{PAUSE_UNTIL_PRESS}");
const u8 gText_DontHaveEnoughVar1[] = _("No tienes suficientes\n{STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_Var1SureHowMany[] = _("¿{STR_VAR_1}? Claro.\n¿Cuántos quieres?");
const u8 gText_xOne[] = _("x1");
const u8 gText_xFive[] = _("x5");
const u8 gText_KurtVar1AndYouWantedVar2Plural[] = _("¿Y quieres {STR_VAR_2} de esos?\nSerán {STR_VAR_3} bayas.");
const u8 gText_KurtVar1AndYouWantedVar2Singular[] = _("¿Y quieres {STR_VAR_2} de ese?\nSerá {STR_VAR_3} baya.");
const u8 gText_KurtGettingStarted[] = _("CÉSAR: ¡Me pongo a ello ahora mismo!");
const u8 gText_ExitMenu[] = _("SALIR DEL MENÚ");
const u8 gText_NoMoreRoomForThis[] = _("No tienes espacio para este\nobjeto.{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("El espacio para {STR_VAR_1} está lleno.{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("¿Puedo ayudarte en algo más?");
const u8 gText_CanIHelpWithAnythingElse[] = _("¿Puedo ayudarte con alguna otra cosa?");
const u8 gText_ThrowInPremierBall[] = _("¡Te regalaré una HONOR BALL también!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("¡Te regalaré {STR_VAR_1} HONOR BALLS también!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("¿{STR_VAR_2}? Ah, no.\nNo puedo comprar eso.{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("¿{STR_VAR_2}?\n¿Cuántos te gustaría vender?");
const u8 gText_ICanPayVar1[] = _("Puedo pagarte ¥{STR_VAR_1}.\n¿Te parece bien?");
const u8 gText_TurnedOverVar1ForVar2[] = _("Entregaste {STR_VAR_2}\ny recibiste ¥{STR_VAR_1}.");
const u8 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u8 gText_HP3[] = _("PS");
const u8 gText_SpAtk3[] = _("AT. ESP.");
const u8 gText_SpDef3[] = _("DEF. ESP.");
const u8 gText_WontHaveEffect[] = _("No tendrá ningún efecto.{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("Elige POKéMON para fusionar.");
const u8 gText_CantBeUsedOnPkmn[] = _("Esto no se puede usar en\nese POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("¡{STR_VAR_1} no puede cambiar!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("¡{STR_VAR_1} ya está\nen combate!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} ya ha sido\nseleccionado.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("¡{STR_VAR_1} no tiene energía\npara combatir!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("¡No puedes cambiar el POKéMON de\n{STR_VAR_1} con uno de los tuyos!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("¡Un HUEVO no puede combatir!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("Esto no se puede usar hasta conseguir\nuna nueva MEDALLA.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("No pueden entrar más de\n{STR_VAR_1} POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("¿Enviar la CARTA retirada a\ntu PC?");
const u8 gText_MailSentToPC[] = _("La CARTA fue enviada a tu PC.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("El BUZÓN de tu PC está lleno.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("Si retiras la CARTA, se perderá\nel mensaje. ¿Está bien?");
const u8 gText_RemoveMailBeforeItem[] = _("Debes retirar la CARTA antes de\nequipar un objeto.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("Se ha equipado {STR_VAR_2}\na {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} ya tiene\nun {STR_VAR_2}.\p¿Quieres intercambiar los\ndos objetos?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1} no lleva nada.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("Recibiste {STR_VAR_2}\nde {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("Se ha retirado la CARTA del\nPOKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("Se ha tomado {STR_VAR_2} y\nse ha reemplazado por {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("Este POKéMON lleva un objeto.\nNo puede llevar CARTA.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("La CARTA se transfirió desde\nel BUZÓN.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("La MOCHILA está llena. No se pudo\nretirar el objeto del POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("¡{STR_VAR_1} aprendió\n{STR_VAR_2}!");
const u8 gText_PkmnLearnedMove4[] = _("¡{STR_VAR_1} aprendió\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} y {STR_VAR_2}\nno son compatibles.\pNo puede aprender\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} quiere aprender el\nmovimiento {STR_VAR_2}.\pSin embargo, {STR_VAR_1} ya\nconoce cuatro movimientos.\p¿Quieres olvidar un movimiento y\nreemplazarlo por {STR_VAR_2}?");
const u8 gText_StopLearningMove2[] = _("¿Dejar de intentar enseñar\n{STR_VAR_2}?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} no aprendió el\nmovimiento {STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("¿Qué movimiento debe olvidar?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2 y{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}¡Puf!\p{STR_VAR_1} olvidó cómo\nusar {STR_VAR_2}.\pY…{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} ya conoce\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("Se han restaurado los PS de {STR_VAR_1}\nen {STR_VAR_2} punto(s).{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1} se curó del\nenvenenamiento.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1} se curó de la\nparálisis.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} se despertó.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("Se curó la quemadura de {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("Se curó la congelación de {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} se descongeló.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("Se han restaurado los PP.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} recuperó salud.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} recuperó la salud.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("Aumentaron los PP de {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} subió al\nNv. {STR_VAR_2}.");
const u8 gText_PkmnGainedExp[] = _("¡{STR_VAR_1} ganó {STR_VAR_2} puntos de Exp.!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("¡{STR_VAR_1} ganó {STR_VAR_2} puntos de Exp.\ny subió al Nv. {STR_VAR_3}!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("Aumentó la estadística base de\n{STR_VAR_2} de {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} se volvió más amigable.\n¡Bajó la base de {STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("¡{STR_VAR_1} te adora!\n¡Bajó la base de {STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} se volvió más amigable.\n¡La base de {STR_VAR_2} no puede bajar más!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} se libró de la\nconfusión.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} ya no está\nenamorado.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("¡{STR_VAR_1} se transformó!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("¿Tirar este\n{STR_VAR_1}?");
const u8 gText_ItemThrownAway[] = _("Se ha tirado\n{STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("¿Enseñar a qué POKéMON?"); // Unused
const u8 gText_ChoosePokemon[] = _("Elige un POKéMON.");
const u8 gText_MoveToWhere[] = _("¿Mover a dónde?");
const u8 gText_TeachWhichPokemon[] = _("¿Enseñar a qué POKéMON?");
const u8 gText_UseOnWhichPokemon[] = _("¿Usar en qué POKéMON?");
const u8 gText_GiveToWhichPokemon[] = _("¿Dar a qué POKéMON?");
const u8 gText_DoWhatWithPokemon[] = _("¿Qué hacer con este {PKMN}?");
const u8 gText_NothingToCut[] = _("No hay nada que CORTAR.");
const u8 gText_CantSurfHere[] = _("No puedes usar SURF aquí.");
const u8 gText_AlreadySurfing[] = _("Ya estás haciendo SURF.");
const u8 gText_CantUseHere[] = _("No se puede usar eso aquí.");
const u8 gText_RestoreWhichMove[] = _("¿Restaurar qué movimiento?");
const u8 gText_BoostPp[] = _("¿Aumentar PP de qué movimiento?");
const u8 gText_DoWhatWithItem[] = _("¿Qué hacer con el objeto?");
const u8 gText_NoPokemonForBattle[] = _("¡No hay POKéMON para combatir!");
const u8 gText_ChoosePokemon2[] = _("Elige un POKéMON.");
const u8 gText_NotEnoughHp[] = _("No hay suficientes PS…");
const u8 gText_PokemonAreNeeded[] = _("Se necesitan {STR_VAR_1} POKéMON.");
const u8 gText_PokemonCantBeSame[] = _("Los POKéMON no pueden ser iguales.");
const u8 gText_NoIdenticalHoldItems[] = _("No se permiten objetos equipados idénticos.");
const u8 gText_CurrentIsTooFast[] = _("¡La corriente es demasiado rápida!");
const u8 gText_DoWhatWithMail[] = _("¿Qué hacer con la CARTA?");
const u8 gText_ChoosePokemonCancel[] = _("Choose POKéMON or CANCEL.");
const u8 gText_ChoosePokemonConfirm[] = _("Choose POKéMON and confirm.");
const u8 gText_SendWhichMonToPC[] = _("Send which POKéMON to the PC?");
const u8 gText_MoveItemWhere[] = _("Move item to where?");
const u8 gText_XsYAnd[] = _("{STR_VAR_1}'s {STR_VAR_2} and\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}'s {STR_VAR_2} were swapped!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("¡Disfruta del ciclismo!");
const u8 gText_InUseAlready_PM[] = _("Esto ya está en uso.");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} ya tiene\nun {STR_VAR_2}.");
const u8 gText_WhichAppliance[] = _("¿Qué aparato\nquieres pedir?");
const u8 gText_NoUse[] = _("Sin uso.");
const u8 gText_Able[] = _("PUEDE");
const u8 gText_First_PM[] = _("PRIMERO");
const u8 gText_Second_PM[] = _("SEGUNDO");
const u8 gText_Third_PM[] = _("TERCERO");
const u8 gText_Able2[] = _("PUEDE");
const u8 gText_NotAble[] = _("NO PUEDE");
const u8 gText_Able3[] = _("¡PUEDE!");
const u8 gText_NotAble2[] = _("¡NO PUEDE!");
const u8 gText_Learned[] = _("APRENDIDO");
const u8 gText_Have[] = _("TIENE");
const u8 gText_DontHave[] = _("NO TIENE");
const u8 gText_Fourth[] = _("CUARTO");
const u8 gText_PkmnCantParticipate[] = _("Ese POKéMON no puede participar.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("¿Cancelar participación?");
const u8 gText_CancelBattle[] = _("¿Cancelar el combate?");
const u8 gText_ReturnToWaitingRoom[] = _("¿Volver a la SALA DE ESPERA?");
const u8 gText_CancelChallenge[] = _("¿Cancelar el desafío?");
const u8 gText_EscapeFromHere[] = _("¿Quieres escapar de aquí y volver\na {STR_VAR_1}?");
const u8 gText_ReturnToHealingSpot[] = _("¿Quieres volver al último centro de cura\nusado en {STR_VAR_1}?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("Es tu único\nPOKéMON para combatir.");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("Ese POKéMON no puede intercambiarse\nahora.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("Ese POKéMON no puede intercambiarse.");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("Un HUEVO no se puede intercambiar ahora.");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("El POKéMON del otro ENTRENADOR\nno puede intercambiarse ahora.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("El otro ENTRENADOR no puede aceptar\nese POKéMON ahora.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("No puedes intercambiar con ese\nENTRENADOR ahora.");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("Ese no es el tipo de POKéMON\nque el otro ENTRENADOR quiere.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("Eso no es un HUEVO.");
const u8 gText_Register[] = _("REGISTRAR");
const u8 gText_Attack3[] = _("ATAQUE");
const u8 gText_Defense3[] = _("DEFENSA");
const u8 gText_SpAtk4[] = _("AT. ESP");
const u8 gText_SpDef4[] = _("DF. ESP");
const u8 gText_Speed2[] = _("VEL.");
const u8 gText_HP4[] = _("PS");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("EO/");
const u8 gText_RentalPkmn[] = _("POKéMON ALQUILER");
const u8 gText_TypeSlash[] = _("TIPO/");
const u8 gText_Power[] = _("PODER");
const u8 gText_Accuracy2[] = _("PRECIS.");
const u8 gText_Appeal[] = _("EXHIBICIÓN");
const u8 gText_Jam[] = _("EXHIB. RIVAL");
const u8 gText_Status[] = _("ESTADO");
const u8 gText_ExpPoints[] = _("PUNTOS EXP.");
const u8 gText_NextLv[] = _("SIG. NIVEL");
const u8 gText_RibbonsVar1[] = _("CINTAS: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("EVENTOS"); // Unused
const u8 gText_Switch[] = _("CAMBIAR");
const u8 gText_PkmnInfo[] = _("DATOS POKéMON");
const u8 gText_PkmnSkills[] = _("FICHA POKéMON");
const u8 gText_BattleMoves[] = _("MOV. COMBATE");
const u8 gText_ContestMoves[] = _("MOV. CONCURSO");
const u8 gText_Info[] = _("INFO");
const u8 gText_EggWillTakeALongTime[] = _("Parece que a este HUEVO le\nllevará bastante tiempo nacer.");
const u8 gText_EggWillTakeSomeTime[] = _("¿Qué nacerá de esto?\nAún tardará un tiempo.");
const u8 gText_EggWillHatchSoon[] = _("A veces se mueve.\nDebería nacer pronto.");
const u8 gText_EggAboutToHatch[] = _("¡Hace ruidos!\n¡Está a punto de nacer!");
const u8 gText_HMMovesCantBeForgotten2[] = _("Los mov. MO no se pueden\nolvidar por ahora.");
const u8 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7},\nvisto en {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\nen {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7},\neclosionado en {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\nen {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7},\nobtenido en un intercambio.");
const u8 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7},\nobtenido en un encuentro\nfatídico con {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7},\nprobablemente visto en {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\nen {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNature[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7}");
const u8 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7},\nvisto en algún lugar con {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7},\neclosionado en algún lugar con {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("Un extraño HUEVO POKéMON hallado\npor la pareja de la Guardería.");
const u8 gText_PeculiarEggNicePlace[] = _("Un peculiar HUEVO POKéMON\nobtenido en un buen lugar.");
const u8 gText_PeculiarEggTrade[] = _("Un peculiar HUEVO POKéMON\nobtenido en un intercambio.");
const u8 gText_EggFromHotSprings[] = _("Un HUEVO POKéMON obtenido\nen las fuentes termales.");
const u8 gText_OddEggFromDaycare[] = _("Un extraño HUEVO POKéMON\nobtenido en la Guardería.");
const u8 gText_EggFromTraveler[] = _("Un extraño HUEVO POKéMON\nobtenido de un viajero.");
const u8 gText_ApostropheSBase[] = _("BASE DE {STR_VAR_1}");
const u8 gText_OkayToDeleteFromRegistry[] = _("¿Eliminar {STR_VAR_1}\ndel REGISTRO?");
const u8 gText_RegisteredDataDeleted[] = _("Se han borrado los datos registrados.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("No hay REGISTRO.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("BORRAR REG.");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("DECORAR");
const u8 gText_PutAway[] = _("GUARDAR");
const u8 gText_Toss2[] = _("TIRAR");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("Colocar el objeto de decoración seleccionado.");
const u8 gText_StoreChosenDecorInPC[] = _("Guardar la decoración elegida en el PC.");
const u8 gText_ThrowAwayUnwantedDecors[] = _("Tirar decoraciones no deseadas.");
const u8 gText_NoDecorations[] = _("No hay decoraciones.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("MESA");
const u8 gText_Chair[] = _("SILLA");
const u8 gText_Plant[] = _("PLANTA");
const u8 gText_Ornament[] = _("ADORNO");
const u8 gText_Mat[] = _("ALFOMBRA");
const u8 gText_Poster[] = _("PÓSTER");
const u8 gText_Doll[] = _("MUÑECO");
const u8 gText_Cushion[] = _("COJÍN");
const u8 gText_Gold[] = _("ORO");
const u8 gText_Silver[] = _("PLATA");
const u8 gText_PlaceItHere[] = _("¿Colocar aquí?");
const u8 gText_CantBePlacedHere[] = _("No se puede colocar aquí.");
const u8 gText_CancelDecorating[] = _("¿Cancelar decoración?");
const u8 gText_InUseAlready[] = _("Esto ya está en uso.");
const u8 gText_NoMoreDecorations[] = _("No se pueden colocar más decoraciones.\nEl máximo que se puede colocar es {STR_VAR_1}.");
const u8 gText_NoMoreDecorations2[] = _("No se pueden colocar más decoraciones.\nEl máximo que se puede colocar es {STR_VAR_1}.");
const u8 gText_MustBePlacedOnDesk[] = _("Esto no se puede colocar aquí.\nDebe estar sobre una MESA, etc."); // Unused
const u8 gText_CantPlaceInRoom[] = _("Esta decoración no se puede colocar en\ntu propia habitación.");
const u8 gText_CantThrowAwayInUse[] = _("Esta decoración está en uso.\nNo se puede tirar.");
const u8 gText_DecorationWillBeDiscarded[] = _("Esta {STR_VAR_1} se descartará.\n¿Está bien?");
const u8 gText_DecorationThrownAway[] = _("El objeto de decoración fue tirado.");
const u8 gText_StopPuttingAwayDecorations[] = _("¿Dejar de guardar decoraciones?");
const u8 gText_NoDecorationHere[] = _("No hay ningún objeto de decoración aquí.");
const u8 gText_ReturnDecorationToPC[] = _("¿Devolver esta decoración al PC?");
const u8 gText_DecorationReturnedToPC[] = _("La decoración fue devuelta al PC.");
const u8 gText_NoDecorationsInUse[] = _("No hay decoraciones en uso.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("No hay objetos.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("No hay CARTA aquí.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("¿Qué te gustaría hacer con\nla CARTA de {STR_VAR_1}?");
const u8 gText_MessageWillBeLost[] = _("El mensaje se perderá.\n¿Está bien?");
const u8 gText_BagIsFull[] = _("La MOCHILA está llena.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("La CARTA se devolvió a la MOCHILA\ncon su mensaje borrado.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("PAPÁ");
const u8 gText_Mom[] = _("MAMÁ");
const u8 gText_MomHowMuchDeposit[] = _("¿Cuánto te gustaría\ndepositar a tu MAMÁ?");
const u8 gText_MomHowMuchWithdraw[] = _("¿Cuánto te gustaría\nretirar de tu MAMÁ?");
const u8 gText_MomMatchCallDesc[] = _("CALMADA Y AMABLE");
const u8 gText_MomMatchCallName[] = _("MAMÁ");
const u8 gText_MomMenuCheckSavings[] = _("VER AHORROS");
const u8 gText_MomMenuDeposit[] = _("DEPOSITAR");
const u8 gText_MomMenuWithdraw[] = _("RETIRAR");
const u8 gText_MomMenuToggleSaving[] = _("AHORRANDO");
const u8 gText_MomMenuExit[] = _("SALIR");
const u8 gText_Info2[] = _("INFO");
const u8 gText_CoolnessContest[] = _("CONCURSO CARISMA");
const u8 gText_BeautyContest[] = _("CONCURSO BELLEZA");
const u8 gText_CutenessContest[] = _("CONCURSO DULZURA");
const u8 gText_SmartnessContest[] = _("CONCURSO INGENIO");
const u8 gText_ToughnessContest[] = _("CONCURSO DUREZA");
const u8 gText_Decoration2[] = _("DECORACIÓN");
const u8 gText_PackUp[] = _("RECOGER");
const u8 gText_Registry[] = _("REGISTRO");
const u8 gText_Information[] = _("INFORMACIÓN");
const u8 gText_Yes[] = _("SÍ");
const u8 gText_No[] = _("NO");
const u8 gText_Lv50[] = _("LV. 50");
const u8 gText_OpenLevel[] = _("OPEN LEVEL");
const u8 gText_RedShard[] = _("RED SHARD");
const u8 gText_YellowShard[] = _("YELLOW SHARD");
const u8 gText_BlueShard[] = _("BLUE SHARD");
const u8 gText_GreenShard[] = _("GREEN SHARD");
const u8 gText_BattleFrontier[] = _("BATTLE FRONTIER");
const u8 gText_Cool[] = _("COOL");
const u8 gText_Beauty[] = _("BEAUTY");
const u8 gText_Cute[] = _("CUTE");
const u8 gText_Smart[] = _("SMART");
const u8 gText_Tough[] = _("TOUGH");
const u8 gText_Normal[] = _("NORMAL");
const u8 gText_Super[] = _("SUPER");
const u8 gText_Hyper[] = _("HYPER");
const u8 gText_Master[] = _("MASTER");
const u8 gText_Cool2[] = _("COOL");
const u8 gText_Beauty2[] = _("BEAUTY");
const u8 gText_Cute2[] = _("CUTE");
const u8 gText_Smart2[] = _("SMART");
const u8 gText_Tough2[] = _("TOUGH");
const u8 gText_Items[] = _("OBJETOS");
const u8 gText_Key_Items[] = _("OBJ. CLAVE");
const u8 gText_Poke_Balls[] = _("POKé BALLS");
const u8 gText_TMs_Hms[] = _("MT & MO");
const u8 gText_Berries2[] = _("BAYAS");
const u8 gText_Medicine[] = _("MEDICINA");
#if I_COMBINE_BAG_POCKETS == FALSE
const u8 gText_BattleItems[] = _("COMBATE");
const u8 gText_Treasures[] = _("TESOROS");
#endif
const u8 gText_SomeonesPC[] = _("PC DE ALGUIEN");
const u8 gText_LanettesPC[] = _("PC DE LANETTE");
const u8 gText_BillsPc[] = _("PC DE BILL");
const u8 gText_PlayersPC[] = _("PC DE {PLAYER}");
const u8 gText_HallOfFame[] = _("HALL DE LA FAMA");
const u8 gText_LogOff[] = _("DESCONECTAR");
const u8 gText_Challenges[] = _("DESAFÍOS");
const u8 gText_Opponent[] = _("RIVAL");
const u8 gText_Tourney_Tree[] = _("TORNEO");
const u8 gText_ReadyToStart[] = _("LISTO PARA EMPEZAR");
const u8 gText_Single2[] = _("INDIVIDUAL");
const u8 gText_Double2[] = _("DOBLE");
const u8 gText_Multi[] = _("MULTIPLE");
const u8 gText_MultiLink[] = _("CONEXIÓN MULTI");
const u8 gText_MenuOptionPokedex[] = _("POKéDEX");
const u8 gText_MenuOptionPokemon[] = _("POKéMON");
const u8 gText_MenuOptionBag[] = _("MOCHILA");
#if IS_HNS
const u8 gText_MenuOptionPokenav[] = _("POKéGEAR");
#else
const u8 gText_MenuOptionPokenav[] = _("POKéNAV");
#endif
const u8 gText_Blank[] = _("");
const u8 gText_MenuOptionSave[] = _("GUARDAR");
const u8 gText_MenuOptionOption[] = _("OPCIONES");
const u8 gText_MenuOptionExit[] = _("SALIR");
const u8 gText_SouthernIsland[] = _("SOUTHERN ISLAND");
const u8 gText_BirthIsland[] = _("BIRTH ISLAND");
const u8 gText_FarawayIsland[] = _("FARAWAY ISLAND");
const u8 gText_NavelRock[] = _("NAVEL ROCK");
const u8 gText_NormalTagMatch[] = _("NORMAL TAG MATCH");
const u8 gText_VarietyTagMatch[] = _("VARIETY TAG MATCH");
const u8 gText_UniqueTagMatch[] = _("UNIQUE TAG MATCH");
const u8 gText_ExpertTagMatch[] = _("EXPERT TAG MATCH");
const u8 gText_TradeCenter[] = _("TRADE CENTER");
const u8 gText_Colosseum[] = _("COLOSSEUM");
const u8 gText_RecordCorner[] = _("RECORD CORNER");
const u8 gText_BerryCrush3[] = _("BERRY CRUSH");
const u8 gText_BattleRules[] = _("BATTLE RULES");
const u8 gText_JudgeMind[] = _("JUDGE: MIND");
const u8 gText_JudgeSkill[] = _("JUDGE: SKILL");
const u8 gText_JudgeBody[] = _("JUDGE: BODY");
const u8 gText_BasicRules[] = _("BASIC RULES");
const u8 gText_SwapPartners[] = _("SWAP: PARTNER");
const u8 gText_SwapNumber[] = _("SWAP: NUMBER");
const u8 gText_SwapNotes[] = _("SWAP: NOTES");
const u8 gText_BattleBasics[] = _("BATTLE BASICS");
const u8 gText_PokemonNature[] = _("POKéMON NATURE");
const u8 gText_PokemonMoves[] = _("POKéMON MOVES");
const u8 gText_Underpowered[] = _("UNDERPOWERED");
const u8 gText_WhenInDanger[] = _("WHEN IN DANGER");
const u8 gText_BattlePokemon[] = _("BATTLE POKéMON");
const u8 gText_BattleTrainers[] = _("BATTLE TRAINERS");
const u8 gText_GoOn[] = _("GO ON");
const u8 gText_Record2[] = _("RECORD");
const u8 gText_Rest[] = _("REST");
const u8 gText_Retire[] = _("RETIRE");
const u8 gText_1F[] = _("1F");
const u8 gText_2F[] = _("2F");
const u8 gText_3F[] = _("3F");
const u8 gText_4F[] = _("4F");
const u8 gText_5F[] = _("5F");
const u8 gText_6F[] = _("6F");
const u8 gText_7F[] = _("7F");
const u8 gText_8F[] = _("8F");
const u8 gText_9F[] = _("9F");
const u8 gText_10F[] = _("10F");
const u8 gText_11F[] = _("11F");
const u8 gText_B1F[] = _("B1F");
const u8 gText_B2F[] = _("B2F");
const u8 gText_B3F[] = _("B3F");
const u8 gText_B4F[] = _("B4F");
const u8 gText_Rooftop[] = _("ROOFTOP");
const u8 gText_ElevatorNowOn[] = _("Now on:");
const u8 gText_BP[] = _("BP");
const u8 gText_RankingHall[] = _("RANKING HALL");
const u8 gText_ExchangeService[] = _("EXCHANGE SERVICE");
const u8 gText_LilycoveCity[] = _("LILYCOVE CITY");
const u8 gText_SlateportCity[] = _("SLATEPORT CITY");
const u8 gText_Exit[] = _("SALIR");
const u8 gText_YourPartysFull[] = _("¡Tu equipo está lleno!{PAUSE_UNTIL_PRESS}");
const u8 gText_InParty[] = _("EN EQUIPO");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("Combine four words or phrases");
const u8 gText_AndMakeYourProfile[] = _("and make your profile.");
const u8 gText_CombineSixWordsOrPhrases[] = _("Combine six words or phrases");
const u8 gText_AndMakeAMessage[] = _("and make a message.");
const u8 gText_FindWordsThatDescribeYour[] = _("Find words that describe your");
const u8 gText_FeelingsRightNow[] = _("feelings right now.");
const u8 gText_WithFourPhrases[] = _("With four phrases,"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("Combine nine words or phrases");
const u8 gText_AndMakeAMessage2[] = _("and make a message.");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("Change just one word or phrase");
const u8 gText_AndImproveTheBardsSong[] = _("and improve the BARD's song.");
const u8 gText_YourProfile[] = _("Your profile");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("Your feeling at the battle's start");
const u8 gText_WhatYouSayIfYouWin[] = _("What you say if you win a battle");
const u8 gText_WhatYouSayIfYouLose[] = _("What you say if you lose a battle");
const u8 gText_TheAnswer[] = _("The answer");
const u8 gText_TheMailMessage[] = _("The MAIL message");
const u8 gText_TheMailSalutation[] = _("The MAIL salutation"); // Unused
const u8 gText_TheBardsSong2[] = _("The new song");
const u8 gText_CombineTwoWordsOrPhrases[] = _("Combine two words or phrases");
const u8 gText_AndMakeATrendySaying[] = _("and make a trendy saying.");
const u8 gText_TheTrendySaying[] = _("The trendy saying");
const u8 gText_IsAsShownOkay[] = _("is as shown. Okay?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("Combine two words or phrases");
const u8 gText_ToTeachHerAGoodSaying[] = _("to teach her a good saying.");
const u8 gText_FindWordsWhichFit[] = _("Find words which fit");
const u8 gText_TheTrainersImage[] = _("the TRAINER's image.");
const u8 gText_TheImage[] = _("The image:");
const u8 gText_OutOfTheListedChoices[] = _("Out of the listed choices,");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("select the answer to the quiz!");
const u8 gText_AndCreateAQuiz[] = _("and create a quiz!");
const u8 gText_PickAWordOrPhraseAnd[] = _("Pick a word or phrase and");
const u8 gText_SetTheQuizAnswer[] = _("set the quiz answer.");
const u8 gText_TheAnswerColon[] = _("The answer:");
const u8 gText_TheQuizColon[] = _("The quiz:"); // Unused
const u8 gText_ApprenticePhrase[] = _("Apprentice's phrase:");
const u8 gText_QuitEditing[] = _("Quit editing?");
const u8 gText_StopGivingPkmnMail[] = _("Stop giving the POKéMON MAIL?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("and fill out the questionnaire.");
const u8 gText_LetsReplyToTheInterview[] = _("Let's reply to the interview!");
const u8 gText_AllTextBeingEditedWill[] = _("All the text being edited will");
const u8 gText_BeDeletedThatOkay[] = _("be deleted. Is that okay?");
const u8 gText_QuitEditing2[] = _("Quit editing?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("The edited text will not be saved."); // Unused
const u8 gText_IsThatOkay[] = _("Is that okay?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("Please enter a phrase or word."); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("The entire text can't be deleted.");
const u8 gText_OnlyOnePhrase[] = _("Only one phrase may be changed.");
const u8 gText_OriginalSongWillBeUsed[] = _("The original song will be used.");
const u8 gText_ThatsTrendyAlready[] = _("That's trendy already!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("Combine two words or phrases.");
const u8 gText_QuitGivingInfo[] = _("Quit giving information?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("Stop giving the POKéMON MAIL?"); // Unused
const u8 gText_CreateAQuiz2[] = _("Create a quiz!"); // Unused
const u8 gText_SetTheAnswer[] = _("Set the answer!"); // Unused
const u8 gText_CancelSelection[] = _("Cancel the selection?"); // Unused
const u8 gText_Profile[] = _("PROFILE");
const u8 gText_AtTheBattlesStart[] = _("At the battle's start:");
const u8 gText_UponWinningABattle[] = _("Upon winning a battle:");
const u8 gText_UponLosingABattle[] = _("Upon losing a battle:");
const u8 gText_TheBardsSong[] = _("The BARD's Song");
const u8 gText_WhatsHipAndHappening[] = _("What's hip and happening?");
const u8 gText_Interview[] = _("Interview");
const u8 gText_GoodSaying[] = _("Good saying");
const u8 gText_FansQuestion[] = _("Fan's question");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("Apprentice's phrase");
const u8 gText_Questionnaire[] = _("QUESTIONNAIRE");
const u8 gText_YouCannotQuitHere[] = _("You cannot quit here.");
const u8 gText_SectionMustBeCompleted[] = _("This section must be completed.");
const u8 gText_F700sQuiz[] = _("{DYNAMIC 0}'s quiz");
const u8 gText_Lady[] = _("Lady");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("After you have read the quiz");
const u8 gText_QuestionPressTheAButton[] = _("question, press the A Button.");
const u8 gText_TheQuizAnswerIs[] = _("The quiz answer is?");
const u8 gText_LikeToQuitQuiz[] = _("Would you like to quit this quiz");
const u8 gText_ChallengeQuestionMark[] = _("challenge?");
const u8 gText_IsThisQuizOK[] = _("Is this quiz OK?");
const u8 gText_CreateAQuiz[] = _("Create a quiz!");
const u8 gText_SelectTheAnswer[] = _("Select the answer!");
const u8 gText_LyricsCantBeDeleted[] = _("The lyrics can't be deleted.");
const u8 gText_PokemonLeague[] = _("LIGA POKéMON");
const u8 gText_PokemonCenter[] = _("CENTRO POKéMON");
const u8 gText_Coolness[] = _("Carisma ");
const u8 gText_Beauty3[] = _("Belleza ");
const u8 gText_Cuteness[] = _("Dulzura ");
const u8 gText_Smartness[] = _("Ingenio ");
const u8 gText_Toughness[] = _("Dureza ");
const u8 gText_SaveFailedCheckingBackup[] = _("Error al guardar. Comprobando memoria de respaldo… Por favor espera.\n{COLOR RED}“Tiempo requerido: 1 minuto aprox.”");
const u8 gText_BackupMemoryDamaged[] = _("La memoria de respaldo está dañada o\nla pila interna se ha agotado.\nPuedes jugar, pero no guardar.");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“No se puede continuar la partida.\nVolviendo a la pantalla de título…”");
const u8 gText_CheckCompleted[] = _("Comprobación completada.\nIntentando guardar de nuevo.\nPor favor espera.");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Guardado completado.\n{COLOR RED}“No se puede continuar la partida.\nVolviendo a la pantalla de título.”");
const u8 gText_SaveCompletePressA[] = _("Guardado completado.\n{COLOR RED}“Por favor pulsa el Botón A.”");
const u8 gText_Ferry[] = _("FERRY");
const u8 gText_SecretBase[] = _("BASE SECRETA");
const u8 gText_Hideout[] = _("GUARIDA");
const u8 gText_ResetRTCConfirmCancel[] = _("¿Reiniciar RTC?\nA: Confirmar, B: Cancelar");
const u8 gText_PresentTime[] = _("Tiempo actual en el juego");
const u8 gText_PreviousTime[] = _("Tiempo anterior en el juego");
const u8 gText_PleaseResetTime[] = _("Por favor reinicia la hora.");
const u8 gText_ClockHasBeenReset[] = _("El reloj ha sido reiniciado.\nSe guardarán los datos. Por favor espera.");
const u8 gText_SaveCompleted[] = _("Guardado completado.");
const u8 gText_SaveFailed[] = _("Error al guardar…");
const u8 gText_NoSaveFileCantSetTime[] = _("No hay partida guardada, no se puede\najustar la hora.");
const u8 gText_InGameClockUsable[] = _("El sistema de ajuste de reloj del juego\nahora está disponible.");
const u8 gText_Spicy2[] = _("picante");
const u8 gText_Dry2[] = _("seco");
const u8 gText_Sweet2[] = _("dulce");
const u8 gText_Bitter2[] = _("amargo");
const u8 gText_Sour2[] = _("ácido");
const u8 gText_Single[] = _("INDIVIDUAL");
const u8 gText_Double[] = _("DOBLE");
const u8 gText_Knockout[] = _("KNOCKOUT");
const u8 gText_Mixed[] = _("MIXTO");
const u8 gText_First[] = _("primero");
const u8 gText_Second[] = _("segundo");
const u8 gText_Third[] = _("tercero");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("¡{STR_VAR_1} se debilitó…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("¡{STR_VAR_1} sobrevivió al envenenamiento!\n¡El veneno desapareció!\p");
#endif
const u8 gText_PkmnSurvived_FldPsn[] = _("¡{STR_VAR_1} sobrevivió al envenenamiento!\n¡El veneno desapareció!\p");
const u8 gText_Marco[] = _("MARCO");
const u8 gText_TrainerCardName[] = _("NOMBRE: ");
const u8 gText_TrainerCardIDNo[] = _("N.º ID");
const u8 gText_TrainerCardMoney[] = _("DINERO");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("POKéDEX");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" puntos"); // Unused
const u8 gText_TrainerCardTime[] = _("TIEMPO JUEGO");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("FICHA DE {STR_VAR_1}");
const u8 gText_HallOfFameDebut[] = _("PRIMER SALÓN DE LA FAMA  ");
const u8 gText_LinkBattles[] = _("COMBATES EN LINKE");
const u8 gText_LinkCableBattles[] = _("COMBATES POR CABLE");
const u8 gText_WinsLosses[] = _("V:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  D:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("INTERCAMBIOS POKéMON");
const u8 gText_UnionTradesAndBattles[] = _("UNION TRADES & BATTLES");
const u8 gText_BerryCrush[] = _("BERRY CRUSH");
const u8 gText_WaitingTrainerFinishReading[] = _("Waiting for the other TRAINER to\nfinish reading your TRAINER CARD.");
const u8 gText_PokeblocksWithFriends[] = _("{POKEBLOCK}S W/FRIENDS");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("WON CONTESTS W/FRIENDS");
const u8 gText_BattlePtsWon[] = _("BATTLE POINTS WON");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP");
const u8 gText_BattleTower[] = _("BATTLE TOWER");
const u8 gText_WinsStraight[] = _("W/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  STRAIGHT/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("BATTLE TOWER");
const u8 gText_BattleDome[] = _("BATTLE DOME");
const u8 gText_BattlePalace[] = _("BATTLE PALACE");
const u8 gText_BattleFactory[] = _("BATTLE FACTORY");
const u8 gText_BattleArena[] = _("BATTLE ARENA");
const u8 gText_BattlePike[] = _("BATTLE PIKE");
const u8 gText_BattlePyramid[] = _("BATTLE PYRAMID");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} SINGLE");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} DOUBLE");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} MULTI");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} LINK");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("Give");
const u8 gText_NoNeed[] = _("No need");
const u8 gText_AnnouncingResults[] = _("Announcing the results!");
const u8 gText_PreliminaryResults[] = _("The preliminary results!");
const u8 gText_Round2Results[] = _("Round 2 results!");
const u8 gText_ContestantsMonWon[] = _("{STR_VAR_1}'s {STR_VAR_2} won!");
const u8 gText_CommunicationStandby[] = _("Communication standby…");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("UPPER");
const u8 gText_Lower[] = _("lower");
const u8 gText_Others[] = _("OTHERS");
const u8 gText_Symbols[] = _("SYMBOLS");
const u8 gText_Register2[] = _("REGISTER");
const u8 gText_Exit2[] = _("EXIT");
const u8 gText_QuitChatting[] = _("Quit chatting?");
const u8 gText_RegisterTextWhere[] = _("Register text where?");
const u8 gText_RegisterTextHere[] = _("Register text here?");
const u8 gText_InputText[] = _("Input text.");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} joined the chat!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0} left the chat.");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Exiting the chat…");
const u8 gText_LeaderLeftEndingChat[] = _("The LEADER, {DYNAMIC 0}, has\nleft, ending the chat.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("The registered text has been changed.\nIs it okay to save the game?");
const u8 gText_AlreadySavedFile_Chat[] = _("There is already a saved file.\nIs it okay to overwrite it?");
const u8 gText_SavingDontTurnOff_Chat[] = _("SAVING…\nDON'T TURN OFF THE POWER.");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} saved the game.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("If the LEADER leaves, the chat\nwill end. Is that okay?");
const u8 gText_Hello[] = _("HELLO");
const u8 gText_Pokemon2[] = _("POKéMON");
const u8 gText_Trade[] = _("TRADE");
const u8 gText_Battle[] = _("BATTLE");
const u8 gText_Lets[] = _("LET'S");
const u8 gText_Ok[] = _("OK!");
const u8 gText_Sorry[] = _("SORRY");
const u8 gText_YaySmileEmoji[] = _("YAY{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("THANK YOU");
const u8 gText_ByeBye[] = _("BYE-BYE!");
const u8 gText_HatchedFromEgg[] = _("{STR_VAR_1} hatched from the EGG!");
const u8 gText_NicknameHatchPrompt[] = _("Would you like to nickname the newly\nhatched {STR_VAR_1}?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("Are you ready to BERRY-CRUSH?\nPlease pick a BERRY for use.\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("Please wait while each member\nchooses a BERRY.");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}You ended up with {STR_VAR_1} units of\nsilky-smooth BERRY POWDER.{RESUME_MUSIC}\pYour total amount of BERRY POWDER\nis {STR_VAR_2}.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Recording your game results in the\nsave file.\lPlease wait.");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("Want to play BERRY CRUSH again?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("You have no BERRIES.\nThe game will be canceled.");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("A member dropped out.\nThe game will be canceled.");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("Time's up.\pGood BERRY POWDER could not be\nmade…\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("Communication standby…");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _(" time(s)");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{STR_VAR_1} BERRY");
ALIGNED(4) const u8 gText_TimeColon[] = _("Time:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("Pressing Speed:");
ALIGNED(4) const u8 gText_Silkiness[] = _("Silkiness:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _(" min. ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _(" sec.");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _(" Times/sec.");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("No. of Presses Rankings");
ALIGNED(4) const u8 gText_CrushingResults[] = _("Crushing Results");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("Neatness Rankings");
ALIGNED(4) const u8 gText_CoopRankings[] = _("Cooperative Rankings");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("Pressing-Power Rankings");
const u8 gText_BerryCrush2[] = _("BERRY CRUSH");
const u8 gText_PressingSpeedRankings[] = _("Pressing-Speed Rankings");
const u8 gText_Var1Players[] = _("{STR_VAR_1} PLAYERS");
const u8 gText_SymbolsEarned[] = _("Symbols Earned");
const u8 gText_BattleRecord[] = _("Battle Record");
const u8 gText_BattlePoints[] = _("Battle Points");
const u8 gText_UnusedCancel[] = _("CANCEL"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("Check BATTLE FRONTIER MAP.");
const u8 gText_CheckTrainerCard[] = _("Check TRAINER CARD.");
const u8 gText_ViewRecordedBattle[] = _("View recorded battle.");
const u8 gText_PutAwayFrontierPass[] = _("Put away the FRONTIER PASS.");
const u8 gText_CurrentBattlePoints[] = _("Your current Battle Points.");
const u8 gText_CollectedSymbols[] = _("Your collected Symbols.");
const u8 gText_BattleTowerAbilitySymbol[] = _("Battle Tower - Ability Symbol");
const u8 gText_BattleDomeTacticsSymbol[] = _("Battle Dome - Tactics Symbol");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("Battle Palace - Spirits Symbol");
const u8 gText_BattleArenaGutsSymbol[] = _("Battle Arena - Guts Symbol");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("Battle Factory - Knowledge Symbol");
const u8 gText_BattlePikeLuckSymbol[] = _("Battle Pike - Luck Symbol");
const u8 gText_BattlePyramidBraveSymbol[] = _("Battle Pyramid - Brave Symbol");
const u8 gText_ThereIsNoBattleRecord[] = _("There is no Battle Record.");
const u8 gText_BattleTower3[] = _("BATTLE TOWER");
const u8 gText_BattleDome2[] = _("BATTLE DOME");
const u8 gText_BattlePalace2[] = _("BATTLE PALACE");
const u8 gText_BattleArena2[] = _("BATTLE ARENA");
const u8 gText_BattleFactory2[] = _("BATTLE FACTORY");
const u8 gText_BattlePike2[] = _("BATTLE PIKE");
const u8 gText_BattlePyramid2[] = _("BATTLE PYRAMID");
const u8 gText_BattleTowerDesc[] = _("KO opponents and aim for the top!\nYour ability will be tested.");
const u8 gText_BattleDomeDesc[] = _("Keep winning at the tournament!\nYour tactics will be tested.");
const u8 gText_BattlePalaceDesc[] = _("Watch your POKéMON battle!\nYour spirit will be tested.");
const u8 gText_BattleArenaDesc[] = _("Win battles with teamed-up POKéMON!\nYour guts will be tested.");
const u8 gText_BattleFactoryDesc[] = _("Aim for victory using rental POKéMON!\nYour knowledge will be tested.");
const u8 gText_BattlePikeDesc[] = _("Select one of three paths to battle!\nYour luck will be tested.");
const u8 gText_BattlePyramidDesc[] = _("Aim for the top with exploration!\nYour bravery will be tested.");
const u8 gText_Powder[] = _("POWDER");
const u8 gText_BerryPickingRecords[] = _("DODRIO BERRY-PICKING RECORDS");
const u8 gText_BerriesPicked[] = _("BERRIES picked:");
const u8 gText_BestScore[] = _("Best score:");
const u8 gText_BerriesInRowFivePlayers[] = _("BERRIES picked in a row with\nfive players:");
const u8 gText_BerryPickingResults[] = _("Announcing BERRY-PICKING results!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 0x03}10P{CLEAR_TO 0x2B}30P{CLEAR_TO 0x53}50P{CLEAR_TO 0x77}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("Announcing rankings!");
const u8 gText_AnnouncingPrizes[] = _("Announcing prizes!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("The first-place winner gets\nthis {DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("You can't hold any more!");
const u8 gText_FilledStorageSpace[] = _("It filled its storage space.");
const u8 gText_WantToPlayAgain[] = _("Want to play again?");
const u8 gText_SomeoneDroppedOut[] = _("Somebody dropped out.\nThe link will be canceled.");
const u8 gText_SpacePoints[] = _(" points");
const u8 gText_CommunicationStandby3[] = _("Communication standby…");
const u8 gText_SpacePoints2[] = _(" points");
const u8 gText_SpaceTimes3[] = _(" time(s)");
const u8 gText_PkmnJumpRecords[] = _("POKéMON JUMP RECORDS");
const u8 gText_JumpsInARow[] = _("Jumps in a row:");
const u8 gText_BestScore2[] = _("Best score:");
const u8 gText_ExcellentsInARow[] = _("EXCELLENTS in a row:");
const u8 gText_AwesomeWonF701F700[] = _("Awesome score! You've\nwon {DYNAMIC 1} {DYNAMIC 0}!");
const u8 gText_FilledStorageSpace2[] = _("It filled its storage space.");
const u8 gText_CantHoldMore[] = _("You can't hold any more!");
const u8 gText_WantToPlayAgain2[] = _("Want to play again?");
const u8 gText_SomeoneDroppedOut2[] = _("Somebody dropped out.\nThe link will be canceled.");
const u8 gText_CommunicationStandby4[] = _("Communication standby…");
const u8 gText_LinkContestResults[] = _("{PLAYER}'s Link Contest Results");
const u8 gText_1st[] = _("1st");
const u8 gText_2nd[] = _("2nd");
const u8 gText_3rd[] = _("3rd");
const u8 gText_4th[] = _("4th");
const u8 gText_Friend[] = _("Friend");
const u8 gText_Pokemon3[] = _("POKeMON"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS}　で\nふしぎなもらいものを　よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の　‘つうしん'を\nえらんで　Aボタンを　おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが　まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの　よみこみを\nちゅうし　しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん　できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん　ちゅう　です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん　エラーです\nせつぞくを　たしかめて　ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん　しゅうりょう！");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく　おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("{PLAYER}'s Single Battle Room Results");
const u8 gText_DoubleBattleRoomResults[] = _("{PLAYER}'s Double Battle Room Results");
const u8 gText_MultiBattleRoomResults[] = _("{PLAYER}'s Multi Battle Room Results");
const u8 gText_LinkMultiBattleRoomResults[] = _("{PLAYER}'s Link Multi Battle Room Results");
const u8 gText_SingleBattleTourneyResults[] = _("{PLAYER}'s Single Battle Tourney Results");
const u8 gText_DoubleBattleTourneyResults[] = _("{PLAYER}'s Double Battle Tourney Results");
const u8 gText_SingleBattleHallResults[] = _("{PLAYER}'s Single Battle Hall Results");
const u8 gText_DoubleBattleHallResults[] = _("{PLAYER}'s Double Battle Hall Results");
const u8 gText_BattleChoiceResults[] = _("{PLAYER}'s Battle Choice Results");
const u8 gText_SetKOTourneyResults[] = _("{PLAYER}'s Set KO Tourney Results");
const u8 gText_BattleSwapSingleResults[] = _("{PLAYER}'s Battle Swap Single Results");
const u8 gText_BattleSwapDoubleResults[] = _("{PLAYER}'s Battle Swap Double Results");
const u8 gText_BattleQuestResults[] = _("{PLAYER}'s Battle Quest Results");
const u8 gText_Lv502[] = _("LV. 50");
const u8 gText_OpenLv[] = _("OPEN LV.");
const u8 gText_WinStreak[] = _("Win streak: {STR_VAR_1}");
const u8 gText_Current[] = _("CURRENT");
const u8 gText_Record[] = _("RECORD");
const u8 gText_Prev[] = _("PREV.");
const u8 gText_RentalSwap[] = _("Rental/Swap");
const u8 gText_Total[] = _("Total");
const u8 gText_ClearStreak[] = _("Clear streak: {STR_VAR_1}");
const u8 gText_Championships[] = _("Championships: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Rooms cleared: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Times cleared:{CLEAR 0x05}{STR_VAR_1}");
const u8 gText_KOsInARow[] = _("KOs in a row: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Times: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Floors cleared: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("LV. 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("OPEN LEVEL");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Win streak: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Clear streak: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Rooms cleared: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("KOs in a row: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Floors cleared: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" and {STR_VAR_2} of the POKéMON species\nyou caught are inelegible");
const u8 gText_FrontierFacilityIncluding[] = _(".\pThese include ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" are inelegible");

const u8 gText_YesNo[] = _("SÍ\nNO");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("PEEKABOO!");
const u8 gText_CommErrorCheckConnections[] = _("Communication error…\nPlease check all connections,\nthen turn the power OFF and ON.");
const u8 gText_CommErrorEllipsis[] = _("Communication error…");
const u8 gText_MoveCloserToLinkPartner[] = _("Move closer to your link partner(s).\nAvoid obstacles between partners.");
const u8 gText_ABtnRegistrationCounter[] = _("A Button: Registration Counter");
const u8 gText_ABtnTitleScreen[] = _("A Button: Title Screen");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}P LINK");
const u8 gText_BronzeCard[] = _("BRONZE");
const u8 gText_CopperCard[] = _("COPPER");
const u8 gText_SilverCard[] = _("SILVER");
const u8 gText_GoldCard[] = _("GOLD");
const u8 gText_Day[] = _("DAY");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("CONFIRM");
const u8 gText_Days[] = _("Days"); // Unused
const u8 gText_TimeColon2[] = _("Time:"); // Unused
const u8 gText_GameTime[] = _("Game time"); // Unused
const u8 gText_RTCTime[] = _("RTC time"); // Unused
const u8 gText_UpdatedTime[] = _("Updated time"); // Unused
const u8 gText_MenuPokedex[] = _("POKéDEX");
const u8 gText_MenuPokemon[] = _("POKéMON");
const u8 gText_MenuBag[] = _("MOCHILA");
#if IS_HNS
const u8 gText_MenuPokenav[] = _("{POKE}GEAR");
#else
const u8 gText_MenuPokenav[] = _("POKéNAV");
#endif
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("GUARDAR");
const u8 gText_MenuOption[] = _("OPCIONES");
const u8 gText_MenuExit[] = _("SALIR");
const u8 gText_MenuRetire[] = _("RETIRARSE");
const u8 gText_MenuRest[] = _("DESCANSAR");
const u8 gText_MenuDexNav[] = _("DEXNAV");
const u8 gText_SafariBallStock[] = _("SAFARI BALLS\nStock: {STR_VAR_1}");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nBALLS  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("Battle Pyramid\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("Floor 1");
const u8 gText_Floor2[] = _("Floor 2");
const u8 gText_Floor3[] = _("Floor 3");
const u8 gText_Floor4[] = _("Floor 4");
const u8 gText_Floor5[] = _("Floor 5");
const u8 gText_Floor6[] = _("Floor 6");
const u8 gText_Floor7[] = _("Floor 7");
const u8 gText_Peak[] = _("Peak");
const u8 gText_LinkStandby2[] = _("Link standby…\n… … B Button: Cancel");
const u8 gText_PressAToLoadEvent[] = _("Press the A Button to load event.\n… … B Button: Cancel");
const u8 gText_LoadingEvent[] = _("Loading event…");
const u8 gText_DontRemoveCableTurnOff[] = _("Don't remove the Game Link cable.\nDon't turn off the power.");
const u8 gText_EventSafelyLoaded[] = _("The event was safely loaded.");
const u8 gText_LoadErrorEndingSession[] = _("Loading error.\nEnding session.");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("HOENN");
const u8 gText_DexNational[] = _("NACIONAL");
const u8 gText_PokedexDiploma[] = _("JUGADOR: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nEste documento certifica\nque has completado\ncon éxito tu\nPOKéDEX {STR_VAR_1}.\n\n{CLEAR_TO 0x42}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("HOENN");
const u8 gText_Kanto[] = _("KANTO");
const u8 gText_Johto[] = _("JOHTO");
const u8 gText_JohtoKanto[] = _("JOHTO Y KANTO");
const u8 gText_XWillBeSentToY[] = _("Se enviará a {STR_VAR_2}\na {STR_VAR_1}.");
const u8 gText_ByeByeVar1[] = _("¡Adiós, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} enviado a través de {STR_VAR_3}.");
const u8 gText_TakeGoodCareOfX[] = _("¡Cuida bien de {STR_VAR_3}!");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_FourQuestionMarks[] = _("????");
const u8 gText_MaxHP[] = _("PS MÁX.");
const u8 gText_Attack[] = _("ATAQUE");
const u8 gText_Defense[] = _("DEFENSA");
const u8 gText_Speed[] = _("VELOCIDAD");
const u8 gText_SpAtk[] = _("AT. ESP.");
const u8 gText_SpDef[] = _("DEF. ESP.");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_MixingRecords[] = _("Mezclando récords…");
const u8 gText_RecordMixingComplete[] = _("Mezcla de récords completada.\nGracias por esperar.");
const u8 gText_RentalPkmn2[] = _("POKéMON ALQUILER");
const u8 gText_SelectFirstPkmn[] = _("Elige el primer POKéMON.");
const u8 gText_SelectSecondPkmn[] = _("Elige el segundo POKéMON.");
const u8 gText_SelectThirdPkmn[] = _("Elige el tercer POKéMON.");
const u8 gText_Rent[] = _("ALQUILAR");
const u8 gText_Summary[] = _("DATOS");
const u8 gText_Others2[] = _("OTROS");
const u8 gText_Deselect[] = _("DESMARCAR");
const u8 gText_TheseThreePkmnOkay[] = _("¿Estás de acuerdo con estos tres POKéMON?");
const u8 gText_Yes2[] = _("SÍ");
const u8 gText_No2[] = _("NO");
const u8 gText_CantSelectSamePkmn[] = _("Can't select same {PKMN}.");
const u8 gText_PkmnSwap[] = _("POKéMON SWAP");
const u8 gText_SelectPkmnToSwap[] = _("Select POKéMON to swap.");
const u8 gText_SelectPkmnToAccept[] = _("Select POKéMON to accept.");
const u8 gText_Swap[] = _("CAMBIAR");
const u8 gText_Summary2[] = _("DATOS");
const u8 gText_Rechoose[] = _("REELIGIR");
const u8 gText_QuitSwapping[] = _("¿Salir del cambio?");
const u8 gText_Yes3[] = _("SÍ");
const u8 gText_No3[] = _("NO");
const u8 gText_PkmnForSwap[] = _("{PKMN} PARA CAMBIAR");
const u8 gText_Cancel3[] = _("CANCELAR");
const u8 gText_Swap2[] = _("CAMBIAR"); // Unused
const u8 gText_Accept[] = _("ACEPTAR"); // Unused
const u8 gText_AcceptThisPkmn[] = _("¿Aceptar a este POKéMON?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Ese {PKMN} ya está en el equipo.");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("JUGADOR");
const u8 gText_SavingBadges[] = _("MEDALLAS");
const u8 gText_SavingPokedex[] = _("POKéDEX");
const u8 gText_SavingTime[] = _("TIEMPO JUEGO");
const u8 gText_WirelessCommStatus[] = _("Wireless Communication Status");
const u8 gText_PeopleTrading[] = _("People trading:");
const u8 gText_PeopleBattling[] = _("People battling:");
const u8 gText_PeopleInUnionRoom[] = _("People in the UNION ROOM:");
const u8 gText_PeopleCommunicating[] = _("People communicating:");
const u8 gText_F700Players[] = _("{DYNAMIC 0} players");
const u8 gText_F701Players[] = _("{DYNAMIC 1} players");
const u8 gText_F702Players[] = _("{DYNAMIC 2} players");
const u8 gText_F703Players[] = _("{DYNAMIC 3} players");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("WONDER CARDS");
ALIGNED(4) const u8 gText_WonderNews[] = _("WONDER NEWS");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("WIRELESS COMMUNICATION");
ALIGNED(4) const u8 gText_Friend2[] = _("FRIEND");
ALIGNED(4) const u8 gText_Exit3[] = _("EXIT");
ALIGNED(4) const u8 gText_Receive[] = _("RECEIVE");
ALIGNED(4) const u8 gText_Send[] = _("SEND");
ALIGNED(4) const u8 gText_Toss[] = _("TOSS");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("A variety of events will be imported\nover Wireless Communication.");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("Read the WONDER CARDS in your\npossession.");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("Read the NEWS that arrived.");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("Return to the title screen.");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("You don't have a WONDER CARD,\nso a new CARD will be input.");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("You don't have any WONDER NEWS,\nso new NEWS will be input.");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("Where should the WONDER CARD\nbe accessed?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("Where should the WONDER NEWS\nbe accessed?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("Communication standby…\nB Button: Cancel"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Communicating…");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("Communication completed.");
ALIGNED(4) const u8 gText_CommunicationError[] = _("Communication error.");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("Communication has been canceled.");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("Throw away the WONDER CARD\nand input a new CARD?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("You haven't received the CARD's gift\nyet. Input a new CARD anyway?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("A WONDER CARD has been received\nfrom {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("A WONDER NEWS item has been\nreceived from {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("A new WONDER CARD has been\nreceived.");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("A new WONDER NEWS item has been\nreceived.");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("A new STAMP has been received.");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("A new TRAINER has arrived.");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("You already had that\nWONDER CARD.");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("You already had that\nWONDER NEWS item.");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("You already had that\nSTAMP.");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("There's no more room for adding\nSTAMPS.");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("Your record has been uploaded via\nWIRELESS COMMUNICATION.");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("You can't accept a WONDER CARD\nfrom this TRAINER.");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("You can't accept WONDER NEWS\nfrom this TRAINER.");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("Nothing was sent over…");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("What would you like to do\nwith the WONDER CARDS?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("What would you like to do\nwith the WONDER NEWS?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("Sending your WONDER CARD…");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("Sending your WONDER NEWS item…");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("Your WONDER CARD has been sent\nto {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("Your WONDER NEWS item has been\nsent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("A STAMP has been sent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("A GIFT has been sent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("The other TRAINER has the same\nWONDER CARD already.");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("The other TRAINER has the same\nWONDER NEWS already.");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("The other TRAINER has the same\nSTAMP already.");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("The other TRAINER canceled\ncommunication.");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("You can't send a MYSTERY GIFT to\nthis TRAINER.");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("If you throw away the CARD,\nits event won't happen. Okay?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("Is it okay to discard this\nNEWS item?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("You haven't received the\nGIFT. Is it okay to discard?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("Data will be saved.\nPlease wait.");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("Save completed.\nPlease press the A Button.");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("The WONDER CARD was thrown away.");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("The WONDER NEWS was thrown away.");
ALIGNED(4) const u8 gText_MysteryGift[] = _("MYSTERY GIFT");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK {B_BUTTON}EXIT");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK {B_BUTTON}CANCEL");
const u8 gText_PlayersBattleResults[] = _("{PLAYER}'s BATTLE RESULTS");
const u8 gText_TotalRecordWLD[] = _("TOTAL RECORD W:{STR_VAR_1} L:{STR_VAR_2} D:{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 0x53}WIN{CLEAR_TO 0x80}LOSE{CLEAR_TO 0xB0}DRAW");
const u8 gText_CommunicationStandby5[] = _("Communication standby…");
const u8 gDaycareText_GetAlongVeryWell[] = _("Parece que los dos se llevan\nestupendamente.");
const u8 gDaycareText_GetAlong[] = _("Parece que los dos se llevan bien.");
const u8 gDaycareText_DontLikeOther[] = _("Parece que los dos no se llevan\nmuy bien.");
const u8 gDaycareText_PlayOther[] = _("Los dos prefieren jugar con otros\nPOKéMON antes que entre ellos.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("SALIR");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("TIEMPO RECORD");
const u8 gText_TimeCleared[] = _("TIEMPO EMPLEADO ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} seg.");
const u8 gText_TrainerHill1F[] = _("1P");
const u8 gText_TrainerHill2F[] = _("2P");
const u8 gText_TrainerHill3F[] = _("3P");
const u8 gText_TrainerHill4F[] = _("4P");
const u8 gText_TeachWhichMoveToPkmn[] = _("¿Enseñar qué {STR_VAR_3} a\n{STR_VAR_1}?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("¿Enseñar {STR_VAR_2}?");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("¡{STR_VAR_1} aprendió\n{STR_VAR_2}!");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} intenta aprender\n{STR_VAR_2}.\pPero {STR_VAR_1} no puede aprender\nmás de cuatro movimientos.\p¿Eliminar un movimiento antiguo para\nhacer sitio a {STR_VAR_2}?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("¿Dejar de intentar enseñar\n{STR_VAR_2}?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2 y {PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}¡Puf!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} olvidó {STR_VAR_3}.\pY…\p{STR_VAR_1} aprendió {STR_VAR_2}.");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} no aprendió el\nmovimiento {STR_VAR_2}."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("¿Rendirse en enseñar un nuevo\nmovimiento a {STR_VAR_1}?");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("¿Qué movimiento debería\nolvidar?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("MOV. COMBATE");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("MOV. CONCURSO");
const u8 gText_MoveRelearnerType[] = _("TIPO/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("POTENCIA/");
const u8 gText_MoveRelearnerAccuracy[] = _("PRECIS./");
const u8 gText_MoveRelearnerAppeal[] = _("EXHIBICIÓN");
const u8 gText_MoveRelearnerJam[] = _("EXHIB. RIVAL");
const u8 gText_ClearAllSaveData[] = _("¿Borrar todos los datos de guardado?");
const u8 gText_ClearingData[] = _("Borrando datos…\nPor favor espera.");
const u8 gText_IsThisTheCorrectTime[] = _("¿Es esta la hora correcta?");
const u8 gText_Confirm3[] = _("CONFIRMAR");
const u8 gText_Cancel4[] = _("CANCELAR");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("Esperando comunicación…\nEsperando a que el otro jugador elija.");
const u8 gText_BattleWasRefused[] = _("Se rechazó el combate.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("Combate rechazado.{PAUSE 60}");
const u8 gText_NoWeather[] = _("SIN TIEMPO"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("SOLEADO"); // Unused
const u8 gText_Sunny2[] = _("SOLEADO2"); // Unused
const u8 gText_Rain[] = _("LLUVIA"); // Unused
const u8 gText_Snow[] = _("NIEVE"); // Unused
const u8 gText_Lightning[] = _("TORMENTA"); // Unused
const u8 gText_Fog[] = _("NIEBLA"); // Unused
const u8 gText_VolcanoAsh[] = _("CENIZA"); // Unused
const u8 gText_Sandstorm[] = _("TORMENTA ARENA"); // Unused
const u8 gText_Fog2[] = _("NIEBLA2"); // Unused
const u8 gText_Seafloor[] = _("FONDO MARINO"); // Unused
const u8 gText_Cloudy[] = _("NUBLADO"); // Unused
const u8 gText_Sunny3[] = _("SOLEADO3"); // Unused
const u8 gText_HeavyRain[] = _("LLUVIA TORRENCIAL"); // Unused
const u8 gText_Seafloor2[] = _("FONDO MARINO2"); // Unused
const u8 gText_DelAll[] = _("BORRAR TODO");
const u8 gText_Cancel5[] = _("CANCELAR");
const u8 gText_Ok2[] = _("OK");
const u8 gText_Quiz[] = _("PREGUNTA");
const u8 gText_Answer[] = _("RESPUESTA");
const u8 gText_PokeBalls[] = _("POKé BALLS");
const u8 gText_Berry[] = _("BAYA");
const u8 gText_Berries[] = _("BAYAS");
const u8 gText_Obtained999RareCandies[] = _("¡Obtuviste 999 CARAMELORAROS!{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOn[] = _("El Repartir Exp. se ha activado.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("El Repartir Exp. se ha desactivado.{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("FANTASMA");
const u8 gText_Boulderbadge[] = _("MEDALLA ROCA");
const u8 gText_Cascadebadge[] = _("MEDALLA CASCADA");
const u8 gText_Thunderbadge[] = _("MEDALLA TRUENO");
const u8 gText_Rainbowbadge[] = _("MEDALLA ARCOÍRIS");
const u8 gText_Soulbadge[] = _("MEDALLA ALMA");
const u8 gText_Marshbadge[] = _("MEDALLA PANTANO");
const u8 gText_Volcanobadge[] = _("MEDALLA VOLCÁN");
const u8 gText_Earthbadge[] = _("MEDALLA TIERRA");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("OAK: Es muy importante conocer\na tus POKéMON a fondo.\p");
const u8 gText_OakThisIsListOfPokemon[] = _("Esta es una lista de tus POKéMON,\n{PLAYER}.\pÁbrela para consultar los datos\ny movimientos de tus POKéMON.\pTambién eliges POKéMON aquí si\nquieres usar un objeto en uno.{PAUSE_UNTIL_PRESS}");

const u8 gText_GBPlayerOn[] = _("Se activó el Reproductor GB.\nSonidos del pasado llenan el aire.{PAUSE_UNTIL_PRESS}");
const u8 gText_GBPlayerOff[] = _("Se desactivó el Reproductor GB.\nLos sonidos nostálgicos se desvanecen.{PAUSE_UNTIL_PRESS}");

const u8 gText_Sunday[] = _("DOMINGO");
const u8 gText_Monday[] = _("LUNES");
const u8 gText_Tuesday[] = _("MARTES");
const u8 gText_Wednesday[] = _("MIÉRCOLES");
const u8 gText_Thursday[] = _("JUEVES");
const u8 gText_Friday[] = _("VIERNES");
const u8 gText_Saturday[] = _("SÁBADO");
const u8 gText_LoveBall[] =     _("LOVE    / PECHA  / (FRY/PSY)");
const u8 gText_Lure[] =         _("LURE    / RAWST  / (WTR/DRG)");
const u8 gText_FriendBall[] =   _("FRIEND / CHERI  / (BUG/GRS)");
const u8 gText_Heavy[] =        _("HEAVY   / ORAN   / (RCK/GND/STL)");
const u8 gText_Moon[] =         _("MOON    / CHESTO / (DRK/GST/PSN)");
const u8 gText_Fast[] =         _("FAST    / ASPEAR / (ELC/FIG/FIR)");
const u8 gText_LevelBall[] =    _("LEVEL  / PERSIM / (NRM/FLY/ICE)");
const u8 gText_Vermilion[] = _("VERMILION");
const u8 gText_Olivine[] = _("OLIVINE");
const u8 gText_Floor0[] = _("Floor 0");
const u8 gText_Pal[] = _("Pal");
const u8 gText_Underling[] = _("Underling");
const u8 gText_Strategy[] = _("Strategy");
const u8 gText_Training[] = _("Training");
const u8 gText_Cheating[] = _("Cheating");
const u8 gText_WeakPerson[] = _("Weak person");
const u8 gText_ToughPerson[] = _("Tough person");
const u8 gText_Anybody[] = _("Anybody");
const u8 gText_Love2[] = _("Love");
const u8 gText_Violence[] = _("Violence");
const u8 gText_Knowledge[] = _("Knowledge");
const u8 gText_Tough3[] = _("Tough");
const u8 gText_Weak[] = _("Weak");
const u8 gText_Both[] = _("Both");
const u8 gText_GreenStone[] = _("GREEN STONE");
const u8 gText_RedStone[] = _("RED STONE");
const u8 gText_BlueStone[] = _("BLUE STONE");
