VermilionCity_House2_hns_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "¿Conoces el MAGNETOTRÉN?\p"
	.string "Es un tren que llega hasta\n"
	.string "CIUDAD TRIGAL, en JOHTO.$"

VermilionCity_House2_Text_Youngster:
	.string "Quiero ir a CIUDAD AZAFRÁN\n"
	.string "para ver el MAGNETOTRÉN.$"
