BlackthornCity_hns_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BlackthornCity_OnFrame
	map_script MAP_SCRIPT_ON_LOAD, BlackthornCity_OnLoad
	map_script MAP_SCRIPT_ON_TRANSITION, BlackthornCity_EventScript_CityEnter
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

BlackthornCity_OnLoad::
	goto_if_unset FLAG_BADGE05_GET, BlackThornCity_EventScript_MoveGymBoy
	goto_if_unset FLAG_BADGE06_GET, BlackThornCity_EventScript_MoveGymBoy
	goto_if_unset FLAG_BADGE07_GET, BlackThornCity_EventScript_MoveGymBoy
	end

BlackThornCity_EventScript_MoveGymBoy::
	setobjectxyperm LOCALID_BLACKTHORN_BOY, 24, 27
	end

BlackthornCity_OnFrame::
	map_script_2 VAR_BLACKTHORN_CITY_STATE, 4, BlackthornCity_EventScript_Call
	.2byte 0

BlackthornCity_EventScript_CityEnter:: 
	setflag FLAG_VISITED_BLACKTHORN_CITY
	callnative SetTimeBasedEncounters
	end

BlackthornCity_EventScript_Call::
	lock
	setspeaker BlackthornCity_Text_ElmName
	pokenavcall BlackthornCity_Text_ElmCall
	waitmessage
	delay 30
	setvar VAR_BLACKTHORN_CITY_STATE, 5
	setvar VAR_NEWBARKTOWN_LABSTATE, 7
	release
	end

BlackthornCity_Text_ElmName:
	.string "PROF. ELM$"

BlackthornCity_Text_BaobaCall:
	.string "DIRECTOR BAOBA: ¡{PLAYER}!\p"
	.string "Soy el DIRECTOR BAOBA.\p"
	.string "Te llamo para contarte que\n"
	.string "¡la ZONA SAFARI se ha ampliado!\p"
	.string "¡Ven a visitarnos!$"

BlackthornCity_Text_ElmCall:
	.string "PROF. ELM: ¿Hola, {PLAYER}?\p"
	.string "Tengo algo para ti.\n"
	.string "¿Puedes pasarte por el LABORATORIO?\p"
	.string "¡Hasta luego!$"

BlackThornCity_EventScript_Sage::
	lock
	faceplayer
	goto_if_eq VAR_BLACKTHORN_CITY_STATE, 1, BlackThornCity_EventScript_SageRefuse
	msgbox BlackthornGrampsGrantsEntryText, MSGBOX_DEFAULT
	closemessage
	release
	end

BlackThornCity_EventScript_SageRefuse::
	msgbox BlackthornGrampsRefusesEntryText, MSGBOX_DEFAULT
	closemessage
	release
	end

BlackThornCity_Trigger_Sage::
	lock
	turnobject LOCALID_BLACKTHORN_SAGE, DIR_EAST
	msgbox BlackthornGrampsRefusesEntryText, MSGBOX_DEFAULT
	closemessage
	applymovement OBJ_EVENT_ID_PLAYER Common_Movement_WalkDown1
	waitmovement 0
	turnobject LOCALID_BLACKTHORN_SAGE, DIR_SOUTH
	release
	end

BlackthornCity_EventScript_GymBoy::
	lock
	faceplayer
	goto_if_unset FLAG_BADGE05_GET, BlackThornCity_EventScript_GymBoyNotReady
	goto_if_unset FLAG_BADGE06_GET, BlackThornCity_EventScript_GymBoyNotReady
	goto_if_unset FLAG_BADGE07_GET, BlackThornCity_EventScript_GymBoyNotReady
	goto_if_eq VAR_BLACKTHORN_CITY_STATE, 1, BlackThornCity_EventScript_GymBoyBefore
	msgbox BlackthornCity_Text_ClairIsBeaten, MSGBOX_DEFAULT
	closemessage
	release
	end	

BlackThornCity_EventScript_GymBoyNotReady::
	msgbox BlackthornCity_Text_ClairNotReady, MSGBOX_DEFAULT
	closemessage
	release
	end

BlackThornCity_EventScript_GymBoyBefore::
	msgbox BlackthornCity_Text_ClairIsIn, MSGBOX_DEFAULT
	closemessage
	release
	end	

BlackthornCity_EventScript_BlackBelt::
	msgbox BlackBeltText_VoicesInMyHead, MSGBOX_NPC
	end

BlackthornCity_EventScript_CoolTrainerF::
	msgbox BlackthornCooltrainerF1Text, MSGBOX_NPC
	end

BlackthornCity_EventScript_Youngster::
	msgbox BlackthornYoungsterText, MSGBOX_NPC
	end

BlackthornCity_EventScript_CoolTrainerF2::
	msgbox BlackthornCooltrainerF2Text, MSGBOX_NPC
	end

BlackthornCity_EventScript_CitySign::
	msgbox BlackthornCitySignText, MSGBOX_SIGN
	end

BlackthornCity_EventScript_GymSign::
	msgbox BlackthornGymSignText, MSGBOX_SIGN
	end

BlackthornCity_EventScript_MoveHouseSign::
	msgbox BlackthornCity_Text_MoveDeletersHouseSign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_DragonsDenSign::
	msgbox BlackthornCity_Text_DragonDenSign, MSGBOX_SIGN
	end

BlackthornCity_EventScript_Santos::
	lock
	faceplayer
	goto_if_set FLAG_GOT_SPELL_TAG, BlackthornCity_EventScript_SantosCompleted
	msgbox BlackthornCity_MeetSantosText, MSGBOX_DEFAULT
	closemessage
	multichoice 20, 0, MULTI_DAYS_OF_WEEK, FALSE
	switch VAR_RESULT
	case 0, BlackthornCity_EventScript_SantosNope
	case 1, BlackthornCity_EventScript_SantosNope
	case 2, BlackthornCity_EventScript_SantosNope
	case 3, BlackthornCity_EventScript_SantosNope
	case 4, BlackthornCity_EventScript_SantosNope
	case 5, BlackthornCity_EventScript_SantosNope
	case 6, BlackthornCity_EventScript_SantosYes
	case 7 BlackthornCity_EventScript_SantosCancel
	case MULTI_B_PRESSED, BlackthornCity_EventScript_SantosCancel
	closemessage
	release
	end
BlackthornCity_EventScript_SantosYes::
	msgbox BlackthornCity_SantosGivesGiftText, MSGBOX_DEFAULT
	giveitem ITEM_SPELL_TAG
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	setflag FLAG_GOT_SPELL_TAG
	msgbox BlackthornCity_SantosGaveGiftText, MSGBOX_DEFAULT
	closemessage
	release
	end
BlackthornCity_EventScript_SantosNope::
	msgbox BlackthornCity_SantosNopeText, MSGBOX_DEFAULT
	closemessage
	release
	end
BlackthornCity_EventScript_SantosCancel::
	closemessage
	release
	end
BlackthornCity_EventScript_SantosCompleted::
	msgbox BlackthornCity_SantosSaturdayText, MSGBOX_DEFAULT
	closemessage
	release
	end


BlackthornCity_Text_ClairNotReady:
	.string "DÉBORA, nuestra LÍDER, ha seguido\n"
	.string "tus progresos.\p"
	.string "Pero solo combate contra quien ya\n"
	.string "tenga siete MEDALLAS.$"

BlackthornCity_Text_ClairIsIn:
	.string "DÉBORA, nuestra LÍDER, te está\n"
	.string "esperando.\p"
	.string "Pero un Entrenador cualquiera no\n"
	.string "tendría ninguna posibilidad.$"

BlackthornCity_Text_ClairIsBeaten:
	.string "¿Has derrotado a DÉBORA?\p"
	.string "¡Es increíble!\p"
	.string "Nunca había perdido contra nadie\n"
	.string "que no fuera LANCE.$"

BlackthornGrampsRefusesEntryText:
	.string "No. Aquí solo pueden entrenar los\n"
	.string "elegidos.\p"
	.string "Por favor, márchate.$"

BlackthornGrampsGrantsEntryText:
	.string "Si DÉBORA lo permite, su abuelo,\n"
	.string "nuestro MAESTRO, también.\p"
	.string "Puedes entrar.$"

BlackBeltText_VoicesInMyHead:
	.string "¡Auuu! ¡Oigo voces en mi cabeza!\p"
	.string "¿Eh? ¡Estoy escuchando la radio!$"

BlackthornCooltrainerF1Text:
	.string "¿Harás que tus POKéMON recuerden\n"
	.string "algún movimiento?$"

BlackthornYoungsterText:
	.string "Todos los maestros dragón proceden\n"
	.string "de CIUDAD ENDRINO.$"

BlackthornCity_MeetSantosText:
	.string "SANTOS: …\p"
	.string "Soy SANTOS, de la familia semanal.\p"
	.string "Adivina qué día es hoy.$"

BlackthornCity_SantosGivesGiftText:
	.string "Puedes quedarte con esto…$"

BlackthornCity_SantosGaveGiftText:
	.string "SANTOS: …\p"
	.string "ETIQUETA HECHIZO…\p"
	.string "Potencia los movimientos FANTASMA…\p"
	.string "Te dará miedo…$"

BlackthornCity_SantosSaturdayText:
	.string "SANTOS: …\p"
	.string "Nos veremos otro sábado…\p"
	.string "Ya no tendré más regalos…$"

BlackthornCity_SantosNopeText:
	.string "SANTOS: No…$"

BlackthornCooltrainerF2Text:
	.string "¿Has cruzado la RUTA HELADA?\p"
	.string "¡Debes de ser un Entrenador genial!$"

BlackthornCitySignText:
	.string "CIUDAD ENDRINO\p"
	.string "Un tranquilo retiro de montaña$"

BlackthornGymSignText:
	.string "GIMNASIO POKéMON DE ENDRINO\n"
	.string "LÍDER: DÉBORA\p"
	.string "La bendecida maestra dragón$"

BlackthornCity_Text_MoveDeletersHouseSign:
	.string "CASA DE LOS MAESTROS DE MOVIMIENTOS$"

BlackthornCity_Text_DragonDenSign:
	.string "GUARIDA DRAGÓN MÁS ADELANTE$"

