CeruleanCity_Gym_hns_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CeruleanCity_Gym_OnFrame
	.byte 0

CeruleanCity_Gym_OnFrame::
	map_script_2 VAR_KANTO_ROCKET_STORY_STATE, 2,  CeruleanCity_Gym_EventScript_RocketGrunt
	map_script_2 VAR_TEMP_0, 0,  CeruleanCity_Gym_EventScript_TryMachinePart
	.2byte 0

CeruleanCity_Gym_EventScript_RocketGrunt::
	lock
	applymovement LOCALID_CERULEAN_GYM_ROCKET, CeruleanCity_Gym_Movement_GruntBumpPlayer
	delay 20
	playse SE_BANG
	waitmovement 0
	
	msgbox CeruleanGym_Text_GruntIntro, MSGBOX_DEFAULT
	closemessage
	playse SE_PIN
	applymovement LOCALID_CERULEAN_GYM_ROCKET, Common_Movement_ExclamationMark
	delay 55
	waitmovement LOCALID_CERULEAN_GYM_ROCKET
	applymovement LOCALID_CERULEAN_GYM_ROCKET, CeruleanCity_Gym_Movement_GruntWalkBack
	waitmovement 0
	msgbox CeruleanGym_Text_GruntBigMistake, MSGBOX_DEFAULT
	applymovement LOCALID_CERULEAN_GYM_ROCKET, CeruleanCity_Gym_Movement_GruntWalkToPlayerAgain
	waitmovement 0
	msgbox CeruleanGym_Text_GruntBye, MSGBOX_DEFAULT
	closemessage
	applymovement OBJ_EVENT_ID_PLAYER, CeruleanCity_Gym_Movement_PlayerSlide
	delay 10
	applymovement LOCALID_CERULEAN_GYM_ROCKET, CeruleanCity_Gym_Movement_GruntLeave
	waitmovement 0
	fadescreenswapbuffers FADE_TO_BLACK
	playse SE_EXIT
	setflag FLAG_HIDE_CERULEAN_GYM_ROCKET
	removeobject LOCALID_CERULEAN_GYM_ROCKET
	fadescreenswapbuffers FADE_FROM_BLACK
	clearflag FLAG_HIDE_CERULEAN_CAPE_ROCKET
	setvar VAR_KANTO_ROCKET_STORY_STATE, 3
	release
	end

CeruleanCity_Gym_EventScript_TryMachinePart::
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 5, CeruleanCity_Gym_EventScript_MachinePart
	setvar VAR_TEMP_0, 1
	end

CeruleanCity_Gym_EventScript_MachinePart::
	special SpawnCameraObject
	applymovement OBJ_EVENT_ID_CAMERA, CeruleanCity_Movement_CameraPanUp
	waitmovement 0
	delay 30
	setvar VAR_0x8004, 5  @ x
	setvar VAR_0x8005, 13  @ y
	playse SE_PIN
	call Route110_TrickHouseEntrance_EventScript_DoHidingSpotSparkle
	delay 55
	applymovement OBJ_EVENT_ID_CAMERA, CeruleanCity_Movement_CameraPanDown
	waitmovement 0
	special RemoveCameraObject
	setvar VAR_TEMP_0, 1
	end

CeruleanCity_Gym_EventScript_MachinePartItem::
	goto_if_lt VAR_KANTO_ROCKET_STORY_STATE, 5, CeruleanCity_Gym_EventScript_DoNothing
	goto_if_ge VAR_KANTO_ROCKET_STORY_STATE, 6, CeruleanCity_Gym_EventScript_DoNothing
	finditem ITEM_MACHINE_PART
	setvar VAR_KANTO_ROCKET_STORY_STATE, 6
	setflag FLAG_HIDDEN_ITEM_MACHINE_PART
	end

CeruleanCity_Gym_EventScript_DoNothing::
	end

CeruleanCity_Movement_CameraPanUp:
	walk_up
	walk_up
	walk_up
	step_end

CeruleanCity_Movement_CameraPanDown:
	walk_down
	walk_down
	walk_down
	step_end

CeruleanCity_Gym_Movement_GruntBumpPlayer:
	walk_fast_down
	walk_fast_down
	walk_in_place_fast_down
	lock_facing_direction
	jump_up
	unlock_facing_direction
	delay_16
	walk_down
	step_end

CeruleanCity_Gym_Movement_GruntWalkBack:
	lock_facing_direction
	walk_slow_up
	walk_slow_up
	unlock_facing_direction
	step_end

CeruleanCity_Gym_Movement_GruntWalkToPlayerAgain:
	walk_down
	walk_down
	step_end

CeruleanCity_Gym_Movement_PlayerSlide:
	lock_facing_direction
	walk_fast_right
	unlock_facing_direction
	step_end

CeruleanCity_Gym_Movement_GruntLeave:
	walk_fast_down
	walk_in_place_fast_down
	step_end

CeruleanCity_Gym_EventScript_Statue::
	lockall
	goto_if_set FLAG_BADGE10_GET, CeruleanCity_Gym_EventScript_GymStatuePostVictory
	msgbox CeruleanCity_Gym_Text_GymStatue
	releaseall
	end

CeruleanCity_Gym_EventScript_StatueDuringRocket::
	msgbox CeruleanGym_Text_Note, MSGBOX_SIGN
	end 

CeruleanCity_Gym_EventScript_GymStatuePostVictory::
	msgbox CeruleanCity_Gym_Text_GymStatuePlayerWon
	releaseall
	end

CeruleanGym_EventScript_Diana::
	trainerbattle_single TRAINER_DIANA_HNS, CeruleanGym_Text_SwimmerfDianaSeen, CeruleanGym_Text_SwimmerfDianaBeaten
	msgbox CeruleanGym_Text_SwimmerfDianaAfter, MSGBOX_AUTOCLOSE
	end

CeruleanGym_EventScript_Briana::
	trainerbattle_single TRAINER_BRIANA_HNS, CeruleanGym_Text_SwimmerfBrianaSeen, CeruleanGym_Text_SwimmerfBrianaBeaten
	msgbox CeruleanGym_Text_SwimmerfBrianaAfter, MSGBOX_AUTOCLOSE
	end

CeruleanGym_EventScript_Parker::
	trainerbattle_single TRAINER_PARKER_HNS, CeruleanGym_Text_SwimmermParkerSeen, CeruleanGym_Text_SwimmermParkerBeaten
	msgbox CeruleanGym_Text_SwimmermParkerAfter, MSGBOX_AUTOCLOSE
	end

CeruleanCity_Gym_EventScript_GymGuy::
	goto_if_set FLAG_DEFEATED_CERULEAN_GYM, CeruleanCity_Gym_EventScript_GymGuyAfter
	msgbox CeruleanGym_Text_GuideIntro, MSGBOX_NPC
	end

CeruleanCity_Gym_EventScript_GymGuyAfter::
	msgbox CeruleanGym_Text_GuideWin, MSGBOX_NPC
	end

CeruleanCity_Gym_Text_GymStatue::
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
	.string "WINNING TRAINERS:\n"
	.string "BLUE, RED$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
	.string "BLUE, RED, {PLAYER}$"

CeruleanGym_Text_Note:
	.string "Perdón, estaré fuera un rato.\p"
	.string "MISTY, LÍDER DEL GIMNASIO\p"
	.string "Como MISTY no está, nosotros\n"
	.string "también nos vamos.\p"
	.string "ENTRENADORES DEL GIMNASIO$"

CeruleanCity_Gym_EventScript_Misty::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_CERULEAN_GYM, CeruleanCity_Gym_EventScript_Misty_Defeated
	msgbox CeruleanGym_Text_MistyIntro, MSGBOX_DEFAULT
	trainerbattle_no_intro TRAINER_MISTY_HNS, CeruleanGym_Text_MistyWinLoss
	message CeruleanGym_Text_ReceivedBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	setflag FLAG_BADGE10_GET
	setflag FLAG_DEFEATED_CERULEAN_GYM
	addvar VAR_NUM_BADGES, 1
	call GymToken_EventScript_Award
	setvar VAR_0x8008, 10
	call Common_EventScript_SetGymTrainers_hns
	msgbox CeruleanGym_Text_Misty_GiveTM, MSGBOX_DEFAULT
	giveitem ITEM_TM_WATER_PULSE
	msgbox CeruleanGym_Text_Misty_ExplainTM, MSGBOX_DEFAULT
	clearflag FLAG_HIDE_CAPE_MISTY
	call_if_eq VAR_SUICUNE_ENCOUNTERS, 5, CeruleanCity_Gym_SetSuicuneScene
	closemessage
	release
	end

CeruleanCity_Gym_SetSuicuneScene::
	setvar VAR_SUICUNE_ENCOUNTERS, 6
	clearflag FLAG_HIDE_ROUTE25_SUICUNE
	return

CeruleanCity_Gym_EventScript_Misty_Defeated::
	msgbox CeruleanGym_Text_MistyFightDone, MSGBOX_DEFAULT
	closemessage
	release
	end

CeruleanGym_Text_GruntIntro:
	.string "¡Uups! ¡Yo sentir!\n"
	.string "Tú no hacer daño,\l"
	.string "¿de acuerdo?\p"
	.string "Yo muy ocupado.\n"
	.string "No tener tiempo\p"
	.string "para hablar\n"
	.string "contigo. No poder\l"
	.string "verme nadie.$"
CeruleanGym_Text_GruntBigMistake:
	.string "¡Oh, no! ¡Tú\n"
	.string "verme! ¡Yo cometer\l"
	.string "gran error!$"
CeruleanGym_Text_GruntBye:
	.string "¡Oye! Tú olvidar\n"
	.string "que me has visto,\p"
	.string "¿vale? Tú ver, oír\n"
	.string "y saber nada, ¿de\p"
	.string "acuerdo?\n"
	.string "¡Adiós, joven!\p"
	.string "¡Hasta la vista!$"
CeruleanGym_Text_Note1:
	.string "Perdón, estaré fuera un rato.\p"
	.string "MISTY, LÍDER DEL GIMNASIO\p"
	.string "Como MISTY no está, nosotros\n"
	.string "también nos vamos.\p"
	.string "ENTRENADORES DEL GIMNASIO$"

CeruleanGym_Text_MistyIntro:
	.string "MISTY: ¡Te estaba\n"
	.string "esperando, pelma!\p"
	.string "Seguro que tienes\n"
	.string "muchas MEDALLAS de\p"
	.string "JOHTO, pero no me\n"
	.string "subestimes en\l"
	.string "absoluto.\p"
	.string "¡Mis POKéMON de\n"
	.string "tipo agua son\l"
	.string "fuertes!$"
CeruleanGym_Text_MistyWinLoss:
	.string "MISTY: Eres\n"
	.string "realmente genial…\p"
	.string "Reconozco tu gran\n"
	.string "experiencia…\p"
	.string "Aquí tienes la\n"
	.string "MEDALLA CASCADA.$"
CeruleanGym_Text_ReceivedBadge:
	.string "{PLAYER} recibió\n"
	.string "MEDALLA CASCADA.$"
CeruleanGym_Text_MistyFightDone:
	.string "MISTY: ¿Hay muchos\n"
	.string "entrenadores\p"
	.string "fuertes en JOHTO?\n"
	.string "Como tú, digo.\p"
	.string "Un día viajaré y\n"
	.string "lucharé contra\p"
	.string "entrenadores\n"
	.string "expertos.$"
CeruleanGym_Text_MistyRematch:
	.string "MISTY: ¡Uau, ahora eres CAMPEÓN\n"
	.string "de KANTO!\p"
	.string "¡Es increíble! Has llegado lejos,\n"
	.string "{PLAYER}.\p"
	.string "Pero no pienso echarme atrás.\p"
	.string "¿Quieres combatir otra vez?$"

CeruleanGym_Text_MistyRematchDefeat:
	.string "MISTY: De verdad que eres bueno…$"

CeruleanGym_Text_SwimmerfDianaSeen:
	.string "Siento haber\n"
	.string "estado fuera.\l"
	.string "¡A lo nuestro!$"
CeruleanGym_Text_SwimmerfDianaBeaten:
	.string "¡Me rindo!\n"
	.string "¡Has ganado!$"
CeruleanGym_Text_SwimmerfDianaAfter:
	.string "Estaré nadando\n"
	.string "tranquilamente.$"
CeruleanGym_Text_SwimmerfBrianaSeen:
	.string "No te desanimes\n"
	.string "por mi elegante\l"
	.string "forma de nadar.$"
CeruleanGym_Text_SwimmerfBrianaBeaten:
	.string "¡Ooh! Has acabado\n"
	.string "conmigo…$"
CeruleanGym_Text_SwimmerfBrianaAfter:
	.string "No fardes tanto de\n"
	.string "haberme vencido.\p"
	.string "MISTY acabará\n"
	.string "contigo si te\l"
	.string "confías demasiado.$"
CeruleanGym_Text_SwimmermParkerSeen:
	.string "¡Glup…!\p"
	.string "¡Soy el primero!\n"
	.string "¡Ven a por mí!$"
CeruleanGym_Text_SwimmermParkerBeaten:
	.string "No puede ser…$"
CeruleanGym_Text_SwimmermParkerAfter:
	.string "MISTY ha mejorado\n"
	.string "mucho en los\l"
	.string "últimos años.\p"
	.string "¡No bajes la\n"
	.string "guardia o acabarás\l"
	.string "mal!$"
CeruleanGym_Text_GuideIntro:
	.string "¡Hola, futuro CAMPEÓN!\p"
	.string "Como MISTY no estaba, yo también\n"
	.string "salí a divertirme. Je, je.$"

CeruleanGym_Text_GuideWin:
	.string "Vaya, me has demostrado lo\n"
	.string "fuerte que eres.\p"
	.string "¡Como siempre, ha sido un combate\n"
	.string "increíble!$"

CeruleanGym_Text_Misty_GiveTM:
	.string "Toma, llévate esto también.$"

CeruleanGym_Text_Misty_ExplainTM:
	.string "Es la MT PULSO AGUA.\p"
	.string "¡Hace daño y a veces también\n"
	.string "provoca confusión!$"
